### ISSUE TITLE
No delay between tutorial steps

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#10]
Need to have a delay between tutorial steps so students can examine code that they have written. Currently, when you complete a step, If there isn't a prompt to run the code, you go immediately to the next step without opportunity to examine the code you've written.

**Comment by pelikhan** [comment]
When a step is completed, we should add an animation that highlights the expected code for a couple seconds before poping up the dialog.

**Comment by pelikhan** [comment]
Results of the last discussion: 
- always display the current goal in the blue tutorial bar (so you can see what needs to be done)
- when the code is completed and we detect it, display a button that says -- "go to next step" + tip.
- when the step involves running, it's implicit so we don't need that "go to next step"

**Comment by brian-swan** [comment]
Has the "go to next step" button been implemented yet? I don't see a change set for this. Or, is this something I need to do when I create a tutorial?

**Comment by pelikhan** [comment]
It is always on.

**Comment by brian-swan** [comment]
I'm not seeing a "go to next step" button in any of my tutorials. I'm on /app/latest.

**Comment by msprotz** [comment]
Brian, as soon as the build is out, you can try this out with the following tutorial: http://touchdevelop.com/app/latest/#hub:follow:crgk

Please let me know if it works for your specific use-case. I believe the macro only makes sense if you insert it at a point where, previously, the tutorial engine would mark the step as selected.

@pelikhan I considered automatically detecting cases where the macro is needed, but that's a bigger endeavor and we've got a busy week, so feel free to open a new ticket for that if needed :)

**Comment by pelikhan** [comment]
What is the macro supposed to do? It did not seem to work for me.

Sent from my Windows Phone
________________________________

**Comment by brian-swan** [comment]
I noticed a slight delay between steps. However...
- The delay wasn't long enough, and
- The delay was confusing because the blue prompt to edit code was still visible (so I wasn't clear that I was finished editing at that point).
Peli's suggestion of introducing a "go to next step" button might address these issues.

I also noticed that I was not prompted to write code for the step following the delay. Is this a bug introduced by the change?

**Comment by msprotz** [comment]
Cool, thanks for the feedback. I'll rework the UI to actually have a "go to next step" button and check about that other bug.

So far nothing changes if you don't use the macro so I'll keep iterating.

**Comment by pelikhan** [comment]
I still don't get what the change is.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Mar 2, 2015 at 9:10 AM -0800, "Jonathan Protzenko" <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool, thanks for the feedback. I'll rework the UI to actually have a "go to next step" button and check about that other bug.

So far nothing changes if you don't use the macro so I'll keep iterating.

-

**Comment by brian-swan** [comment]
Great...thanks! One thought on the "go to next step" button: If you can give the tutorial author control over the text for that button, that would be great. For example, something like this...

**{stcmd:delay:<button text here>}**

...would allow me to make sure the button has text that fits the context of the tutorial. In most cases, it would say something like "Examine your code, then go to the next step."

**Comment by brian-swan** [comment]
I don't think this issue has been resolved, so reopening. Has there been any progress on a 'go to next step' UI?

**Comment by msprotz** [comment]
I'm looking into this right now.

**Comment by msprotz** [comment]
https://www.touchdevelop.com/app?releaseid=2519763761186100000-3f2a6ca3.0ea3.4ed7.1f0f.3e9da5b050b7-protz#hub:follow:crgk

Brian, can you try this tutorial and tell me if that's closer to what you had in mind?

I've set the tooltip to show up after three seconds.

Let me know if anything needs tweaking, then I'll merge (it's on a branch right now).

**Comment by brian-swan** [comment]
Yes! That's what I had in mind...looks great. Thanks!
