### ISSUE TITLE
Direction param in game->set background scene should not be a string

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#100]
Because the parameter used for specifying direction in **game->set background scene** is a string, it can't be "enforced" in a tutorial. If I want students to use a "horizontal" moving background scene, I have no way of enforcing this in a tutorial.

The parameter used for specifying direction should be something other than a string. Perhaps something similar to colors...Have a **direction** object with **horizontal** and **vertical** properties.

**Comment by pelikhan** [comment]
Have you tried the ``{stprecise:horizontal}`` macro to fix this? The TouchDevelop language does not support enums. The only way to fix this would be to provide 2 action for each direction.

**Comment by brian-swan** [comment]
I didn't know about that macro...it does exactly what I want. Thanks!
