### ISSUE TITLE
ios safari: crash when attempting to add a script to a group

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#104]
Seems that there is a iOS Safari specific bug in the APIs the PUT call to https://storage.touchdevelop.com/sessions/... It consistently fails on iPhone or iPad.

**Comment by sebastianburckhardt** [comment]
I have changed the PUT to a POST. Should always have been a POST (I think it had PUT semantics in some early draft, but later became POST).

Server is updated (accepts either one). Client code is updated and checked in.

Maybe this will fix things.

**Comment by pelikhan** [comment]
Still a problem...

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Apr 27, 2015 at 1:33 PM -0700, "Sebastian Burckhardt" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have changed the PUT to a POST. Should always have been a POST (I think it had PUT semantics in some early draft, but later became POST).

Server is updated (accepts either one). Client code is updated and checked in.

Maybe this will fix things.

-

**Comment by pelikhan** [comment]
Safari reports the following error:

                Failed to load resource:; Request header field Content-Type is not allowed by Access-Control-Allow-Headers

**Comment by sebastianburckhardt** [comment]
Server now sends the header for allowing Content-Type header.

**Comment by pelikhan** [comment]
Fixed with the missing header.
