### ISSUE TITLE
Error for output param in an action is confusing

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#106]
When I create an output param in an action, I immediately get the "output parameter 'name' needs to be assigned before the action finishes" error. I understand what is going on here, but new developers are confused. They think they have done something wrong by simply creating an output parameter. We have seen several people quit tutorials when this error appears even though they haven't done anything wrong.
- Can this be turned off in tutorials? (best) and/or,
- Can we show it in a different color and provide text that is more like "Reminder: you'll need to assign 'name' a value before you finish writing this action."

**Comment by mmoskal** [comment]
This is now displayed as a hint.
