### ISSUE TITLE
game->splash text should be a one-line function

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#110]
Currently, **game->splash text** is an event that requires you define the handler in the body of the **done** function. This is conceptual overhead that makes the simple task of showing splash text before a game confusing to young developers. It would be nice if this was a simple one-line function that could be called before a user starts a game (or at any time, really).

**Comment by v-vamell** [comment]
Reassigned as Pri 1 issue - based on the complexity - need a new API

**Comment by brian-swan** [comment]
Is there an ETA for this issue? How likely is it to be fixed? We are at a point in our curriculum development where we are making decisions about how we teach "splash text" (i.e. we are finalizing video scripts). It is important for us to understand what will happen here. We need to decide now on the language we use in our script. Can we assume this will be fixed?

**Comment by pelikhan** [comment]
Caveat: optional arguments not yet supported in tutorials

**Comment by brian-swan** [comment]
Thanks! Is the fix in the game library? If yes, what is the library ID? If no, how do I test the fix?

**Comment by pelikhan** [comment]
It is in the game library. TouchDevelop you to update it.

**Comment by brian-swan** [comment]
Thanks. Found it. Will the options be supported in tutorials eventually?

**Comment by pelikhan** [comment]
File a bug.
