### ISSUE TITLE
Editing action name in tutorials should be the same as editing string

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#112]
When you are prompted to edit an action name in a tutorial, you are prompted to click the "dismiss" button when done. This is how the old string editing prompting worked. The change in string editing (checkmark at the end of the editing box) is great. Can this be applied to action names too?

**Comment by pelikhan** [comment]
I think this fixes it: https://github.com/Microsoft/TouchDevelop/commit/7d0b4c388c05ac44b3a40fc46716cee571788308
