### ISSUE TITLE
Can't delete a record

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#113]
When I create a record (an object, in this case), there is no way to delete it from my app. An example is here: http://tdev.ly/yrcga. Unlike with actions, when I click on the name, there is no option to "cut" or "delete" the record.

**Comment by pelikhan** [comment]
The copy/cut buttons are under the "long" list of object types. Maybe time to revisit that UI.

**Comment by brian-swan** [comment]
I can't find a "long" list. Can you describe how I find it? (or include a screenshot?)

**Comment by pelikhan** [comment]
Hummm. I see that it is hidden in “beginner” skill mode. Is that the skill mode you are using?

**Comment by brian-swan** [comment]
No. I'm in "coder" mode.

**Comment by pelikhan** [comment]
I am seeing this:
![image](https://cloud.githubusercontent.com/assets/4175913/6990221/a973248c-da1c-11e4-808b-f4db3ef74986.png)

**Comment by brian-swan** [comment]
OK. I've found that UI. However, it is not intuitive. Would be better if it were more similar to the UI for deleting an action.

**Comment by msprotz** [comment]
The UI for deleting an action is pretty much the same, it's just that you have to scroll down past the various record types before you see the buttons. I could put these buttons first, above the record types, I guess...

**Comment by pelikhan** [comment]
IMO, the button should be replaced by a “change record type” button that pops up a selection dialog.

**Comment by msprotz** [comment]
Actually, that's what we had previously, then we decided that modal dialogs were inferior in terms of UI interactions, and I implemented the new version.

**Comment by pelikhan** [comment]
Change record is probably not such a common operation.
