### ISSUE TITLE
Can't specify "local" or "replicated" for global var in tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#114]
If I create a tutorial that has a global variable that has been marked at "local" or "replicated", the tutorial will prompt me to create a global variable, but it defaults to "temporary" and doesn't allow for specification as "local" or "replicated". In order to teach more complex topics via tutorials, we need the ability to specify a global variable as "local" or "replicated" in a tutorial.

**Comment by mmoskal** [comment]
This is now also fixed in c958b6e0cd216bc30266147d7600d1900d9f4da0

However, you need to use the {adddecl} macro: http://tdev.ly/mxrzc

**Comment by brian-swan** [comment]
This is great...thanks! However, I found another bug when using this: #116
