### ISSUE TITLE
Support the creation of records in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#115]
If I create a tutorial that uses a record (a table, for example), the tutorial does not prompt me to create the record in the app. Instead, the tutorial fails to prompt for anything. Here's an example: http://tdev.ly/mtkuqaue. 
Ideally, the tutorial engine would handle the creation of a record in much the same way it handles the creation of custom actions. With actions, the tutorial engine prompts for the creation of the action when the it encounters the first action call in the script. With records, it would be ideal if the tutorial engine prompted for the creation of the record upon the first "call" or "use" of the record.
Without this type of support in tutorials, we can't use TD to teach about storing data in tables.

**Comment by mmoskal** [comment]
The example is here: http://tdev.ly/chqde

Not sure about the "replicated" vs "local" stuff yet, but this is reported separately

**Comment by brian-swan** [comment]
There seem to be some problems with this fix. In the example you provide, I'm prompted to create a new resource, but "table" isn't one of the resources available to choose from, so the tutorial essentially comes to a stop.

**Comment by pelikhan** [comment]
Ha, what skill level?

**Comment by brian-swan** [comment]
Coder skill level.

**Comment by pelikhan** [comment]
Right, we hide those in coder level. This setting needs to be disabled in tutorial mode. on me.

**Comment by brian-swan** [comment]
Checking in on the progress of this. This is blocking our curriculum development.
