### ISSUE TITLE
Tutorial prompting: unnecessary object (board)

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#117]
In this tutorial, I'm prompted to create a board object that I never use...I'm eventually prompted to delete it: http://tdev.ly/qogja.

**Comment by mmoskal** [comment]
Ctrl-Alt-D during a tutorial step shows a diff between what is there and what should be there:

![image](https://cloud.githubusercontent.com/assets/10673976/6989922/e58185a0-da16-11e4-9456-671b8421ccb8.png)

The board is essentially understood to be part of the second line. As a workaround, if you split the two lines into separate steps the issue will not occur.

**Comment by mmoskal** [comment]
In fact I've just fixed this one as well, 1eedfd9e56c36f5fe8c
