### ISSUE TITLE
Rename "data" to "vars"

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#118]
Per discussion on 4/6.

**Comment by User0847** [comment]
I ask that the team reconsider this renaming.  I agree that there may be a better heading than "data" for the list of global variables, but I think distinguishing between the scope of global variables and local variables declared in functions/actions is helpful to new coders. Using the heading "vars" obscures that distinction. 

(See also my comment under the proposal to have a "database" section.)

**Comment by brian-swan** [comment]
Agreed that what is important here is distinguishing between the scope of global and local variables. Also agreed that, for new coders, there must be a better name than "data" for the category that contains global variables. In #121 , we are proposing that up to 2 global variables show up alongside local variables in the tray/calculator, thus eliminating the need for new coders to categorize them. The distinction between local and global variables would be the symbol that a student sees. (I need to add this to that issue.)
