### ISSUE TITLE
Add actions to objects (object types)

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#123]
Per discussion on 4/6, allow for actions to be associated with object types (formerly objects). The actions here should show up under the object type definition, not in the actions for the script.

**Comment by pelikhan** [comment]
fixed by bf3d28d8d886f1455d2a0f9302f14a72e7d695c2

**Comment by pelikhan** [comment]
Also 3f029bd561f6d8626fe35e4dd7da01544ff43b4c
