### ISSUE TITLE
"Find references" does not work with method-style call

### ISSUE THREAD

**Issue by thSoft** [Microsoft/TouchDevelop#126]
Finding references to an action does not enumerate action calls in method style (arrow syntax).

**Comment by pelikhan** [comment]
Could you describe in more details the problem? Maybe some screenshots would help.

**Comment by thSoft** [comment]
I create an action with an object as first parameter and call it "on" the object:
![method](https://cloud.githubusercontent.com/assets/118109/7281268/d755ccd6-e928-11e4-8cb1-eb4bb400b801.png)
"Find references" should find this call, but it does not:
![references](https://cloud.githubusercontent.com/assets/118109/7281691/5ad15d6c-e92b-11e4-815c-8e2360e51c94.png)

**Comment by thSoft** [comment]
Did you fix this bug?
