### ISSUE TITLE
Prompts disappear in tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#132]
In this common scenario, tutorial prompts disappear: If I accidentally add an EXTRA output parameter to a custom action, the tutorial engine stops prompting me. See the step in this tutorial that prompts you to add an output param to a custom action: http://tdev.ly/irbuc (you'll have to add an extra output param to see the bug).

**Comment by mmoskal** [comment]
No repro, in any of the three modes. Could you double check? I'm just prompted to delete the additional parameter.

![image](https://cloud.githubusercontent.com/assets/10673976/7286963/1f0046a2-e905-11e4-9277-cc00ae3e8a2e.png)

**Comment by brian-swan** [comment]
Indeed, this seems to have been fixed (I can't repro it either).
