### ISSUE TITLE
Enable ability to set default mode for tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#133]
In a tutorial, we need a way to set the default mode (beginner/coder/expert) for someone following the tutorial. In many cases, a tutorial is designed with a particular mode in mind, so the author should be able to set this. Of course, this is something that will have to be used with discretion.

**Comment by pelikhan** [comment]
Have you tried the macro {stmode:...} ?

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Apr 16, 2015 at 12:25 PM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


In a tutorial, we need a way to set the default mode (beginner/coder/expert) for someone following the tutorial. In many cases, a tutorial is designed with a particular mode in mind, so the author should be able to set this. Of course, this is something that will have to be used with discretion.

-

**Comment by brian-swan** [comment]
I didn't realize there was already a macro for this...apologies (looks like it is {steditormode:...} ). However, when I read the docs, it says that the only two options are "block" and "pro". I tried using "coder", but I was still prompted to choose a mode at the beginning of the tutorial (which is what I'm trying to avoid).
Should this issue be changed to "support 'coder' for the steditormode macro"?

**Comment by pelikhan** [comment]
Yes.

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, Apr 17, 2015 at 10:16 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


I didn't realize there was already a macro for this...apologies (looks like it is {steditormode:...} ). However, when I read the docs, it says that the only two options are "block" and "pro". I tried using "coder", but I was still prompted to choose a mode at the beginning of the tutorial (which is what I'm trying to avoid).
Should this issue be changed to "support 'coder' for the steditormode macro"?

-

**Comment by brian-swan** [comment]
Closing this and opening a new issue - #138
