### ISSUE TITLE
Discuss a new repeat construct in TouchDevelop AST

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#134]
Blockly has `forever` blocks and `repeat N times` blocks. We assume these are good primitives for kids (after all, it's clearer than `while true` and `for` loops). However, when we "graduate" from Blockly to TouchDevelop, the `while true` and `for` loops appear.

I think that's okay (after all, you're graduating towards a more sophisticated programming environment); Peli says to reduce friction, these should appear as "repeat Math.infinity times" and "repeat N times" respectively, which is also a valid point.
- There's a fair bit of work if we change the AST; that being said, we can make the base visitor class call into `visitWhile` and `visitFor`, meaning that if everything is done well, that should be manageable.
- We could also expose these as TouchDevelop primitives (not just for translated programs), in the calculator and the like.

Thoughts?

**Comment by tballmsft** [comment]
I am worried about having too many different control constructs in TouchDevelop.

**Comment by mmoskal** [comment]
I agree. I’m already not too happy about having 3 different loops.

What I would like to add is “return”, “break” and “continue” statements ;) Separate issue though.

**Comment by pelikhan** [comment]
‘’repeat’’ is a fundamental block  that is much easier to grasp for beginners than while/for.

**Comment by mmoskal** [comment]
We could render “for” as “repeat” in beginner mode, and maybe use something “repetition#” instead of “i”.

**Comment by msprotz** [comment]
What we could do in coder mode is:
- figure out whether the variable is used in the body of the loop,
- if index is used: render as a "for" loop both when editing the statement and when *not* editing the statement
- if index is unused: render as a "for" loop when editing the statement, but render as a "repeat" loop when not editing the statement.
Thoughts?
- if no

**Comment by pelikhan** [comment]
If something is displayed on the screen, there must be a button for it - otherwise users have a hard time copying snippets.

Sent from Outlook<http://taps.io/outlookmobile>

_____________________________
