### ISSUE TITLE
Prescriptive hints (a.k.a. enums)

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#135]
Right now, the special `{hints:` syntax for comments results in the calculator showing good suggestions. For instance, when I type `♻ microbit → button pressed`, the calculator provides me with the left and right options.

That's great, but we might want to have a different kind of hints that generate type-checking errors when anything falls outside the set of accepted values.

- Abusing the special comments system would probably result in a massive pile of hacks, since we would lose the property that only the library signature suffices to type-check a program that uses it.
- This would also entail modifications to the type-checker.

One way to do it would be to add properties to a function (besides atomic and private), that would describe for one of their arguments the set of admissible values. This property would appear in the type of the function, would be type-checked accordingly, and if used would no longer require the use of the hints mechanism.

Thoughts?

**Comment by pelikhan** [comment]
Michal added ``{enum:...}`` macro.
