### ISSUE TITLE
Bady copy/paste experience from outside to inside a library

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#137]
STR:
- copy code from script X that contains a series of calls to the microbit library (e.g. ♻ microbit → debug)
- paste that code _inside_ a function from the microbit library
- the references to microbit functions have been replaced by ♻ → microbit and errors that "I cannot find the property microbit on ♻"

**Comment by pelikhan** [comment]
The general scenario is copy from the library docs into outside script.

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, Apr 17, 2015 at 10:05 AM -0700, "Jonathan Protzenko" <notifications@github.com<mailto:notifications@github.com>> wrote:


STR:

  *   copy code from script X that contains a series of calls to the microbit library (e.g. ? microbit ? debug)
  *   paste that code inside a function from the microbit library
  *   the references to microbit functions have been replaced by ? ? microbit and errors that "I cannot find the property microbit on ?"

-
