### ISSUE TITLE
Can't create table and action in app tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#139]
This is a fairly specific scenario (but one that is important to our curriculum development): I've created a tutorial that 1) creates a table, then 2) creates a custom action that populates the table. The example is here: http://tdev.ly/sdsea. The tutorial successfully prompts for creating the table, then for creating the action, but it then freezes before prompting for the body of the action.
I have tried to repro this in a tutorial that only creates an action (no table), but cannot. i.e. I'm successfully prompted to create the body of the action. Example here: http://tdev.ly/gccwi
I'm in coder mode.

**Comment by mmoskal** [comment]
This is because the "do stuff" is atomic and the "atomic" checkbox was disabled. You will probably make your action non-atomic.
