### ISSUE TITLE
Numbered tutorial steps in app produce "can't find type <page name> page data" error

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#142]
In this tutorial, http://tdev.ly/kajgi, I'm using numbered steps (#0main, #1show). Upon introducing the second numbered step, I get an error when following the tutorial: "can't find type <page name> page data"
This makes it impossible to use numbered steps to create an app tutorial.

**Comment by mmoskal** [comment]
There is a workaround: create "page", copy&paste it and rename result to "#1 page". Then they will share the page data.

**Comment by brian-swan** [comment]
I've tried to follow that workaround, but I can't get it to work. Can you be more specific? In the example I provided, there are pages #0main, show, and #1show (#0main calls show). I want the tutorial to prompt for a step on #0main, then a step on #1show. I haven't been able to eliminate the "can't find type page data" error no matter what I've tried.

**Comment by mmoskal** [comment]
It indeed doesn’t appear to work…

**Comment by brian-swan** [comment]
Thanks! I've verified that this fixes the issue.
