### ISSUE TITLE
Boolean parameter in add grid animation() is ignored

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#144]
In the **sprite sheet->add grid animation(string, num, num, num, num, bool)** method, the Boolean parameter (last parameter) seems to be ignored. Documentation indicates that this is a "yo-yo" parameter, which I interpret as a switch for playing the animation forwards and backwards if set to **true**. Regardless of the value of this parameter, the animation is only played forward. Here's an example: http://tdev.ly/apjvqjaf.

**Comment by pelikhan** [comment]
You also need to specify how any times you want the animation to repeat.

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Apr 22, 2015 at 10:54 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


In the sprite sheet->add grid animation(string, num, num, num, num, bool) method, the Boolean parameter (last parameter) seems to be ignored. Documentation indicates that this is a "yo-yo" parameter, which I interpret as a switch for playing the animation forwards and backwards if set to true. Regardless of the value of this parameter, the animation is only played forward. Here's an example: http://tdev.ly/apjvqjaf.

-

**Comment by brian-swan** [comment]
I see. I expected that if I set **yo-yo := true** that 1 repetition of the animation would be "up and down". But, if I set the number of loops to 2, I see that **yo-yo** works.
