### ISSUE TITLE
Delay code execution while animation plays

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#145]
I would like to delay code execution until an animation finishes running. More specifically, I have the animation code in a *play animation* action, so my code looks like this:
 
[code before animation]
board->on every frame
   &nbsp;&nbsp;if (some condition)
       &nbsp;&nbsp;&nbsp;&nbsp;>play animation()
   &nbsp;&nbsp;end if
end on every frame
[code after animation]
 
Is there some way to make *[code after animation]* delay execution until after the animation in *play animation* finishes? I've tried using **anim->wait**, but that just freezes my script.
 
My specific scenario is this: I have a sprite moving on the board. When the sprite hits an obstacle, I want to play an animation. BUT, for this to look realistic, the sprite needs to stop moving while the animation plays, then continue moving after the animation finishes. Here's the example: http://tdev.ly/alvsukmu

**Comment by mmoskal** [comment]
Anim->wait will need to call app->allow_other_events

**Comment by pelikhan** [comment]
``anim->wait`` has been fixed.
