### ISSUE TITLE
Tutorial in "beginner" mode ignores {widget} macro

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#147]
When I follow this tutorial, http://aka.ms/startcoding, in "beginner mode", I'm taken through the tutorial in split-screen mode. The tutorial uses the {widget} macro to force full screen, so it appears that the macro is ignored. (This is not an issue in "coder" mode.)

**Comment by pelikhan** [comment]
There is currently no macro for control the screen splitting.

**Comment by brian-swan** [comment]
The {widget} macro controls split screen mode. Split screen mode is on by default, but I can disable it by omitting it from a list of specified "widgets". e.g. {widgets:undo} will make the undo button visible, but by omitting split, I've turned off split screen mode.

**Comment by pelikhan** [comment]
The macro controls the visibility of the “split” button – not the actually splitting. By default, all scripts open in split mode in beginner mode.

**Comment by brian-swan** [comment]
I need the behavior in "beginner" mode to be the same as in "coder" mode with respect to the {widgets} macro. In coder mode, if I use {widget:undo} the tutorial opens in full screen mode. That's what I need in beginner mode.

**Comment by pelikhan** [comment]
If you use {widget:unod}, you get the undo button. It does not impact the screen splitting.

**Comment by pelikhan** [comment]
Try using ``{flags:nosplit}``

**Comment by mmoskal** [comment]
In fact if you use any {widget:…} it tells the engine that you want to control widgets. Without that, it assumes you want everything. This is a somewhat confusing…

**Comment by brian-swan** [comment]
Talked with Peli about this in detail. It appears that I was leveraging a bug that will be fixed. I'll update tutorials to use {flags:nosplit}.
