### ISSUE TITLE
play again lightbox not disappearing

### ISSUE THREAD

**Issue by coatsy** [Microsoft/TouchDevelop#149]
Created an HTML5 app: http://tdev.ly/ejjke
 
When I play it and die, I get the usual screen.
![tderror](https://cloud.githubusercontent.com/assets/1772428/7348226/13816964-ed33-11e4-9fe0-6f8a1788d006.jpg)

But hitting play again does not dismiss the lightbox and the game starts behind the dialog.
 
Happens in IE(11) and Chrome (42.0.2311.90 m)
 
Also seems to happen in the TD editor.

**Comment by coatsy** [comment]
IE works
? Not fixed in Chrome?

**Comment by pelikhan** [comment]
Make sure that the engine has updated.

**Comment by coatsy** [comment]
Installed Chrome for the first time on a new machine and still got the error

**Comment by pelikhan** [comment]
Make sure you are running /app/latest

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Apr 27, 2015 at 4:42 PM -0700, "Andrew Coates" <notifications@github.com<mailto:notifications@github.com>> wrote:


Installed Chrome for the first time on a new machine and still got the error

-

**Comment by coatsy** [comment]
Creating a HTML5 app from the script results in the error on the generated app:

http://aka.ms/wscSample (http://tdev.ly/ejjke)

in both Chrome and IE
