### ISSUE TITLE
rendering of actions in the side pane

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#153]
The rendering for action parameters in the side pane depends on whether it fits on a single line or not. This is imho confusing and we should probably settle for one behavior or another.

**Comment by pelikhan** [comment]
Agreed.

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Apr 28, 2015 at 8:39 AM -0700, "Jonathan Protzenko" <notifications@github.com<mailto:notifications@github.com>> wrote:


The rendering for action parameters in the side pane depends on whether it fits on a single line or not. This is imho confusing and we should probably settle for one behavior or another.

-

**Comment by pelikhan** [comment]
We should remove them then.
