### ISSUE TITLE
Inconsistency in the usage of create

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#154]
If I define a custom type, then it's

```
foo := mytype -> create
```

but if it's a collection, then I have to use

```
foo := create -> collection of -> number
```

this is confusing

**Comment by mmoskal** [comment]
There is also `mytype->create collection`.

I think going forward we should add the creation method to ‘create’ singleton – `create->web request`, `create->json builder` etc. and also allow this for custom types.
