### ISSUE TITLE
failure to load collaboration information

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#157]
Scripts may be stuck loading in the collab initialization phase.

![image](https://cloud.githubusercontent.com/assets/4175913/7385579/9a2624e4-edfd-11e4-9ddc-8e31d1369236.png)

**Comment by sebastianburckhardt** [comment]
How does this happen? I can think of two cases
- script is removed from group script before it is opened in editor the first time
- adding of group script failed for some reason, then editor gets stuck

I guess it may be the second. I think the best behavior would be to treat this as a non-group script. I will update the code accordingly.

**Comment by pelikhan** [comment]
Great!

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Apr 29, 2015 at 8:39 AM -0700, "Sebastian Burckhardt" <notifications@github.com<mailto:notifications@github.com>> wrote:


How does this happen? I can think of two cases

  *   script is removed from group script before it is opened in editor the first time
  *   adding of group script failed for some reason, then editor gets stuck

I guess it may be the second. I think the best behavior would be to treat this as a non-group script. I will update the code accordingly.

-
