### ISSUE TITLE
"edit with group" button is gone

### ISSUE THREAD

**Issue by sebastianburckhardt** [Microsoft/TouchDevelop#158]
Looks like the UI got remodeled. 

Did you move this button to some other place? Or was it accidentally removed.

(I need the button back so I can test my fix for #157)

**Comment by pelikhan** [comment]
You can add a script to a group from the group page.

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Apr 29, 2015 at 10:06 AM -0700, "Sebastian Burckhardt" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #158<https://github.com/Microsoft/TouchDevelop/issues/158> to @pelikhan<https://github.com/pelikhan>.

-

**Comment by msprotz** [comment]
This one should probably go back in expert mode / non-lite TD. We argued a while back that it was useful for discovery of the group thing. I agree that it should probably be hidden in the lite cloud / non-expert mode.

**Comment by pelikhan** [comment]
The script list page has been cleaned up and there’s only a set of essential buttons. We can have a button to add the script to the group in the button bar next to the author name.

**Comment by pelikhan** [comment]
Please reopen if you strongly feel about having this button back on the script landing page.
