### ISSUE TITLE
Can't sign out anymore in the new lite cloud

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#162]

**Comment by pelikhan** [comment]
The sign out button is near the privacy and cookies / legal button.

**Comment by mmoskal** [comment]
I think it should be also on the user page. Usually to sign out you click on, or somewhere near, your name.

No one will ever find it on the “copyright”.

**Comment by msprotz** [comment]
It's usually next to the user's name.

**Comment by pelikhan** [comment]
There is no space for that button on the phone layout. It is at the bottom of the page on outlook.com.

**Comment by mmoskal** [comment]
In outlook and gmail if I click on my name I get a menu that has “sign out” option. In facebook I have to click a little triangle next to my name.

We had that when the button was on the user page.

**Comment by pelikhan** [comment]
fixed in f1c9b9ac1ae2feaca7f85d1492f9f09c1c9b983c
