### ISSUE TITLE
Tutorial promting for newline in string is broken

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#172]
When a tutorial prompts for a string that contains a new line, the prompt doesn't match the goal. Further, if I follow the goal step (which prompts me to enter \n), the entry is escaped, so that it isn't a new line character. Example is here: http://tdev.ly/gajhimtj

We have one tutorial that depends on students easily understanding that they need to enter a new line in a string, hence the P1 classification.

**Comment by tballmsft** [comment]
More discussion needed.

**Comment by brian-swan** [comment]
Prompting for \n and treating it like a new line character would be sufficient for us.

**Comment by mmoskal** [comment]
This is unlikely to happen. So far we have shied away from any interpretation of characters in string literals.

**Comment by brian-swan** [comment]
Is there anything I can do to address this? Here's the code I want students to write and the prompting that they see:
![code1](https://cloud.githubusercontent.com/assets/918682/7824498/25ab659a-03b8-11e5-899f-de0a0ce75204.png)

**Comment by pelikhan** [comment]
This is especially tricky because \n is meaningless for a beginner.

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/9090791/28d5bd62-3b51-11e5-96f2-639aaa29f9c0.png)

Fixed in https://github.com/Microsoft/TouchDevelop/commit/09a259efbeb08b0209883a7ecaeda874526d756e
