### ISSUE TITLE
"previous step" button in tutorials is missing

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#173]
The "go to previous step" button is missing from instruction steps in tutorials. The ability to navigate backwards in a tutorial is critical to student success in the curriculum we are building.

**Comment by pelikhan** [comment]
The button needs to be enabled with the previousStepButton widget.

Sent from my Windows Phone
________________________________

**Comment by brian-swan** [comment]
This is a change, correct? It is a change that has immediate and serious consequences for the work we have in progress now.

**Comment by pelikhan** [comment]
I can check but it has been in place for a month now (since the petco event).

Sent from my Windows Phone
________________________________

**Comment by pelikhan** [comment]
Actually the widget is precisely: "tutorialGoToPreviousStep"

**Comment by pelikhan** [comment]
This widgets is enabled in "coder" and up by default.
