### ISSUE TITLE
Feature request for web response of type code

### ISSUE THREAD

**Issue by divakarmanivel** [Microsoft/TouchDevelop#175]
I found this line inside the web.ts file in tds git file
if (!/response_type=token/i.test(url))
url += "&response_type=token";

It was inside the function ' export function oauth_v2_async(oauth_url: string, userid: string): Promise '

If you could just create another function with
if (!/response_type=code/i.test(url))
url += "&response_type=code";

**Comment by pelikhan** [comment]
I've changed the check slightly: you can include ``reponse_type=code`` in the ``oauth url`` url argument.

**Comment by divakarmanivel** [comment]
Hi peli. I found the same line inside this function as well which does not change the oauth auth url to accept type code. The function which has the this code is

export function oauth_v2_async(oauth_url: string, userid: string): Promise
            // : OAuthResponse
        {
            var redirectURI = "https://www.touchdevelop.com/" + userid + "/oauth";
            var state = Util.guidGen();
            var stateArg = "state=" + state.replace('-', '');


            var hostM = /^([^\/]+:\/\/[^\/]+)/.exec(document.URL)
            var host = hostM ? hostM[1] : ""
            if (host && !/\.touchdevelop\.com$/i.test(host)) {
                redirectURI = host + "/api/oauth"
                userid = "web-app"
            }


            var actualRedirectURI = redirectURI;
            // special subdomain scheme?
            var subdomainRx = /&tdredirectdomainid=([a-z0-9]{1,64})/i;
            var msubdomain = oauth_url.match(subdomainRx);
            if (msubdomain) {
                var appid = msubdomain[1];
                actualRedirectURI = 'https://' + appid + '-' + userid + '.users.touchdevelop.com/oauth';
                redirectURI = "https://www.touchdevelop.com/" + appid + '-' + userid + "/oauth";
                App.log('oauth appid redirect: ' + appid);
                oauth_url = oauth_url.replace(subdomainRx, '');
            }
            // state variable needed in redirect uri?
            var stateRx = /&tdstateinredirecturi=true/i;
            if (stateRx.test(oauth_url)) {
                actualRedirectURI += "?" + stateArg;
                Time.log('oauth adding state to url');
                oauth_url = oauth_url.replace(stateRx, '');
            }


            App.log('oauth login uri: ' + oauth_url);
            App.log('oauth redirect uri: ' + actualRedirectURI);
            // craft url login;
            var url = oauth_url
                + (/\?/.test(oauth_url) ? '&' : '?')
                + 'redirect_uri=' + encodeURIComponent(actualRedirectURI)
                + "&" + stateArg;
            if (!/response_type=(token|code)/i.test(url))
                url += "&response_type=token";


            App.log('oauth auth url: ' + url);
            return Web.oauth_v2_dance_async(url, actualRedirectURI, userid, stateArg);
        }

Please change or remove this line as well.

if (!/response_type=(token|code)/i.test(url))
                url += "&response_type=token";
