### ISSUE TITLE
turtle->set heading doesn't follow conventions (or documentation)

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#178]
**turtle->set heading** seems to follow a counterclockwise rotation. 90 degrees is west, 270 is east. According to convention (and the TD documentation), those should be reversed: https://www.touchdevelop.com/app/latest#list:topics:topic:turtlesetheading:overview

**Comment by pelikhan** [comment]
Fixed. Update your script to try it out.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, May 11, 2015 at 12:18 PM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


turtle->set heading seems to follow a counterclockwise rotation. 90 degrees is west, 270 is east. According to convention (and the TD documentation), those should be reversed: https://www.touchdevelop.com/app/latest#list:topics:topic:turtlesetheading:overview

-

**Comment by brian-swan** [comment]
Thanks. That fixes it. Thanks.
