### ISSUE TITLE
Exported Windows Phone Apps Crash

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#180]
Widows phone apps do not run when exported with Cordova. They crash out at the same point, whatever app is exported.

**Comment by ianapps** [comment]
Error is: Unhandled exception at line 27, column 9 in ms-appx://com.app.mdzeghqk/www/plugins/com.msopentech.websql/www/windows/SqlTransaction.js

0x800a139e - JavaScript runtime error: Connection is not set

**Comment by mmoskal** [comment]
I don’t know any details here, but we certainly do not expect WebSQL, especially a shimmed version, on Windows Phone.

**Comment by ianapps** [comment]
This issue started just after the phone Back Button not working was fixed. The TD/Cordova package deploys and crashes out as it opens.  Opening in VB gives the error above.

**Comment by ianapps** [comment]
It has 2 hearts in the issues forum on TD, so others appear to be having the same issue.

**Comment by ianapps** [comment]
Is this recognised as an issue and is it being looked at?

**Comment by ianapps** [comment]
I this link looks like the same issue: https://github.com/MSOpenTech/cordova-plugin-websql/issues/25

Hope this helps

**Comment by ianapps** [comment]
I think the above link implies that the plugin name has changed, so the Cordova deployment script needs updating to reflect this.

**Comment by ianapps** [comment]
Tested the app following the remove/install plugin guidance and now the exported app can run without crashing.  The recommendations in the link need to be followed to fix this issue.

**Comment by ianapps** [comment]
Also, now that I can get an app running, I also noticed the windows phone back button isn't working which was meant to be fixed; https://github.com/Microsoft/TouchDevelop/issues/48.
