### ISSUE TITLE
"for print/email" should be an option in script properties in 'coder' mode

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#183]
The ability to print or email code is important for all skill levels. The **for print/email** option should be available in the script properties for (at least) "coder" mode.

**Comment by msprotz** [comment]
One thing we mentioned during the meetings (nice to have) is that if the CSS was done properly with a "print" stylesheet, then the users could "just print" instead of having to hit an extra button.

**Comment by brian-swan** [comment]
For our course, we really need to be able to print code that is in "coder" mode. Since the "print/email" button was removed from coder mode, we can no longer do this.

**Comment by pelikhan** [comment]
Alright, I’ll bring that back.

**Comment by brian-swan** [comment]
This is fixed...thanks!

**Comment by pelikhan** [comment]
This is printer button in the script list. [cid:image001.png@01D092DB.74D40710]
