### ISSUE TITLE
tables missing completely from the script view

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#184]
In this script:
http://tdev.ly/qcvf

there is a table, but I cannot select it on the left hand side menu. I can say "go to".

Did we kill tables?

**Comment by pelikhan** [comment]
The intellicollector should detect that tables are needed and add the required widgets. Bug probably added with skill refactoring for restricted.

Sent from Outlook<http://taps.io/outlookmobile>




On Sat, May 16, 2015 at 1:45 AM -0700, "Michał Moskal" <notifications@github.com<mailto:notifications@github.com>> wrote:


In this script:
http://tdev.ly/qcvf

there is a table, but I cannot select it on the left hand side menu. I can say "go to".

Did we kill tables?

-

**Comment by mmoskal** [comment]
No, it was completely missing. I’ve added it back in coder and expert, fixed in 0c19af7827df8c0f

**Comment by millerv** [comment]
Verified as fixed - hidden in Beginner skill level, visible in Coder and Expert skill levels.
