### ISSUE TITLE
certificate dialog improvements 

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#186]
How to create azure subscription?
- unclear where to start
- need to sign up for Microsoft account --- someone on iPhone couldn't manage
- two factor authentication!!!
- credit card needed for azure --- one gave up there, after spending minutes to create a MICROSOFT account. 
- will never work on iPhone anyway: certificate, file
- "something went wrong" after initial deployment in TouchDevelop (takes a minute?)
- confusing video --- diverges from what we want

**Comment by pelikhan** [comment]
* updated link instead of video
