### ISSUE TITLE
Tutorial prompting disappears if you click help

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#189]
When following a tutorial, if you click the API **help** link, then return to the tutorial, prompting disappears. (It seems that you are no longer in "tutorial mode"...you just have an unfinished script.)

Is the right solution here to disable/remove the **help** link in tutorials?

**Comment by tballmsft** [comment]
Do not allow jumping into docs from tutorial

**Comment by pelikhan** [comment]
They should be disabled. Do you have a screenshot of those?

**Comment by brian-swan** [comment]
The image below shows the help link I'm talking about (in the context of a tutorial). If you click that link, you are taken to documentation, but when you return to the tutorial (by clicking the "script" arrow (<-)), the tutorial is broken (no prompting).
![brokenhelp](https://cloud.githubusercontent.com/assets/918682/9064677/7a67bc68-3a82-11e5-9b44-7378b514d44d.png)

**Comment by pelikhan** [comment]
Fixed.
