### ISSUE TITLE
Issue with ( while using the keyboard

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#192]
![capture](https://cloud.githubusercontent.com/assets/10673049/7758859/bdb28076-ffc1-11e4-9550-4abb29edc92f.PNG)
In the situation above, I cannot open a parenthesis with the keyboard. The behavior is kind of erratic, it seems, unless I use the mouse.

**Comment by millerv** [comment]
Was this the French keyboard issue you mentioned in a previous meeting?
