### ISSUE TITLE
Order of tutorial prompting is confusing

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#2]
When following a tutorial, the order in which a user is prompted to write code is sometimes very confusing. 
* e.g. 1: http://tdev.ly/kavqqqgj 
* e.g. 2: When inserting Random Range (step 5 here http://tdev.ly/oeqeagwu, like for robot set x or y), it’s clunky – it leaves the “0” from the original function there and you have to delete it. 
* e.g. the order for storing a value in a variable should be 1) create variable, 2) write the expression for initialization (not the other way around using "store in var")

**Comment by mmoskal** [comment]
The first issue should be resolved.

Could you check on the second one now? It's maybe not exactly the way I would do it, but it is the minimal number of edits to do it.

Please open a new issue for the third thing. It's about the general editor design. We need to discuss how to best do it.

**Comment by brian-swan** [comment]
Yes, the second issue is much improved. Thanks!
I've opened a new issue for the 3rd thing.
