### ISSUE TITLE
Sign-in logos need to match actual logos

### ISSUE THREAD

**Issue by MichaelEBraun** [Microsoft/TouchDevelop#206]
The TouchDevelop Hub (sign in) issue: 

People do not automatically identify Microsoft with Hotmail / Live / Outlook / Office 365. Similar to Google - people don't associate Google with Gmail school gmail.  The image should represent Google more closely with how the login appears on the gmail. Similarly,  the login appears on Microsoft similar to the login appears when on Microsoft website to login to email. Users are getting stuck with these random images of Microsoft / Google (images are not representing the way login appears for the user while on those email services.

**Comment by millerv** [comment]
This may be resolved with the new backend.

**Comment by millerv** [comment]
All icons associated with each of the authentication services use silhouettes of the latest images, closing bug as Fixed.
