### ISSUE TITLE
clicking on errors icon in expert mode leaves second column blank (unexpected)

### ISSUE THREAD

**Issue by thomasjball** [Microsoft/TouchDevelop#21]
![erroricon](https://cloud.githubusercontent.com/assets/7671657/6152548/df4a9c10-b1d2-11e4-87fb-ae8a19a3b20d.png)

**Comment by pelikhan** [comment]
This is our vanishing script list bug. Tom, is the repro deterministic? I can't repro on mine.

**Comment by mmoskal** [comment]
This is "coder" level and not "expert". It's totally reproducible.

**Comment by thomasjball** [comment]
Yes, Michal is correct on both counts.

**Comment by pelikhan** [comment]
fixed 060d281a57786bb0c83c33977b2ace4630f583ec
