### ISSUE TITLE
Tutorial takes empty string as a correct input and doesn't continue with the next step

### ISSUE THREAD

**Issue by sgi-natalietai** [Microsoft/TouchDevelop#219]
Part of the tutorial that I am creating asks the student to check if a string variable is equal to a certain string.

eg. thisstring -> equals("hi")

There are a series of these, and half the time it does what would be expected of the tutorial (prompts the student to tap the "equals" box and then "edit" to go into the string with a message that lets them know what exactly they should be typing in.)

The other half of the time, immediately after pressing "equals" the editor will come up with a line that says "This line is perfect!" while the string is still empty with no more prompts as to what to do next.

**Comment by pelikhan** [comment]
Could you publish and post your tutorial id?

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, Jun 5, 2015 at 6:21 PM -0700, "sgi-natalietai" <notifications@github.com<mailto:notifications@github.com>> wrote:


Part of the tutorial that I am creating asks the student to check if a string variable is equal to a certain string.

eg. thisstring -> equals("hi")

There are a series of these, and half the time it does what would be expected of the tutorial (prompts the student to tap the "equals" box and then "edit" to go into the string with a message that lets them know what exactly they should be typing in.)

The other half of the time, immediately after pressing "equals" the editor will come up with a line that says "This line is perfect!" while the string is still empty with no more prompts as to what to do next.

-

**Comment by sgi-natalietai** [comment]
http://tdev.ly/ccfxaick

Thanks.
