### ISSUE TITLE
Tutorial prompting for forms->button skips editing button text

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#220]
When **forms->button("text")** is used in a tutorial, the tutorial does not prompt the user to alter the button text as specified in the tutorial. This impacts what we can do with tutorials in our course. Example here: https://www.touchdevelop.com/qkfom.

**Comment by pelikhan** [comment]
This is due because the forms library has a default "ok" filling for the button text. The tutorial engine then thinks the user has entered a non-empty string and continues.
I have removed that default filling so it should work again. Please update the forms library and try again.

**Comment by brian-swan** [comment]
Using the updated library fixes the issue. Thanks!
