### ISSUE TITLE
touchdevelop is disabling copy/paste

### ISSUE THREAD

**Issue by msprotz** [Microsoft/TouchDevelop#222]
I can't copy/paste contents of a comment in the editor.

**Comment by mmoskal** [comment]
In latest? I thought I fixed this in https://github.com/Microsoft/TouchDevelop/commit/ebbaffead1377e9e92291b16c7aaaa8408f53503

**Comment by msprotz** [comment]
Ctrl-C/V doesn't work for me in the editor.

**Comment by mmoskal** [comment]
And right-click works?

**Comment by msprotz** [comment]
My bad, that browser window wasn't refreshed, the other one was.
