### ISSUE TITLE
"store in var" not an option for page parameter

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#223]
If a page has an input parameter, it is sometimes necessary to store it's value in a temp variable in the **display** section so that it's value can be manipulated. However, "store in var" is not an option for a page parameter (see picture...also not available in the "more" options). This, but itself isn't a huge problem - I can just write var temp score := p without using "store in var". However, it *does* affect tutorials. Prompting in this situation breaks down. Here's an example: http://tdev.ly/obffqwgd 

![capture](https://cloud.githubusercontent.com/assets/918682/8141421/6335f5fe-111b-11e5-9388-06cf5fe95150.PNG)

**Comment by pelikhan** [comment]
This is true for all function parameters, page or function.

**Comment by pelikhan** [comment]
When the right hand side is a local, "store in var" is available but lower priority (typically second/third screen of intellibuttons). When do you need to have such temp variables?
