### ISSUE TITLE
Older art assets cached w/o CORS headers cause script crash/lockup

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#227]
Encountered issue when using older Day of the Dead art assets from the TouchDevelop Samples account - the assets in question are approximately 8 months old of this writing.

Steps to repro:
1. Published as hidden this script:  https://www.touchdevelop.com/ayatidsc - uses Day of the Dead assets.
2. When someone not signed in attempted to try the link, it would show the error message: "Something went wrong; please reload the web page."
3. Reloaded the page, still stuck with error message.
4. In Internet Explorer, pressed F12 to bring up console.
5. Console log spew (in Notes below) shows Access Denied errors.

Result:
After discussion over email with Peli, older assets on TouchDevelop are missing CORS headers, and can lock up scripts.

Expected:
Create new CDN for all older art assets so they have proper CORS headers.

Notes (F12 Console spew):
HTML1300: Navigation occurred.
File: app
Creating AppCache with manifest: 'https://www.touchdevelop.com/app/current.manifest'.
TD-LOG: 0000.057: baseUrl0: https://az31353.vo.msecnd.net/app/2519684305802180000-f9e59f3a.3ace.4800.09f2.fce1a8c331d4-80977/c/
TD-LOG: 0000.059: userAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; rv:11.0) like Gecko
TD-LOG: 0000.060: browser: ie11.tablet/0/0
TD-LOG: 0000.063: Error: SecurityError
URL:  (script: 57d5b94f-e4d5-4514-beb7-a0959bd4fb0a, context: promiseDone)
JS-URL: https://az31353.vo.msecnd.net/app/2519684305802180000-f9e59f3a.3ace.4800.09f2.fce1a8c331d4-80977/c/main.js
Platform: ie11.tablet, ie11, tablet, touch, assumeMouse, win, win8plus
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; rv:11.0) like Gecko (resolution: 1536x362)
Date: Tue Jun 16 2015 18:39:54 GMT-0700 (Pacific Daylight Time)

RecentEvents:

StackTrace:

TD-LOG: 0000.069: baseUrl: https://az31353.vo.msecnd.net/app/2519684305802180000-f9e59f3a.3ace.4800.09f2.fce1a8c331d4-80977/c/
TD-LOG: 0000.069: setting up flags and knobs
TD-LOG: 0000.073: TICK: mainInit
TD-LOG: 0000.075: initialize apis
TD-LOG: 0000.127: initialize editor
TD-LOG: 0000.144: theme: undefined
TD-LOG: 0000.145: initialize api cache
TD-LOG: 0000.145: DBG: dbgEvent|ApiCacheMgr.initAsync: got table promise
TD-LOG: 0000.146: DBG: dbgEvent|app cache event: checking, status=2
TD-LOG: 0000.185: DBG: dbgEvent|ApiCacheMgr.initAsync: got table
TD-LOG: 0000.219: DBG: dbgEvent|ApiCacheMgr.initAsync: got data
TD-LOG: 0000.239: DBG: dbgEvent|app cache event: noupdate, status=1
TD-LOG: 0000.264: saving cache mgr, 2 bytes
TD-LOG: 0000.348: DBG: dbgEvent|Editor.refreshDecl
TD-LOG: 0000.411: DBG: dbgEvent|resize(prev w=0 h=0, curr w=1536 h=362)
TD-LOG: 0000.411: phone mode: off
TD-LOG: 0000.412: resize 1536x362
TD-LOG: 0000.422: dispatch: #run:57d5b94f-e4d5-4514-beb7-a0959bd4fb0a:id=ayatidsc
TD-LOG: 0000.423: pushState: #run:57d5b94f-e4d5-4514-beb7-a0959bd4fb0a:id=ayatidsc
TD-LOG: 0000.428: DBG: dbgEvent|Editor.loadHashCore.fullLoad
TD-LOG: 0000.455: DBG: dbgEvent|Editor.prepareForLoad reloading script
TD-LOG: 0000.469: DBG: dbgEvent|resize(prev w=1536 h=362, curr w=1536 h=362)
TD-LOG: 0000.469: phone mode: off
TD-LOG: 0000.470: resize 1536x362
TD-LOG: 0000.482: DBG: dbgEvent|Editor.prepareForLoad.end
TD-LOG: 0000.483: DBG: dbgEvent|ProgressOverlay.show 1 reloading script
TD-LOG: 0000.497: DBG: dbgEvent|Editor.loadScriptAsync
TD-LOG: 0000.498: loadScriptAsync: 57d5b94f-e4d5-4514-beb7-a0959bd4fb0a
TD-LOG: 0000.504: DBG: dbgEvent|Editor.saveStateAsync
TD-LOG: 0000.505: DBG: dbgEvent|Editor.loadScriptAsync.getHeader
TD-LOG: 0000.517: DBG: dbgEvent|Editor.loadScriptAsync.setHeader
TD-LOG: 0000.517: World: setting 57d5b94f-e4d5-4514-beb7-a0959bd4fb0a
TD-LOG: 0000.520: World: 57d5b94f-e4d5-4514-beb7-a0959bd4fb0a/ayatidsc: Piñata Breaker save with base 
TD-LOG: 0000.530: DBG: dbgEvent|Editor.loadScriptTextAsync.start
TD-LOG: 0000.603: DBG: dbgEvent|Editor.loadScriptTextAsync.coreLoaded
TD-LOG: 0000.917: DBG: dbgEvent|Editor.loadScriptTextAsync.done
TD-LOG: 0000.923: >>> Stop Collab! Piñata Breaker
TD-LOG: 0000.924: loadScriptAsync: saving state again
TD-LOG: 0000.924: DBG: dbgEvent|Editor.saveStateAsync
TD-LOG: 0000.924: DBG: dbgEvent|UndoMgr.pushMain
TD-LOG: 0000.933: DBG: dbgEvent|UndoMgr.createSavedApp Piñata Breaker:upd main:upd game:upd boing:upd explosion:upd dotd background:upd dotd candy:upd candy pop effect:upd day of the dead candy:upd day of the dead pinata:upd ending:upd crunchy eating:upd cheer:upd tempspritenum:upd pinataminigame:upd stick:upd tapcount:upd minigameend:upd hitsound:upd candyset:upd end:upd app:upd 
TD-LOG: 0000.934: DBG: dbgEvent|Editor.loadScriptAsync.done
TD-LOG: 0000.934: DBG: dbgEvent|ProgressOverlay.hide 0
TD-LOG: 0000.935: DBG: dbgEvent|ProgressOverlay.show 1 compiling script
TD-LOG: 0000.944: DBG: dbgEvent|Editor.saveStateAsync
TD-LOG: 0000.945: DBG: dbgEvent|UndoMgr.pushMain
TD-LOG: 0000.945: DBG: dbgEvent|UndoMgr.createSavedApp app:hit 
TD-LOG: 0001.153: Ok elimination: 185 check(s) eliminated (estimated)
TD-LOG: 0001.154: DBG: dbgEvent|showWall
TD-LOG: 0001.180: DBG: dbgEvent|resize(prev w=1536 h=362, curr w=1536 h=362)
TD-LOG: 0001.181: sethash: run:57d5b94f-e4d5-4514-beb7-a0959bd4fb0a:id=ayatidsc - Piñata Breaker :: run
TD-LOG: 0001.181: DBG: dbgEvent|History.setHash|run:57d5b94f-e4d5-4514-beb7-a0959bd4fb0a:id=ayatidsc
TD-LOG: 0001.181: DBG: dbgEvent|History.setHash is a replace
TD-LOG: 0001.181: pushState: #run:57d5b94f-e4d5-4514-beb7-a0959bd4fb0a:id=ayatidsc
TD-LOG: 0001.184: TICK: coreRun|ayatidsc
TD-LOG: 0001.186: fixed art sound: https://az31353.vo.msecnd.net/aac/evcyntoj.m4a
TD-LOG: 0001.187: fixed art sound: https://az31353.vo.msecnd.net/aac/nbcosagg.m4a
TD-LOG: 0001.189: fixed art sound: https://az31353.vo.msecnd.net/aac/wxwukllh.m4a
TD-LOG: 0001.190: fixed art sound: https://az31353.vo.msecnd.net/aac/rkydkdab.m4a
TD-LOG: 0001.191: fixed art sound: https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a
TD-LOG: 0001.193: ArtCache: art cache: hit https://az31353.vo.msecnd.net/aac/evcyntoj.m4a
TD-LOG: 0001.194: audio: src datauri mp4
TD-LOG: 0001.196: start loading sound
TD-LOG: 0001.197: ArtCache: art cache: hit https://az31353.vo.msecnd.net/aac/nbcosagg.m4a
TD-LOG: 0001.198: audio: src datauri mp4
TD-LOG: 0001.200: start loading sound
TD-LOG: 0001.200: ArtCache: art cache: miss https://az31353.vo.msecnd.net/pub/daaxcxnp
TD-LOG: 0001.202: log: GET https://az31353.vo.msecnd.net/pub/daaxcxnp
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/pub/daaxcxnp required Cross Origin Resource Sharing (CORS).
File: app
TD-LOG: 0001.208: ArtCache: art cache: miss https://az31353.vo.msecnd.net/pub/bbohiuxv
TD-LOG: 0001.209: log: GET https://az31353.vo.msecnd.net/pub/bbohiuxv
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/pub/bbohiuxv required Cross Origin Resource Sharing (CORS).
File: app
TD-LOG: 0001.211: ArtCache: art cache: miss https://az31353.vo.msecnd.net/pub/cxgsircf
TD-LOG: 0001.212: log: GET https://az31353.vo.msecnd.net/pub/cxgsircf
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/pub/cxgsircf required Cross Origin Resource Sharing (CORS).
File: app
TD-LOG: 0001.214: ArtCache: art cache: hit https://az31353.vo.msecnd.net/pub/vigqhiui
TD-LOG: 0001.214: picture: fromArtUrl delayed
TD-LOG: 0001.218: ArtCache: art cache: miss https://az31353.vo.msecnd.net/pub/vmqsajwk
TD-LOG: 0001.219: log: GET https://az31353.vo.msecnd.net/pub/vmqsajwk
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/pub/vmqsajwk required Cross Origin Resource Sharing (CORS).
File: app
TD-LOG: 0001.222: ArtCache: art cache: hit https://az31353.vo.msecnd.net/aac/wxwukllh.m4a
TD-LOG: 0001.223: audio: src datauri mp4
TD-LOG: 0001.225: start loading sound
TD-LOG: 0001.227: ArtCache: art cache: hit https://az31353.vo.msecnd.net/aac/rkydkdab.m4a
TD-LOG: 0001.227: audio: src datauri mp4
TD-LOG: 0001.229: start loading sound
TD-LOG: 0001.230: loaded sound oncanplay
TD-LOG: 0001.234: ArtCache: art cache: miss https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a
TD-LOG: 0001.236: log: GET https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a required Cross Origin Resource Sharing (CORS).
File: app
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.244: loaded sound oncanplay
TD-LOG: 0001.245: art cache: request failed https://az31353.vo.msecnd.net/pub/daaxcxnp
TD-LOG: 0001.246: picture: fromArtUrl delayed
TD-LOG: 0001.246: log: error with GET https://az31353.vo.msecnd.net/pub/daaxcxnp
TD-LOG: 0001.254: loaded sound oncanplay
TD-LOG: 0001.260: loaded sound oncanplay
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.356: art cache: request failed https://az31353.vo.msecnd.net/pub/cxgsircf
TD-LOG: 0001.357: picture: fromArtUrl delayed
TD-LOG: 0001.357: log: error with GET https://az31353.vo.msecnd.net/pub/cxgsircf
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.369: art cache: request failed https://az31353.vo.msecnd.net/pub/vmqsajwk
TD-LOG: 0001.370: picture: fromArtUrl delayed
TD-LOG: 0001.370: log: error with GET https://az31353.vo.msecnd.net/pub/vmqsajwk
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.380: art cache: request failed https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a
TD-LOG: 0001.381: start loading sound
TD-LOG: 0001.381: log: error with GET https://az31353.vo.msecnd.net/aac/vlmcjiuk.m4a
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.399: art cache: request failed https://az31353.vo.msecnd.net/pub/bbohiuxv
TD-LOG: 0001.400: picture: fromArtUrl delayed
TD-LOG: 0001.400: log: error with GET https://az31353.vo.msecnd.net/pub/bbohiuxv
TD-LOG: 0001.497: loaded sound oncanplay
TD-LOG: 0001.498: DBG: dbgEvent|ProgressOverlay.hide 0
TD-LOG: 0001.499: runtime state: 0 -> 1, Runtime.run
TD-LOG: 0001.500: editor: notifyRunState
TD-LOG: 0001.515: ArtCache: art cache: miss https://az31353.vo.msecnd.net/pub/daaxcxnp
TD-LOG: 0001.515: log: GET https://az31353.vo.msecnd.net/pub/daaxcxnp
SEC7118: XMLHttpRequest for https://az31353.vo.msecnd.net/pub/daaxcxnp required Cross Origin Resource Sharing (CORS).
File: app
SEC7120: Origin https://www.touchdevelop.com not found in Access-Control-Allow-Origin header.
File: app
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

File: app
TD-LOG: 0001.541: art cache: request failed https://az31353.vo.msecnd.net/pub/daaxcxnp
TD-LOG: 0001.541: picture load: 0
TD-LOG: 0001.542: picture: loading
TD-LOG: 0001.543: log: error with GET https://az31353.vo.msecnd.net/pub/daaxcxnp
Resource doesn’t exist in the cache: 'https://az31353.vo.msecnd.net/pub/daaxcxnp'.
TD-LOG: 0001.662: picture: loaded 1116x540
TD-LOG: 0001.675: DBG: dbgEvent|CRASH REPORT SecurityError
TD-LOG: 0001.676: Error: SecurityError
URL:  (script: 57d5b94f-e4d5-4514-beb7-a0959bd4fb0a, context: promiseDone)
JS-URL: https://az31353.vo.msecnd.net/app/2519684305802180000-f9e59f3a.3ace.4800.09f2.fce1a8c331d4-80977/c/main.js
Platform: ie11.tablet, ie11, tablet, touch, assumeMouse, win, win8plus
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; rv:11.0) like Gecko (resolution: 1536x362)
Date: Tue Jun 16 2015 18:39:57 GMT-0700 (Pacific Daylight Time)

RecentEvents:

StackTrace:

TD-LOG: 0011.046: DBG: dbgEvent|save-ssa-1
TD-LOG: 0011.046: DBG: dbgEvent|Editor.saveStateAsync
TD-LOG: 0011.047: DBG: dbgEvent|UndoMgr.pushMain
TD-LOG: 0011.047: DBG: dbgEvent|UndoMgr.createSavedApp app:hit 
TD-LOG: 0011.048: save skipped: not auth or offline

**Comment by pelikhan** [comment]
This should be fixed by new backend.

**Comment by millerv** [comment]
Haven't seen this yet, so closing bug.
