### ISSUE TITLE
Touch develop no run

### ISSUE THREAD

**Issue by samuelsavio** [Microsoft/TouchDevelop#23]
touchdevelop local does not start and returns error

````
cd TouchDevelop
Mac-mini-di-samuel:TouchDevelop samuelsavio$ jake local
[P] modifying in-place all css files
[I] build completed.
rm -rf build/local/tdserver.js
starting shell watch...
starting with --cli TD_ALLOW_EDITOR=true TD_LOCAL_EDITOR_PATH=../.. --usehome
set TD_ALLOW_EDITOR=true
set TD_LOCAL_EDITOR_PATH=../..
data directory: /Users/samuelsavio/TouchDevelop
start, autoupdate=false
Deployment key: a843009fc0732e4dd949e8798756d3412020f940
Editor URL: http://localhost:4242/editor/local#td_deployment_key=a843009fc0732e4dd949e8798756d3412020f940
touchdevelop local started...
serving index.html from ../..
serving main.js from ../..
serving default.css from ../..
serving editor.css from ../..
serving browser.js from ../..
serving index.html from ../..
serving default.css from ../..
serving browser.js from ../..
serving main.js from ../..
serving editor.css from ../..
GET /-tdevmgmt-/d432fa3fab495dff663d6feacad8ecb459ec54c8/stats
HTTP error 403: wrong key
serving index.html from ../..
serving default.css from ../..
serving editor.css from ../..
serving browser.js from ../..
serving main.js from ../..
GET /-tdevmgmt-/d432fa3fab495dff663d6feacad8ecb459ec54c8/stats
HTTP error 403: wrong key
````

**Comment by pelikhan** [comment]
Please try pasting the "Editor URL" in your browser:

    Editor URL: http://localhost:4242/editor/local#td_deployment_key=a843009fc0732e4dd949e8798756d3412020f940

We need to handle the wrong key issue in a better way.

**Comment by samuelsavio** [comment]
Something wrong reload the page

**Comment by samuelsavio** [comment]
also the old method no longer works
 npm install -g http://aka.ms/touchdevelop.tgz
touchdevelop 
returns this error 


/usr/local/bin/touchdevelop: line 1: syntax error near unexpected token `('
/usr/local/bin/touchdevelop: line 1: `var __extends = this.__extends || function (d, b) {'

**Comment by pelikhan** [comment]
Jonathan, looks like our packaged shell has a regression. Can you look into it?

**Comment by mmoskal** [comment]
You should be able to run locally now 275541e24472f61317010bf76dc182625d14358e.

The packaged shell issue remains.

**Comment by msprotz** [comment]
Hmm... it looks like it tries to execute the bin/touchdevelop.js file directly, without calling "node bin/touchdevelop.js" or whatever it's supposed to be. I assume that we're missing the `#!/usr/bin/env node` line at the beginning of our packaged js file?

**Comment by msprotz** [comment]
Ok this is actually a regression because now that we have proper "clean" utf8 files in the tree without the BOM, the delightful regexp at shell/package.js:28 no longer works.

**Comment by pelikhan** [comment]
Michal had it setup so that you would not need to write "node".

Sent from my Windows Phone
________________________________

**Comment by msprotz** [comment]
I've pushed another commit that removes references to byte-order marks in our files. None of our files have it (I checked) and with this commit, none of the files we generate have it either. (`vs.sln` has it, and also a build-generated file called `beta.json`, but i don't think that's relevant.)

**Comment by pelikhan** [comment]
Sounds good. vs.sln is a Visual Studio file and should be left as is.

Sent from my Windows Phone
________________________________

**Comment by pelikhan** [comment]
Please try again.

Sent from my Windows Phone
________________________________
