### ISSUE TITLE
previous step recreates main when going back to first step

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#232]
If you use the "go to previous step" option to go back to the first step, you are required to re-create main, which was not part of the original first step: http://tdev.ly/salyybnt

**Comment by pelikhan** [comment]
This is tricky to solve. The easiest fix for us is to disable the "go to previous step" if it tries to go back to main.

**Comment by pelikhan** [comment]
> The easiest fix for us is to disable the "go to previous step" if it tries to go back to main.
Is this fix ok?

**Comment by brian-swan** [comment]
By "if it goes back to main", do you mean if it tries to recreate main?

**Comment by pelikhan** [comment]
Unikely we fix this one.

**Comment by millerv** [comment]
Seems benign at this point, and may cause more issues to 'fix' at this point.  Closing bug.
