### ISSUE TITLE
Tutorials: New data behavior and {widgets:promoteRefactoring} not working correctly in Beginner skill level

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#233]
The tutorial in question that I've been working on is a hidden publish:  http://tdev.ly/kiduewcj

Steps to reproduce:
1. Go to the link: http://tdev.ly/kiduewcj
2. Set the skill level to Beginner mode.
3. Complete the tutorial steps up near the end, where the user is prompted to enter the readyforminigame global variable/data.
4. Attempt to the complete any step that asks the learner to add a data/global variable.

Result: 
The blue prompt box will keep asking the learner to look at the next panel, then go back again, when the global variable is clearly visible in the panel.  

Expected:
The blue prompt box in tutorials needs to point to the global variable/data shown in the panel while in Beginner mode, and {widgets:promoteRefactoring} doesn't seem to help with this (not certain if it needs to, but adding it made no difference).

Notes:
Here is a screenshot, and I also have video if you need it.
![td_tutorial_data](https://cloud.githubusercontent.com/assets/2482509/8344720/1f02782a-1a9a-11e5-9b86-146c35763d1c.PNG)

**Comment by millerv** [comment]
Note: This has affected a tutorial already released on the MS Imagine site:  http://aka.ms/doodleguesser

**Comment by pelikhan** [comment]
This is a correct assesment. We've never had a tutorial with enough variables / global vars to push out data.
