### ISSUE TITLE
starting shell watch...

### ISSUE THREAD

**Issue by grumpycoder100** [Microsoft/TouchDevelop#235]
has this been fixed? I'm using node.js  v0.12.5

**Comment by grumpyspaceman** [comment]
I think this might help somehow, but when I try to open tdserver, which is a JavaScript file, Windows Script Host shows me a Microsoft JScript compilation error, saying that there is an invalid character at line 1 and char 1 of the JavaScript file. Please look up to this as I really want to export my apps to cordova..

also, this line of code was the one which resulted in the Microsoft JScript compilation error
#!/usr/bin/env node

**Comment by KevinNorth** [comment]
I've also run into this problem on a Windows machine.
