### ISSUE TITLE
Publish date for script is very wrong

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#236]
I've seen this issue more than once, but I have not been able to determine a pattern. In this example, the publish date for a script I published 3 days ago is "2015 years ago":
![capture](https://cloud.githubusercontent.com/assets/918682/8434421/14f42c92-1f00-11e5-98e5-18a20c6fe8ab.JPG)

**Comment by millerv** [comment]
Haven't seen this issue for a while, closing bug as fixed.
