### ISSUE TITLE
"Open TouchDevelop" link is broken

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#237]
When you go to a tutorial landing page (e.g. https://www.touchdevelop.com/wjglc), the "Open TouchDevelop" link on the page is broken.

![hyperlinkcan tbeopened](https://cloud.githubusercontent.com/assets/918682/8549560/4a7bba08-2480-11e5-9cd1-2b31f6b83d46.JPG)

**Comment by pelikhan** [comment]
Fixed
