### ISSUE TITLE
"preview" doesn't show stats for tutorial steps

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#238]
I used to be able to look at a script and click the “preview” button to get stats about usage (# of users who started a tutorial step). This doesn’t seem to work any more.

**Comment by millerv** [comment]
We're hitting this issue as well on the Microsoft Imagine team - we need the ability to track participation and overall tutorial usage.

**Comment by pelikhan** [comment]
Given the script id (e.g. abc), query https://www.touchdevelop.com/api/abc/progressstats

**Comment by millerv** [comment]
Closing issue since we can leverage the progressstats link now.
