### ISSUE TITLE
Tutorial prompting fails on "or" condition

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#24]
In this tutorial, http://tdev.ly/wtgwemnw, the last step adds to the condition of an existing if/then condition (adds an "or"...). The tutorial engine simply fails to correctly prompt the user.

**Comment by mmoskal** [comment]
If you notice some strange order of inserting numbers let me know.

**Comment by brian-swan** [comment]
I noticed some strange behaviors with numbers... opened #31.
