### ISSUE TITLE
Building from source on a cleanly cloned respository fails

### ISSUE THREAD

**Issue by jtuchsen** [Microsoft/TouchDevelop#240]
Running "jake" fails after following the installation instructions in the README. It looks like this happens because Touch Script was recently bumped up to a beta of version 1.5, and the package.json is configured to use the newest minor version, but some of the interfaces have changed between the versions. Forcing Touch Script back to 1.4 in the package.json fixed the issue for me.

**Comment by msprotz** [comment]
Hmm. Can you create a pull request to fix that?

We may also want to switch to TypeScript 1.5 beta since it would allow us to have working source maps.

**Comment by jtuchsen** [comment]
Sure, I just created a pull request to bump the version number down.

**Comment by jtuchsen** [comment]
I just realized I've been saying *Touch*Script instead of *Type*Script! I resubmitted my pull request after fixing the language. If I find some free time over the weekend I'll look into how hard it's going to be to update TouchDevelop to 1.5, it'll give me an opportunity to compare differences between ES6 and TypeScript, and read more of TouchDevelops source.

**Comment by pelikhan** [comment]
Thanks for the PR! It got pulled in.
