### ISSUE TITLE
Feature request: Script locking to prevent accidental deletions or changes

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#242]
If at all possible, it would be great to have a means of "locking" scripts on an account so that a script cannot be accidentally deleted or changed - cloning would be permitted, however.

Due to the nature of Microsoft Imagine's work, it's possible for someone to accidentally delete or change a script while they're working inside of it, and we have no means of recovering it if they've deleted it.  If accidentally changed, it can be difficult to sift through the history sometimes to find the best 'unaltered' version.

**Comment by pelikhan** [comment]
It seems that you should simply publish more often to avoid this issue. Is that an option?
