### ISSUE TITLE
"store in var" not available in tray

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#247]
"store in var" is missing from the options available in the tray. I can find it by searching, but new users don't necessarily know to do this. See the screenshot:
![storeinvar](https://cloud.githubusercontent.com/assets/918682/8744801/f665dc4e-2c2e-11e5-8a17-6817e3d2d123.jpg)

**Comment by pelikhan** [comment]
Could you publish as hidden this script?

**Comment by brian-swan** [comment]
Sure. This script demonstrates the issue: http://tdev.ly/glpnuvuz. (You should see "store in var" when you click on the last line of the script, but you don't.)

**Comment by mmoskal** [comment]
This broke it:

commit f5286823836e4fe228ce52d9e681c9fd765ff707
Author: Peli de Halleux <jhalleux@microsoft.com>
Date:   Mon Jun 15 10:03:50 2015 -0700

    fixes #223
