### ISSUE TITLE
images and copyright/safeguarding within schools 

### ISSUE THREAD

**Issue by leestott** [Microsoft/TouchDevelop#248]
Safe guarding of images on touchdevelop I.e. If someone  uploads a image of someone else in their class how can the image be removed if a student complains.

**Comment by tballmsft** [comment]
Lee, There is a "report abuse" link for every type of publication in the touchdevelop cloud, including artwork.  Furthermore, all artwork is scanned automatically and anything not passing the filter is not indexed and queued for review.
