### ISSUE TITLE
makey makey touchdevelop library issue

### ISSUE THREAD

**Issue by leestott** [Microsoft/TouchDevelop#249]
Touchdevelop libraries makey makey library doesn’t seem to work

**Comment by tballmsft** [comment]
Please provide a detailed repo, including published script exhibiting the problem.

**Comment by leestott** [comment]
Tom I think this is related to the button bug. I.e when use use a collection button sometimes it appears.. With the makey makey, it works/doesnt work. The only fix seems to be exit the script and go back in this can take 2-3 attempts. The makey makey button light, lights when so it looks like a touchdevelop issue.

**Comment by pelikhan** [comment]
Hi lee, please provide complete details and repro when filling issues. TouchDevelop simply emits keystroke for Mackey makey, not clear what can go wrong.

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jul 21, 2015 at 12:38 AM -0700, "Lee Stott" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tom I think this is related to the button bug. I.e when use use a collection button sometimes it appears.. With the makey makey, it works/doesnt work. The only fix seems to be exit the script and go back in this can take 2-3 attempts. The makey makey button light, lights when so it looks like a touchdevelop issue.

-
