### ISSUE TITLE
Behavior of app restart has changed

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#254]
Calls to "app restart" used to pop a dialogue that asked if you wanted to run the script again. That behavior seems to have changed. Now, it simply stops the script. Is this a bug or is there a new API for restarting a script?

**Comment by pelikhan** [comment]
What is your repro?

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jul 21, 2015 at 7:57 PM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Calls to "app restart" used to pop a dialogue that asked if you wanted to run the script again. That behavior seems to have changed. Now, it simply stops the script. Is this a bug or is there a new API for restarting a script?

-

**Comment by brian-swan** [comment]
Sorry...forgot to include the link: http://tdev.ly/iidmaeah

**Comment by pelikhan** [comment]
I see the dialog. Did you try it on a published script?

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jul 21, 2015 at 8:51 PM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry...forgot to include the link: http://tdev.ly/iidmaeah

-

**Comment by brian-swan** [comment]
I tried on two different browsers on my laptop (not a published script) and didn't see the dialog. Just tried the published script on my phone and I do see the dialog. Not sure what is going on. Will check again later.

Sent from my Windows Phone
________________________________

**Comment by pelikhan** [comment]
Might be that it only appears when published right now.

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Jul 22, 2015 at 6:18 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:

I tried on two different browsers on my laptop (not a published script) and didn't see the dialog. Just tried the published script on my phone and I do see the dialog. Not sure what is going on. Will check again later.

Sent from my Windows Phone
________________________________

**Comment by brian-swan** [comment]
Just tried on my laptop again. It **does** seem to be related to whether the script is published. When I try on a script that isn't published, I do not see the dialog. For a script that is published, there is a dialog.

Can this be fixed so that published status doesn't affect behavior?

**Comment by pelikhan** [comment]
After reviewing, it appears that I disabled app->restart in non-published script because it interferes with the tutorial engine. I will re-enable it if the tutorial is off, a better fix requires more work.

**Comment by brian-swan** [comment]
We use this feature in tutorials.

Sent from my Windows Phone
________________________________

**Comment by pelikhan** [comment]
We disabled the app->restart in non-published scripts because of #148

**Comment by brian-swan** [comment]
In the tutorial referenced in #148 (Jetpack), we don't explicitly use app->restart. That API seems to be called automatically when a game ends and it interfered with the tutorial. In CCGA tutorials, we explicitly use app->restart (students are prompted to add this code to their app). If it doesn't work until the app is published, students are confused (we saw this with teachers in the training workshops). Is there a way to separate the behavior based on whether the API is called explicitly?

**Comment by pelikhan** [comment]
Alright, the game library will restart if not published; and app->restart will always pop the dialog regardless of the published behavior.
https://github.com/Microsoft/TouchDevelop/commit/572ec9082abcb15d7dc99047de6db6919e82a8a0
