### ISSUE TITLE
New variable name editing obscures promote to data

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#258]
There seems to be new functionality in a recent build. When I click next to a variable name, I am immediately moved into "edit" mode for the variable name. However, if I want to promote the variable to data, I can no longer click/tap next to the variable name - the "promote to data" option is greyed out and not available (see image). The only way to make "promote to data" an option is to use the left/right arrow keys to get next to the variable name. I suggest rolling this feature back.
![capture](https://cloud.githubusercontent.com/assets/918682/9097340/ee34f5de-3b77-11e5-9309-d94e079faeb7.PNG)

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/TouchDevelop/commit/3f4139c586915128c4ca00be4bccb2a35bcde1de
