### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#26]
We are still missing a bunch of icons. I'll pile up the list as I stumble on them:
- "move left"
- "fix it"
- "action"
...

**Comment by mmoskal** [comment]
Note that most are already fixed on the icons branch.

Micha³
[this letter was sent from a telephone]




On Thu, Feb 12, 2015 at 5:05 AM -0800, "Peli de Halleux" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #26<https://github.com/Microsoft/TouchDevelop/issues/26> to @mmoskal<https://github.com/mmoskal>.

-

**Comment by mmoskal** [comment]
Fixed in e2eddb1b326871f9389643925ebc1449324d1141
