### ISSUE TITLE
Looking at API documentation link and returning to script making functions unusable

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#260]
1. Go to TouchDevelop.com, launch Touch Develop.
2. No need to sign in, just create script.
3. Select blank with the default name that appears.
4. Select the first blank line in main.
5. Select media.
6. Select create landscape board.
7. Store this in a variable (var board is fine).
8. Click elsewhere to deselect the line.
9. Click on the light blue explanatory text to open the API docs for this.
10. Click the back to script arrow.
11. Click on your first line of code again.

Result:
Now the warning message of 'excessive parameter(s) supplied to create landscape board' will appear.

Notes:
This appears to worsen as the user tries to use other media functions and clicks the light blue explanatory text to see the API documentation - it appears parameters start getting stripped out of the functions, making them unusable during a session.

![media bug](https://cloud.githubusercontent.com/assets/2482509/9477337/a6e15ff6-4b26-11e5-8943-9395c58b8035.PNG)

**Comment by pelikhan** [comment]
Looking into this.
