### ISSUE TITLE
LeX Hour of Code 2015: Need setting for create ellipse() function that turns off gradient

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#261]
We'd like to have a means of turning off the gradient on the ellipses created by Touch Develop's 'create ellipse()' function, so that our version of the tutorial looks similar to another popular game that uses flat-colored circles.
![populargame](https://cloud.githubusercontent.com/assets/2482509/9533639/3d14112e-4cc8-11e5-8cfa-8d9eed7c4e26.png)

**Comment by pelikhan** [comment]
I’ve added disabled gradients but it seems that we should also have built-in text on sprites.

**Comment by millerv** [comment]
That'd be a nice feature - locking a sprite to another sprite in general.  When I add text and try to set its position on the x and y of the sprite below it, the text sprite on top 'lags' a bit and slides around. Will log as a separate bug.

**Comment by pelikhan** [comment]
Fixed.
