### ISSUE TITLE
LeX Hour of Code 2015: Lock sprite to another sprite

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#262]
(See image in bug #261 )

As a potential customization piece for learners to pursue after they finish the Hour of Code tutorial, we'd like to offer them an easy way to lock a text sprite or picture sprite inside of their 'circle' character.  The popular game shown in #261 offers a way to put skins and names on each player's circle if they wish, and it would be great if we could do the same via Touch Develop.

Currently when I've tested out 'tying' a sprite to another sprite's center x,y coordinate and we move that sprite around, the sprite on top lags slightly behind and slides around a bit. It makes it obvious that they are not locked/connected.

**Comment by pelikhan** [comment]
Is that still current?

**Comment by millerv** [comment]
Would be a 'nice to have' feature, hence Priority 3.  Please keep it around in the meantime.

**Comment by millerv** [comment]
Closing this out since Hour of Code 2015 is complete.
