### ISSUE TITLE
Need ability to collapse or hide stars in a tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#266]
For some learning scenarios it is necessary to create long tutorials (i.e. tutorials with many steps). In these cases, there are so many stars (representing tutorial steps) that it pushes the instructions for a step off the page (the user must scroll down to see the step instructions). It would be great to have a way to collapse or hide the stars in these cases.

**Comment by pelikhan** [comment]
Do you have a repro?

**Comment by brian-swan** [comment]
The first step shows the issue: http://tdev.ly/urlya.

**Comment by pelikhan** [comment]
Fixed in bea.
