### ISSUE TITLE
Error attempting build

### ISSUE THREAD

**Issue by Vm900** [Microsoft/TouchDevelop#267]
Hi
I'm having problems building locally.
I keep getting lib.d.ts not found error
Please help
Thanks

**Comment by pelikhan** [comment]
Could you copy paste the build output?

**Comment by Vm900** [comment]
Hi
I had given up on trying to do it on windows so i switched to linux and it went swimmingly well.Thanks for the quick response anyway.

**Comment by pelikhan** [comment]
That’s strange… we all use windows ☺
