### ISSUE TITLE
Change prompting in tutorial for storing value in variable 

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#27]
For teaching purposes in a tutorial, the order for storing a value in a variable should be 1) create variable, 2) write the expression for initialization (not the other way around using "store in var")

**Comment by brian-swan** [comment]
The presence or absence of this feature is of mounting importance for the curriculum I'm building. Whether it is enabled or not will affect the video instruction we are building. Ideally, it would be in place before we produce the videos. So, two questions:
1.  How likely is it that this feature will be implemented?
2.  Assuming it will be implemented, what is the timeline for availability?

**Comment by brian-swan** [comment]
In a conversation with Michal, he suggested that it might be possible to add a macro that forced the prompting order I need: 1. prompt for "var", then 2. auto fill variable name and assignment operator, and finally 3. prompt for expression.

**Comment by millerv** [comment]
Closing bug - at this point, the way one creates variables in the Touch Develop tutorials 'works' despite being different than traditional coding. Too much of the curriculum is already built around the current workflow and would require a lot of adjustments as a ripple effect if this feature changed.
