### ISSUE TITLE
App → restart problem

### ISSUE THREAD

**Issue by MichalJamrich** [Microsoft/TouchDevelop#275]
I can not find way to stop the running "run every" loops or selective functions. The only way that I found it through App → restart.
This library function has a bug. If I miss the button "play again " but  I click on the wall below the button, button disappears and the game will remain intractable. I found this error on all games in the showcase using the function. Is there any way to fix this feature or stop loops and functions? Eg. run every until...

**Comment by pelikhan** [comment]
"run every" returns a timer which you can use to stop that handler.

The disappearing button is definitely an issue.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Oct 5, 2015 at 3:47 PM -0700, "MichalJamrich" <notifications@github.com<mailto:notifications@github.com>> wrote:


I can find way to stop the running "run every" loops or selective functions. The only way that I found it through App $B"*(B restart.
This library function has a bug. If I miss the button "play again " but I click on the wall below the button, button disappears and the game will remain intractable. I found this error on all games in the showcase using the function. Is there any way to fix this feature or stop loops and functions? Eg. run every until...

-

**Comment by MichalJamrich** [comment]
Thank you for your recommendation abou timer. 
Is there any way to solve the problem with the "app restart" yourself? Or wait for Microsoft to resolve the error.

**Comment by pelikhan** [comment]
You can fix it and send us a PR.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Oct 6, 2015 at 12:45 AM -0700, "MichalJamrich" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your recommendation abou timer.
Is there any way to solve the problem with the "app restart" yourself? Or wait for Microsoft to resolve the error.

-
