### ISSUE TITLE
Using the "Blank MySQL" Web App, the web site is not reachable

### ISSUE THREAD

**Issue by SocalSam** [Microsoft/TouchDevelop#279]
Using app with pub id /iylla , TouchDevelop indicated that it had created the web site but when the web site would not resolve using the Edge Browser, error 500, web site not found was returned to browser.

So the repo would be:
1. Open TouchDevelop in Edge
2. Create a touchdevelop app using the MySQL Web App
3. Attempt to go to web site generated 
4. Error occurs

**Comment by millerv** [comment]
Due to changes over time in Touch Develop, this bug doesn't occur since the MySQL Web App was removed.
