### ISSUE TITLE
"on every frame" action names are inconsistent

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#28]
The **board** object has an action called **add on every frame**. Other objects have an action called **on every frame**. They essentially do the same thing: evaluate the objects state on every frame. From a teaching (or learning) point of view, this is confusing. Suggestion: Change the function on **board** to **on every frame**.

**Comment by mmoskal** [comment]
I have added an alias. We'll perform automatic renaming once this gets to "current", see #30
