### ISSUE TITLE
Unable to use Template:    To create a Web App in a Dreamspark site

### ISSUE THREAD

**Issue by SocalSam** [Microsoft/TouchDevelop#280]
## Reference TouchDevelop App:  /cxfki

Using the basic template titled: Blank Azure Web App, the app would not build an Azure Web App and posted deployment errors.  I have attached a screen capture of the deployment error.

## To repo the problem:
1. Create a Web App in an Azure DreamSpark Account
2. Retrieve the Publish Settings from the Web App created in step 1
3. Copy the Publish settings from the Web App
4. Open TouchDevelop and then on the front page select the Create Script block
5. In the Create Script dialog box "Select Template Script", select the Blank Azure Web App
6. Once the new Blank Azure Web App is built, publish the "App" to TouchDevelop
7. Switch to the "Script" panel by clicking on the App Name
8. Press the "Azure Web App"
9. Copy and paste the Publish Setting copied to clipboard in step 3
10. Deploy
11. Error occurs, deployment error shown below:
![azure deployment error](https://cloud.githubusercontent.com/assets/7978513/10460544/a94fe800-7189-11e5-811e-6e9f81f727fd.PNG)

**Comment by mmoskal** [comment]
You can try to use more recent node.js version or else wait until this checkin gets to beta. Sorry about that.
