### ISSUE TITLE
Social App tutorial appears to be broken

### ISSUE THREAD

**Issue by SocalSam** [Microsoft/TouchDevelop#283]
Used both Edge and Chrome to test issue, Windows 10, brand new installation
1. Open the Social App tutorial
2. do the first step which takes the user to the variable naming page
3. Perform the step in the tutorial and add the word "Picture"
4. No new tutorial bubble shows up, if a mistake is forced, a tutorial bubble shows up, but no next step type of bubble.

**Comment by pelikhan** [comment]
We've removed those tutorials.
