### ISSUE TITLE
Right-to-left languages showing incorrect caption punctuation in Internet Explorer

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#284]
Steps to reproduce:
1. In a tutorial like the CCGA TDT 4 "Collage Tutorial", embed a video on a tutorial step.
2. Include a caption (.vtt) file for this video that uses a right-to-left language like Arabic.
3. Follow the tutorial and watch the captions in Internet Explorer.
4. Follow the tutorial again and watch the captions in Google Chrome.

Result:
The text is laid out correctly from right-to-left in Internet Explorer, but it puts the punctuation (the period) in the wrong location (on the right end like English, instead of on the left end, for Arabic).
![ara_ie_vs_chrome](https://cloud.githubusercontent.com/assets/2482509/10619405/6204b556-772a-11e5-90bc-fd4fd01c6688.jpg)

**Comment by ilabar** [comment]
Still on this topic, I asked the Arabic resource to review this bug and the feedback is the following.
The Arabic CCs handed back are displaying correctly in GoogleChrome while displaying incorrectly in IE. When you zoom in to see the full stop at the end of sentence on below image, you can see it is properly on the left hand side in Chrome, while incorrectly displayed on right hand side in IE. The text orientation is correct in both cases except the punctuation.

**Comment by pelikhan** [comment]
Is there anything we can do here? This seems like a browser specific issue.

**Comment by millerv** [comment]
Ilaria - please have your Arabic team member try adjusting the Languages and Accessibility Captions in Internet Explorer 11 to see if the punctuation appears correctly if they're set with Arabic in mind.  See these screenshots for details:

![td_ie11_languages](https://cloud.githubusercontent.com/assets/2482509/10797665/fd7ad092-7d60-11e5-9c82-1f69ebea68b5.PNG)

![td_ie11_accessibility](https://cloud.githubusercontent.com/assets/2482509/10797673/03afa942-7d61-11e5-8d1a-435d8f5bac3a.PNG)

**Comment by ilabar** [comment]
Hi, our vendor followed the settings described, the result is that captions are still not displayed properly on IE.
In our opinion it is a browser bug since it occurs only for Internet Explorer, the visualization is correct using Google Chrome.
![ara_issues_01](https://cloud.githubusercontent.com/assets/15230722/10844654/33377fb6-7ef9-11e5-8c08-0c617018cc59.png)

**Comment by pelikhan** [comment]
Doesn't seem that we can do anything there besides reaching out for IE.
