### ISSUE TITLE
Right-to-left languages impossible(?) to copy into Touch Develop - reverses sentences

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#285]
Steps to reproduce:
1. Find right-to-left language text like Arabic and copy it from a Word document or web page. 
2. Open a tutorial like the CCGA TDT 4 "Collage Tutorial", and then open the script's description (the text that appears when you first open the script - that landing page).
3. Paste the copied right-to-left text into the script's description.

Result:
When the right-to-left text is pasted into the description, all the words 'flip' and it reverses the sentence.  The English equivalent would be a sentence like "Hello my name is Bob." turning into ".Bob is name my Hello"

Expected:
Need some means of tagging text that we drop in from the localization teams' translations as "this is right-to-left" instead of always defaulting to English-style left-to-right.

**Comment by ilabar** [comment]
Localization vendor states that there is no way to specify text direction in plain text formats like JSON or VTT subtitles.
It means that there is no "correct" way of copying and pasting Arabic from such plain text – the text direction information is simply not there, so there is no way to 'preserve' it during copying.
A good practice when copy/pasting the text from Word is to make sure that on the machine there are Arabic regional settings for the OS, but we can’t say whether it will help or not. Still worth a try.

**Comment by pelikhan** [comment]
I don't understand how we can help here.

**Comment by millerv** [comment]
During our IM conversation, you mentioned that it may be possible to 'sample' the first character of a sentence (like Chrome?).  Either that or I need some sort of flag/macro/tag/character that I can use in edit fields that will tell Touch Develop "this is a right-to-left sentence".
