### ISSUE TITLE
microbit basic->plot image doesn't take an image.

### ISSUE THREAD

**Issue by markshannon** [Microsoft/TouchDevelop#287]
On https://www.microbit.co.uk
The following code gives me a type error
```
microbit basic->plot image(image->create image(X))
```
"'plot image' expects String here got ♲ micro:bit ->image"
This is not good API design. `plot image` should be able to plot an image.

**Comment by mmoskal** [comment]
This issue is fixed in our development version. Unfortunately it can take as long as two weeks for this change to reach www.microbit.co.uk.

Thanks for the feedback!
