### ISSUE TITLE
Tutorials: Master script not pulling in translated tutorial step text

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#288]
Steps to reproduce:
1. Go to the Collage Tutorial (TDT 4) at http://aka.ms/CollageTutorial.
2. Set your language to es, fr, ar, or zh.
3. Follow the tutorial and watch the in-between tutorial text boxes.

Result:
The correct posters, videos, and captions are pulled in, but the text from the localized script is not.

![td_es_shows_en_02](https://cloud.githubusercontent.com/assets/2482509/10680926/246ace64-78d9-11e5-991f-5ebd6e922ea9.PNG)

**Comment by tballmsft** [comment]
requires deep developer dive.
