### ISSUE TITLE
Tutorials: Tutorials not referring to localized version's code

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#289]
Steps to reproduce:
1. Go to http://aka.ms/CollageTutorial.
2. Set your language to es, fr, ar, or zh
3. Follow the tutorial steps, and then watch the blue code hint box.

Result:
We ask the learner to type in something in their native language, but this isn't carried over into the master script. (The text below should show something in Spanish instead of what the prompt/hint box shows in English)

![td_es_shows_en](https://cloud.githubusercontent.com/assets/2482509/10680961/74785da4-78d9-11e5-9f1e-ac6c3ad27202.PNG)

**Comment by pelikhan** [comment]
This is not supported. Only comment in between dialogs are localizable.

**Comment by millerv** [comment]
Can we put this on a feature request list somehow? There are several CCGA tutorials that will have similar needs for in-code localizable strings.

**Comment by pelikhan** [comment]
This is not easy to implement and unlikely to happen soon . I suggest publishing completely independent tutorials instead.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Nov 3, 2015 at 10:27 AM -0800, "millerv" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #289<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fMicrosoft%2fTouchDevelop%2fissues%2f289&data=01%7c01%7cjhalleux%40microsoft.com%7c4cb95d823f644b9fbbb808d2e47c5f76%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=xrhaNPwPm1rVAeO9ci%2b%2fy%2fToD1A0l7tyKBCOFZrVTAk%3d> to @pelikhan<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fpelikhan&data=01%7c01%7cjhalleux%40microsoft.com%7c4cb95d823f644b9fbbb808d2e47c5f76%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=o3bPfTHgbSqsxafaRssI3NR21otGSevNPq4LHvv9TMA%3d>.

-
