### ISSUE TITLE
Tutorial prompts for sound asset unnecessarily

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#29]
This tutorial requires that a user add a sound that is included as part of the script: http://tdev.ly/knzbqxul 
However, the tutorial engine prompts the user to search for a sound. It should prompt the user to use the sound that is available as part of the script (see screenshot).
![soundexample](https://cloud.githubusercontent.com/assets/918682/6175663/a0d35e5a-b2ad-11e4-84e2-e30d9140b07c.PNG)

**Comment by pelikhan** [comment]
By default, the tutorial engine always prompt the user for art resources. It allows users to customize the pic/sounds while keeping the same gameplay.

In general, we could prepopulate the search with the art resources already available in the script so it the user can select easily.

**Comment by brian-swan** [comment]
OK. I can live with this, but (from a teaching point of view) it raises the priority of #15 . That one is high priority for the work I'm doing now. It affects multiple tutorials.
