### ISSUE TITLE
Tutorials: Run button not visible after entering code on several tutorials

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#290]
Steps to reproduce:
1. Go to http://aka.ms/CollageTutorial.
2. Follow the tutorial steps until it asks the learner to create a picture.
3. Once you add the robot picture and then assign that to a variable, note the prompt pointing to where the Run button usually appears.

Result:
The Run button is not visible and the prompt points at a blank space during the tutorial.

![tdt4_missingui_01](https://cloud.githubusercontent.com/assets/2482509/10681037/36fa095e-78da-11e5-89db-35daf64bb251.PNG)

**Comment by millerv** [comment]
Update: Bug present in new backend as well.

**Comment by millerv** [comment]
This issue is occurring in several tutorials currently.

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/TouchDevelop/commit/aef03f179517decfb5c944564f3f9e0064972708

**Comment by millerv** [comment]
Not seeing this on the Touch Develop web app yet.

**Comment by millerv** [comment]
Still active in current version of Touch Develop, see video here:  http://1drv.ms/1XP5Krr

**Comment by millerv** [comment]
After trying this out in a few tutorials, this appears to be fixed.  Closing bug.
