### ISSUE TITLE
Tutorials: Prompt incorrectly directs learner when they need to change current code

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#291]
Steps to reproduce:
1. Go to http://aka.ms/CollageTutorial.
2. Follow the tutorial steps until you're asked to change the font size (the 3rd parameter) in a line of code that you wrote in the previous step.
3. After watching the video, note where the tutorial prompt is located, and how it directs the learner.

Result:
After the learner watches the video for this 'change font size' step of the tutorial, the screen automatically shows the prompt on moving the cursor around - but this won't get the learner where they need to go to complete this step. The right and left buttons show "move cursor" but it actually cycles through the pages of functions and related code instead.

Note:
If the learner accidentally clicks off and then back onto the code, the blue code hint box will appear correctly and the prompts will work correctly again.

Edit:
Video of behavior:  http://1drv.ms/1LWg6lZ

![tdt4_incorrectprompt_01](https://cloud.githubusercontent.com/assets/2482509/10681197/ad525808-78db-11e5-9ad6-d5d9f5d6f141.PNG)

**Comment by pelikhan** [comment]
Is there a smaller repro?

**Comment by millerv** [comment]
This is the closest/shortest I can get it:  http://tdev.ly/ookmyarg

**Comment by millerv** [comment]
Seeing this in next.touchdevelop.com as well.

**Comment by millerv** [comment]
Tried this out in a few tutorials where the issue was reported - appears to be fixed, closing bug.
