### ISSUE TITLE
Tutorials: Error message if learner tries different picture insertion method

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#292]
Steps to reproduce:
1. Go to http://aka.ms/CollageTutorial
2. Follow the steps until prompted to change the background at the end of the tutorial.
3. Tap on the line as prompted to select it.
![tdt4_bg_prompt_01](https://cloud.githubusercontent.com/assets/2482509/10681344/2254108c-78dd-11e5-931d-e47016749c62.PNG)
4.Once the line is selected, note the prompt to 'replace picture' - click on the Backspace key instead.
![tdt4_bg_prompt_02](https://cloud.githubusercontent.com/assets/2482509/10681360/4271ec86-78dd-11e5-8f34-4b2534f36dcb.PNG)
5. The prompt will move to the search bar and auto-populate with 'grid background' when clicked, do so and select one of the backgrounds offered.
![tdt4_bg_prompt_03](https://cloud.githubusercontent.com/assets/2482509/10681368/663b824e-78dd-11e5-937a-1016e8661757.PNG)

Result:
An error message will appear at the bottom of the screen in a hot pink message bar that says: "unknown tutorial step: change"
![tdt4_errormsg_01](https://cloud.githubusercontent.com/assets/2482509/10681380/88ebad50-78dd-11e5-9435-5db4b70a7936.png)

**Comment by pelikhan** [comment]
Hi valerie, could you provide a minimal repro step?

**Comment by millerv** [comment]
Give this super-short example script hidden publish a try: http://tdev.ly/wolxeyjs
