### ISSUE TITLE
Localization: Sign-in screen needs to provide localizable strings (see inside)

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#294]
Steps to reproduce:
1. Go to http://www.touchdevelop.com/
2. Launch Touch Develop.
3. Click on the Sign In button.

Result:
The strings of text shown on this screen need to appear on the translation site at https://touchdeveloptranslator.azurewebsites.net.  These include:

"TouchDevelop client apps use cloud services to synchronize your scripts across all your devices."

"By signing in to TouchDevelop you agree to the Cloud Services Agreement with Microsoft Research. Please read our statement on Privacy and Cookies."

"sign in with..."

![media2_signin](https://cloud.githubusercontent.com/assets/2482509/10777486/4e90035e-7cd9-11e5-8502-5950c21f179d.png)

**Comment by pelikhan** [comment]
We are currently reworking the cloud backend so this page will be completely redone. ETA december.

**Comment by millerv** [comment]
This is now available via the CrowdIn tool and website.json strings.  Closing bug.
