### ISSUE TITLE
Localization: More Settings on account page text "Browse" needs localizable string

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#295]
Steps to reproduce:
1. Go to http://www.touchdevelop.com/
2. Launch Touch Develop.
3. Click the sign in button and sign in with an account.
4. Click on the account name.
5. Click on More Settings.
6. Scroll down to where the account holder can customize their picture icon.

Result:
The strings for "Browse" and "Picture" do not offer localizable strings on https://touchdeveloptranslator.azurewebsites.net and cannot be localized at this time.

![media2_picture_browse](https://cloud.githubusercontent.com/assets/2482509/10777603/607f484e-7cda-11e5-931b-141cd4c69e0a.PNG)

![td_moresettings](https://cloud.githubusercontent.com/assets/2482509/10777607/663b93fa-7cda-11e5-956a-57197f2f8d05.PNG)

**Comment by pelikhan** [comment]
"browse" is a native UI element. picture fixed.

**Comment by millerv** [comment]
Tested in latest, build 82084, issue still occurring.  See attached picture.
![td_picture_text](https://cloud.githubusercontent.com/assets/2482509/10901932/b222c98e-81ab-11e5-8679-90911a8d02ab.PNG)

**Comment by pelikhan** [comment]
Probably no translator availabe for picture.

**Comment by millerv** [comment]
Hey Peli, would something like this work?  http://www.shauninman.com/archive/2007/09/10/styling_file_inputs_with_css_and_the_dom
