### ISSUE TITLE
Localization: Language pulldown needs to offer languages in native alphabets

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#296]
1. Go to http://www.touchdevelop.com/
2.  Launch Touch Develop.
3. Click the sign in button and sign in with an account.
4. Click on the account name.
5. Click on More Settings.
6. Scroll down to the language pulldown selector.

Result:
These strings are not localizable via https://touchdeveloptranslator.azurewebsites.net/ and only appear in English.  When a non-English user is changing language settings, the pulldown needs to offer their language, in their language's alphabet.

![td_moresettings](https://cloud.githubusercontent.com/assets/2482509/10777667/fc9b01b4-7cda-11e5-9b56-1f7d20bdc0e4.PNG)

**Comment by pelikhan** [comment]
This requires a cloud backend update will have to wait till december.
