### ISSUE TITLE
double escape for some translation strings

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#301]
![image](https://cloud.githubusercontent.com/assets/4175913/10860415/eecfc9c4-7f24-11e5-9967-227b0e97c588.png)

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/10860430/252c1c52-7f25-11e5-8199-316c9cf0e7eb.png)

**Comment by millerv** [comment]
No longer using this translation service, will monitor incoming translations and bug on a per-line basis - closing bug.
