### ISSUE TITLE
Backend migration

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#304]
The drop dead date for migration is beginning of December.

Tasks:
- [x] allow migration of old accounts via Access Control Service
- [x] import all scripts/users/...
- [x] implement workspace import
- [x] tutorial progress APIs
- [x] import group memberships (?)
- [x] add privacy/legal links
- [x] sort out CDN url(s) in the client (need to recognize more than one and rewrite) **merge**
- [x] update Google to use a more official Client ID
- [x] make next.td.com always use api.td.com, not www.td.com
- [x] add Yahoo support
- [x] add account linking between different providers
- [x] skip all legacy linking for FB logins - we can recognize them directly
- [x] migrate doc pages
- [x] build server upload of web app
- [x] encrypt shell
- [x] do something about API keys in user's account (drop?)
- [x] /progressstats endpoint
- [x] **review permissions** - search, list scripts etc
- [x] add HOC page
- [x] check other pages, add redirects
- [x] Azure website deployment support
- [x] add client support for getting migration tokens when deployed on next
- [x] start alpha.td.com
- [x] support /blog/ redirect
- [x] tick logging
- [x] static script/tutorial page
- [x] import ACS status of art
- [x] user's profile picture
- [x] web proxy
- [x] integrate ACS sanization
- [x] add alternate providers page to explain that we're migrating
- [x] serve the correct updated favicon.ico
- [x] https://legacy.touchdevelop.com/app/authorize (tutorial translator)

Final:
- [ ] refresh zip file with npm packages and node
- [x] up-scale next.td.com
- [x] DNS update www.touchdevelop.com -> tdnxt.cloudapp.net

Later:
- [x] cloud storage access token
- [x] user oauth
- [ ] make backup work (right now out-of-memory when listing blobs)
- [ ] add webapp support (?) (Office Mix dependency)
- [ ] canexport API (App Studio dep)
- [x] build server upload of web pages (?)
- [ ] add doc pages TOC
- [ ] search in docs
- [ ] should 'get from facebook' for picture copy the picture?
- [ ] integrate tutorial translator web site

**Comment by pelikhan** [comment]
"
The download link for the local install npm install -g http://aka.ms/touchdevelop.tgz (that redirects to https://www.touchdevelop.com/api/language/touchdevelop.tgz) also errors out, with a cert error on raspian ('certificate is not yet valid'), and with an http error 500 when trying to download it with wget --no-check-certificate.
"
