### ISSUE TITLE
Tutorials:  Landing pages not pulled in localized tutorial 

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#305]
Let's take as an example Simplified Chinese, anyway this bug occurs also for ARA/FRA/LAS.
The translated content we delivered is depicted below and as you can see it is not matching with what is visualized in the TD UI.
Please provide a fix, if possibile.

Thanks
Ilaria
![landing page tutorial chs](https://cloud.githubusercontent.com/assets/15230722/10908559/85dbd706-822a-11e5-8cb5-239f1da3d7e9.png)
![screnshot tutorial chs](https://cloud.githubusercontent.com/assets/15230722/10908583/a71757ec-822a-11e5-8958-fe27747d69c0.png)

**Comment by millerv** [comment]
It looks like the string "by" is not available in https://touchdeveloptranslator.azurewebsites.net/app/#.  This needs to be added so the loc team can add their translations.

The string "tutorial" looks like it is available in https://touchdeveloptranslator.azurewebsites.net/app/#, so I'll ask Ilaria and team to add and upvote their translations - we'll need another loc push after they finish this and the "by" string, whenever it is enabled.

**Comment by ilabar** [comment]
The tutorial” string was just localized via TD Translator. We voted with 20 points for each of 9 languages.
For the string "by" we need support from dev team. Can you please tell us once the English is added?

**Comment by pelikhan** [comment]
This page is in the web site which is being rebuilt right now.

**Comment by ilabar** [comment]
so we won't get it fixed for localized versions right now? keep us posted on when the new page in English will be ready as we might decide to update the localized versions to reflect the changes.
