### ISSUE TITLE
Localized Collage Tutorial: truncation issue for some images

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#307]
Hi,
steps to reproduce.
Go to the live version of the Collage tutorial into 9 languages:
a.	German (de): http://www.touchdevelop.com/qndjc
b.	Japanese (ja): http://www.touchdevelop.com/ofbw
c.	Korean (ko): http://www.touchdevelop.com/avhcc
d.	Dutch (nl): http://www.touchdevelop.com/sexfe
e.	Brazilian Portuguese (pt): http://www.touchdevelop.com/exnec 
a.	Arabic (ar): http://www.touchdevelop.com/uofoi
b.	Latin American Spanish (es): http://www.touchdevelop.com/oinji
c.	French (fr): http://www.touchdevelop.com/kffe 
d.	Chinese (zh and zh-CHS): http://www.touchdevelop.com/uqjke 

There are some truncated char in the images that we would like to get fixed. All the details of the images affected by this problem here attached.

French:
![image](https://cloud.githubusercontent.com/assets/15230722/10972545/a7ca7608-83d1-11e5-8c29-e338780c7a1f.png)

Chinese:

![image](https://cloud.githubusercontent.com/assets/15230722/10972577/be3c8066-83d1-11e5-9546-08b7410ef460.png)

![image](https://cloud.githubusercontent.com/assets/15230722/10972655/18355746-83d2-11e5-8b29-8c559accb87d.png)

![image](https://cloud.githubusercontent.com/assets/15230722/10972717/5381d4c8-83d2-11e5-921b-4434be00bd6e.png)

Arabic:

![image](https://cloud.githubusercontent.com/assets/15230722/10972728/6177f418-83d2-11e5-81ff-80e4299ac365.png)

German:

![image](https://cloud.githubusercontent.com/assets/15230722/10972743/6ff97318-83d2-11e5-9889-2d15b3d480e7.png)

Dutch:

![image](https://cloud.githubusercontent.com/assets/15230722/10972758/8063229e-83d2-11e5-9c48-433424082639.png)

Brazilian Portuguese:

![image](https://cloud.githubusercontent.com/assets/15230722/10972772/8dad9d58-83d2-11e5-9eee-98c0a26b105c.png)

![image](https://cloud.githubusercontent.com/assets/15230722/10972783/964de760-83d2-11e5-9b1c-906bea30586e.png)

Korean:
![image](https://cloud.githubusercontent.com/assets/15230722/10972803/b028367c-83d2-11e5-9574-a137386f5711.png)

![image](https://cloud.githubusercontent.com/assets/15230722/10972807/b582f814-83d2-11e5-83ec-5f325ea7b176.png)

Japanese:

![image](https://cloud.githubusercontent.com/assets/15230722/10972814/c05963cc-83d2-11e5-8cc7-8312d69be8f6.png)

![image](https://cloud.githubusercontent.com/assets/15230722/10972825/ccc75664-83d2-11e5-85ce-9c6e7e9c28f9.png)

Latam Spanish:

![image](https://cloud.githubusercontent.com/assets/15230722/10972831/d7f7d522-83d2-11e5-8c9b-5a2c544ef488.png)

**Comment by ilabar** [comment]
Hi, checked this morning and nothing has changed. I'll actually add a couple more truncation issues we have logged for German. 
Can you give a feedback if you can fix these issues asap?

Thanks
Ilaria

**Comment by ilabar** [comment]
here the screenshots for German:

![image](https://cloud.githubusercontent.com/assets/15230722/11038104/3df5bff0-86f9-11e5-959f-09b283350796.png)

![image](https://cloud.githubusercontent.com/assets/15230722/11038121/4e5044c4-86f9-11e5-9215-1a60658b8b4c.png)

**Comment by ilabar** [comment]
Can you please push these fixes to the live site? we cannot take the fixes from beta version since the overall UI looks partially and not entirely localized.

Thanks!

**Comment by pelikhan** [comment]
It's live.
