### ISSUE TITLE
Backend: Cannot complete Coding Jetpack Jumper, no pictures available

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#311]
Description:
Cannot complete the Coding Jetpack Jumper tutorial in the new backend since there are no pictures to choose from.

Steps to reproduce:
1. Make sure to adjust the etc/hosts file for the new backend.
2. Once signed in to the new backend, go to the Coding Jetpack Jumper tutorial.
3. Follow the tutorial steps until near the end, where the learner is encouraged to choose a new picture to replace the picture of Bot.

Result:
When the learner attempts to replace the picture of the robot, no pictures are offered on the search and the tutorial prompt 'sticks' in place.

Notes:
Video available at:  http://1drv.ms/1RCdlHS

**Comment by millerv** [comment]
Hitting this in several other CCGA tutorials - cannot progress and test further.

**Comment by mmoskal** [comment]
Should fix in 15 min

**Comment by mmoskal** [comment]
Should be fixed in **beta 0.0.56.**
