### ISSUE TITLE
investigate translation service to use

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#313]
Some ideas:

https://crowdin.com/
http://www.oneskyapp.com/ 
https://webtranslateit.com/en 
http://docs.phraseapp.com/ 
https://www.transifex.com/ 
https://wovn.io/ 
https://unbabel.com/ 
https://www.smartling.com/

**Comment by mmoskal** [comment]
CC @pelikhan

**Comment by pelikhan** [comment]
https://crowdin.com/ seems to be a great contender.
