### ISSUE TITLE
Backend: Screenshot feature not available.

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#314]
Description:
Screenshot feature not available.

Steps to reproduce:
1. Make sure to adjust the etc/hosts file for the new backend.
2. Once signed in to the new backend, enter any activity like http://aka.ms/ChasePro
3. During the activity, attempt to take a Screenshot.

Result:
When the user attempts to take their screenshot, and then proceeds from the picture preview page, they receive an error message and cannot take the screenshot.
![backend_publishscreenshot_01](https://cloud.githubusercontent.com/assets/2482509/11007294/cdd663be-847d-11e5-8137-eb0abc6d4ce5.PNG)
![backend_publishscreenshot_02](https://cloud.githubusercontent.com/assets/2482509/11007295/d13969fc-847d-11e5-919b-141b693394c4.PNG)

**Comment by mmoskal** [comment]
Should be fixed now; please test and close

**Comment by millerv** [comment]
Confirmed as fixed, closing bug.
