### ISSUE TITLE
Backend: (maybe?) Tutorial engine breaks after "read more..." on Change Skill level

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#315]
Description:
Tutorial engine breaks after "read more..." on Change Skill Level

Note: Not certain if backend related, but this was the original situation where bug was discovered.

Steps to reproduce:
1. Make sure to adjust the etc/hosts file for the new backend.
2. Once signed in to the new backend, enter any activity like Collage Tutorial (http://aka.ms/CollageTutorial)
3. Proceed to a step where control passes to the user on a step where they need to make edits.
4. On this step, ignore the blue tutorial prompt pointing at the line to change/update/add, and scroll down to "Change Skill Level"
5. On this UI, click on "Read More..."
6. Click on the arrow button to return to the script.
7. Look for the blue tutorial prompts and try to click on the star in the circle button to review the tutorial step.

Result:
The tutorial engine appears to 'break' if the user tries to "Read more" on skill levels and returns to their script.

Notes:
See video: http://1drv.ms/1XUZmRq

**Comment by pelikhan** [comment]
Should not be able to change skill in flight....

Sent from Outlook<http://aka.ms/Ox5hz3>




On Fri, Nov 6, 2015 at 12:15 PM -0800, "millerv" <notifications@github.com<mailto:notifications@github.com>> wrote:


Description:
Tutorial engine breaks after "read more..." on Change Skill Level

Note: Not certain if backend related, but this was the original situation where bug was discovered.

Steps to reproduce:
1. Make sure to adjust the etc/hosts file for the new backend.
2. Once signed in to the new backend, enter any activity like Collage Tutorial (http://aka.ms/CollageTutorial<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2faka.ms%2fCollageTutorial&data=01%7c01%7cjhalleux%40microsoft.com%7ce98661c25b1d41657fdf08d2e6e710b4%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=cVZdUieJQ0G3CcdwnWGnYYi2AdMxR%2bPqQ7Pt7Aksq5k%3d>)
3. Proceed to a step where control passes to the user on a step where they need to make edits.
4. On this step, ignore the blue tutorial prompt pointing at the line to change/update/add, and scroll down to "Change Skill Level"
5. On this UI, click on "Read More..."
6. Click on the arrow button to return to the script.
7. Look for the blue tutorial prompts and try to click on the star in the circle button to review the tutorial step.

Result:
The tutorial engine appears to 'break' if the user tries to "Read more" on skill levels and returns to their script.

Notes:
See video: http://1drv.ms/1XUZmRq<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f1drv.ms%2f1XUZmRq&data=01%7c01%7cjhalleux%40microsoft.com%7ce98661c25b1d41657fdf08d2e6e710b4%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=NcKbEQY0JVncNPvJa%2bulu2CNWRo%2fcLFD%2fsQqgA9LLaQ%3d>

-

**Comment by pelikhan** [comment]
link removed.

**Comment by millerv** [comment]
Can change skills levels fine, read more link removed, so no more breakage this way.  Closing bug.
