### ISSUE TITLE
Tutorials: Undo button does nothing in keypad UI during tutorial.

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#316]
Description:
Undo button does nothing in keypad UI during tutorial.

Note: Not certain if backend or tutorial related, but this was the original situation where bug was discovered.

Steps to reproduce:
1. Make sure to adjust the etc/hosts file for the new backend.
2. Once signed in to the new backend, enter any activity like Collage Tutorial (http://aka.ms/CollageTutorial)
3. Proceed to a step where control passes to the user on a step where they need to make edits.
4. On this step, add the requested code.
5. Attempt to click on Undo under the backspace keypad button.
6. Try other code features and then click the Undo button.

Result:
The Undo button just seems to remove focus from the keypad, and doesn't undo the last action(s)

Notes:
See video: http://1drv.ms/1MNC125

**Comment by pelikhan** [comment]
That does not seem to be backend related.

**Comment by millerv** [comment]
You're right, not Backend related. Title fixed.
Undo button still doesn't seem to do anything other than remove focus though - doesn't actually Undo anything.
