### ISSUE TITLE
Backend: Hidden publish on account doesn't appear on new backend.

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#317]
Description:
Backend: Hidden publish on account doesn't appear on new backend.

Steps to reproduce:
1. On the older backend, login to an account.
2. Create a script and hidden publish that script.
3. Write down or note the hidden publish script ID.
4. Allow sufficient time for it to copy to the new backend.
5. Adjust the etc/hosts file for the new backend access and login.
6. Once logged in to the new backend with the account, look at all the available scripts.
7. Type the script ID of the hidden publish into the search.

Result:
The hidden publish script appears when searching for that ID, but won't appear on the account in the new backend. See screenshots.

![backend_nohiddenscripts](https://cloud.githubusercontent.com/assets/2482509/11024090/d3e71520-863d-11e5-9fd1-7d3faac075df.PNG)

![backend_hiddenscript](https://cloud.githubusercontent.com/assets/2482509/11024092/db1a07c6-863d-11e5-9866-8463d025a7fd.PNG)

**Comment by mmoskal** [comment]
The new backend treats the hidden but more seriously - namely hidden scripts are only visible in various lists for the creator of that script. After all it's supposed to be hidden.

Let me know if you relied on the old behavior.

**Comment by millerv** [comment]
Ah, the issue is that the creator (Microsoft Virtual Academy) couldn't even see their own Flatverse tutorial, since it was hidden and needed to just mentally remember the script ID and search for it that way.

**Comment by mmoskal** [comment]
The hidden script shows up in the user's page (in the "Scripts by this user:" section). It will not appear in the list of your installed scripts if you have published it from the old backend - this workspace is only synchronized once. After we switch it will be a non-issue.

**Comment by mmoskal** [comment]
Please close if OK.

**Comment by millerv** [comment]
I think(?) this is working ok, as far as I can tell on my accounts.
