### ISSUE TITLE
Backend: Using the unhide button on a hidden script won't make the unhidden script appear properly on new backend.

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#318]
Description:
Backend: Using the unhide button on a hidden script won't make the unhidden script appear properly on new backend.

Steps to reproduce: 
1. On the older backend, login to an account.
2. Create a script and hidden publish that script.
3. Write down or note the hidden publish script ID.
4. Allow sufficient time for it to copy to the new backend.
5. Use the 'unhide' button on the script - this gives the script a new script ID.
6. Write down this new script ID somewhere for easy reference.
7. Adjust the etc/hosts file for the new backend access and login.
8. Once logged in to the new backend with the account, look at all the available scripts.
9. Try to find the script that you 'unhid'.
10. Now, type the script ID of the hidden publish into the search.

Result:
The script that was initially hidden, then set to unhidden will appear as a 'hidden' version of the unhidden script ID.
(In this screenshot, this script ID was actually unhidden on the old backend, but is displayed as "hidden" on the new backend.)
![backend_hiddenscript](https://cloud.githubusercontent.com/assets/2482509/11024101/02e723d8-863e-11e5-92b1-6b6315cf3e21.PNG)

**Comment by mmoskal** [comment]
Hide/unhide is not supported in the new backend (at least yet). I'm inclined to drop it from the app, as you can now delete your scripts if you want. Comments?

**Comment by pelikhan** [comment]
In doubt we should drop. The user can republish.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Nov 9, 2015 at 8:04 AM -0800, "Michał Moskal" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hide/unhide is not supported in the new backend (at least yet). I'm inclined to drop it from the app, as you can now delete your scripts if you want. Comments?

-

**Comment by millerv** [comment]
Looks like a hidden publish can be republished as public, closing bug.
