### ISSUE TITLE
Tutorials: Tutorial prompt for creating new function, naming it, adding parameters difficult for learners

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#319]
Description:
Tutorials: Tutorial prompt for creating new function, naming it, adding parameters difficult for learners
Steps to reproduce:
1. Enter a tutorial that requires creating a new function, renaming it, and adding parameters.
2. Use http://tdev.ly/ydmdyncb as a short version.
3. Note where the tutorial prompt shows the pointiest part when the learner needs to rename the function.
4. Instead of clicking on the name part, click on the green word "function".
5. Instead of typing there, click back on the name part in the main coding area.

Result:
The way the tutorial prompt points to what the learner needs to work on is confusing and can easily display the prompt incorrectly. 

Note:
Video available at: http://1drv.ms/1SCvyWO

**Comment by millerv** [comment]
User voice posters encountering this issue:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10659558-functions-tutorial-1

**Comment by pelikhan** [comment]
Fixed in 2092

**Comment by pelikhan** [comment]
Pushed to beta please test.

**Comment by millerv** [comment]
This looks better - will keep an eye out for any more feedback.  Closing bug.
