### ISSUE TITLE
Groups: CCGA educators hitting "access denied" and related issues in the Groups area

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#323]
Description:
CCGA educators hitting "access denied" and related issues in the Groups area.

Steps to reproduce:
1. Log into an account with a pre-existing group and members in that group.
2. After logging in, scroll over to the Groups area and click on a group.
3. In this group, attempt to delete comments, scripts, or users.

Result:
Several "access denied" errors are flustering current CCGA educators using Touch Develop - they relied on deleting items in this Groups area to track materials they had already graded.

Notes:
See video here (additional strange pink banner error message at end too):  http://1drv.ms/1HKAvGz

**Comment by millerv** [comment]
Report(s) on User Voice:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10642722--add-a-script-to-a-group-does-not-work

**Comment by mmoskal** [comment]
I think the User Voice post above is something else - @sebastianburckhardt I believe the user voice thing should be now fixed, right?

**Comment by millerv** [comment]
Following up with affected users.

**Comment by millerv** [comment]
Sounds like affected users are doing ok - will keep an eye out.  Closing bug now.
