### ISSUE TITLE
CCGA: Not all scripts appearing in My Scripts after changeover to new backend

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#324]
Description:
Not all scripts appearing in My Scripts after changeover to new backend

Note: 
This doesn't have clean repro steps due to the nature of the situation.  

CCGA teachers are not seeing all of the scripts that they've worked on appear in their My Scripts area after the changeover to the new backend.  

I also encountered this with the Microsoft Virtual Academy account and Flatverse:
1. Before the changeover, I worked in the older backend on Flatverse and published it there.
2. After the changeover (today, Thurs Nov 12th) I tried to find Flatverse on my list of "My Scripts" and could not. (Fortunately because I had sent previous emails with the link to /mbahc I was able to find it again.)
3. Searching for /mbahc showed the script and when I worked with it, it was populated to My Scripts again.

Question:
Would it be possible to force-poplulate everyone's My Scripts on their accounts with every single one of their scripts that they've worked on in the past?  Or something to add anything they've created, whether published or not, back to a visible and easily accessible place?

**Comment by mmoskal** [comment]
For the MVA account, it may be that you migrated it to the new backend, and kept working on it in the old backend. The import of scripts in account only happens once, when you migrate - this shouldn't be a problem for the teachers, as there is no old backend to work on right now.

I was seeing a number of creshes in the backend relating to the import. Such a crash would make the import process stall, as it tries to re-import this one script. It may be that if they sync again, the remaining scripts will get imported.

For published scripts, you can always go to your account page (just click on your name in the Hub) and see at the list of "scripts by this user". It should include hidden scripts.

**Comment by millerv** [comment]
Following up with affected users.

**Comment by millerv** [comment]
No recent reports of this issue, closing bug.
