### ISSUE TITLE
missing documentation pages in new backend

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#325]
User voice posters have found the following broken links so far:

https://www.touchdevelop.com/docs/stringmap
https://www.touchdevelop.com/docs/pages
https://www.touchdevelop.com/docs/wall

**Comment by millerv** [comment]
User voice post:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10673946-missing-pages-for-links-on-https-www-touchdevelo

**Comment by millerv** [comment]
User voice post: https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10634496-fix-the-missing-page-https-www-touchdevelop-com

**Comment by codespare** [comment]
The download link for the local install ```npm install -g http://aka.ms/touchdevelop.tgz``` (that redirects to ```https://www.touchdevelop.com/api/language/touchdevelop.tgz```) also errors out, with a cert error on raspian ('certificate is not yet valid'), and with an http error 500 when trying to download it with ```wget --no-check-certificate```.

**Comment by mmoskal** [comment]
@codespare - opened #328 to track this

**Comment by mmoskal** [comment]
All of these are now fixed.

**Comment by rubycoder** [comment]
There are other broken links:

https://www.touchdevelop.com/oauthv2
https://www.touchdevelop.com/webrequests
https://www.touchdevelop.com/exporttoapp

**Comment by rubycoder** [comment]
FYI - until these links get fixed, I'm using the copies in the Internet Archive.

You can start here:   https://web.archive.org/web/20150912023550/https://www.touchdevelop.com/docs/contents
Or here: 
https://web.archive.org/web/20150912084501/https://www.touchdevelop.com/docs/api

and follow the links on these pages to get to other pages in the archive.  So far the archive has contained all the pages I've needed.

**Comment by millerv** [comment]
Splitting these off into separate bugs per TD team's request.
