### ISSUE TITLE
CCGA Teacher login issue

### ISSUE THREAD

**Issue by PatPhillips1400** [Microsoft/TouchDevelop#326]
Message from a teacher in our CCGA training session:
"The students have only done a few tutorials in class. 
But I (teacher) may have created two accounts.  One using my microsoft log in (jolynne.hopkins@gmail.com) and another using "google" with my school email (jolynne.hopkins@ycs.wednet.edu). This may be part of my problem.  Everything we did in the training class is with my microsoft account.  I would like to keep that one.  Now when I log in with my microsoft account, it only shows the scripts I've looked at recently - not even the scripts I've written with my students.  It was only part of one but I don' t know what happened to it.  All my work from the workshop is gone.   It isn't a big deal .. as I can do it over.  But I do want to know what I did wrong to prevent the students from losing their work.  Especially when we get into writing script from scratch.  
If I have the students choose the option that says something like "I've been in before Nov 7" ... would that link their previous work?"

**Comment by mmoskal** [comment]
I don’t have account merging, I can only link a new auth method to an existing account.

This means the teacher can delete one of their accounts (and lose everything in it), try to log in again (with the auth method of the deleted account), and say they want to link accounts. From now on, both auth method will lead to the same account.

Any more info needed?
