### ISSUE TITLE
Another Teacher login issue

### ISSUE THREAD

**Issue by PatPhillips1400** [Microsoft/TouchDevelop#327]
Another teachers says:
"For some reason today, I cannot get logged into TouchDevelop!  I am trying to log in with my Microsoft account as I  always do and I keep getting an error:
I have tried everything that I can think of.  I have tried “Link other provider.” I have tried clearing out cookies for my browser.  I have tried rebooting my machine.  I can’t get in.  Who should I contact for assistance?" Here is the screen shot she sent... I'd really like to better understand what is happening so that I can intercept some of these problems on the first contact...
thanks,
Pat
![login problem](https://cloud.githubusercontent.com/assets/15836188/11151709/2a422c66-89f4-11e5-99b6-1e28311be7a3.png)

**Comment by mmoskal** [comment]
This should be resolved now. There was an issue with linking legacy accounts, and also it would prevent linking more than one authentication provider to a legacy account.

If they just go through that screen again, it shouldn't show up in the future.
