### ISSUE TITLE
touchdevelop.tgz missing

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#328]
From @codespare in #325 

The download link for the local install npm install -g http://aka.ms/touchdevelop.tgz (that redirects to https://www.touchdevelop.com/api/language/touchdevelop.tgz) also errors out, with a cert error on raspian ('certificate is not yet valid'), and with an http error 500 when trying to download it with wget --no-check-certificate.

**Comment by mmoskal** [comment]
@codespare - the certificate issue might have been temporary - we just got a new cert yesterday and it says "Valid from: Nov 12 2015 17:43" - don't know if it's UTC of Pacific. Should be fine now.

I'm going to fix the 500 soon.

**Comment by mmoskal** [comment]
This is now fixed. I have also added http://tdev.ly/td.tgz (and soon https://tdev.ly/td.tgz)

**Comment by codespare** [comment]
I am getting http error status 406 when running npm install -g http://aka.ms/touchdevelop.tgz, but downloading it first and installing it from the file system worked. Also, TouchDevelop.png 404's but that's minor. Thank you for your fast reply!

**Comment by PatPhillips1400** [comment]
THANK YOU, MICHAL (and team)!

Thank you very much for all of your extra efforts in helping the CCGA teachers get going again after their problems signing in, etc.

Much appreciated. 

Pat

**Comment by pelikhan** [comment]
Stil getting 406.

**Comment by mmoskal** [comment]
406 fixed now

**Comment by mmoskal** [comment]
```
[11:40 aa]$ npm install https://tdev.ly/td.tgz
touchdevelop@0.40.0 node_modules\touchdevelop
```
