### ISSUE TITLE
TD local not picking up in-app art

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#329]
When running TD in the local mode no art is able to be shown, displayed or used when running an app.

**Comment by mmoskal** [comment]
should be fixed now (with td local 0.41.0 and latest web app)

**Comment by ianapps** [comment]
Running beta 0.0.191.2167 in TD local (both for app# and latest#) doesn't appear to be fixed. Howe do I run 0.41.0?

**Comment by ianapps** [comment]
It is showing the art under the 'art' section within the app now.  However, when the app is run it is not using it you just have a white screen. Nor is the icon picture for the apps on the main screen being shown.
