### ISSUE TITLE
Issue with localized UI Collage tutorial Chinese 

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#333]
Repro steps:
go to https://www.touchdevelop.com/uqjke, start tutorial by click “tutorial” button and then you can see platform is in English + buttons, eg. “Let’s get started!” or “Let’s do it!” displays in English. Videos + CCs are displaying as properly localized.
These strings were already displayed as localized before the migration, happened so I am wondering if we can restore that status.

WatchMe.mp4 is affected by this problem and is actually blocked for CHS.

Thanks,
Ilaria

**Comment by pelikhan** [comment]
Please provide detailled repro for this.

**Comment by ilabar** [comment]
Launch the tutorial at the url above. See string "let's do it" in English to fix 
![image](https://cloud.githubusercontent.com/assets/15230722/11241207/91c540da-8df0-11e5-943c-5f3259e5ed8e.png)
