### ISSUE TITLE
CCGA: Block "Let's Get Started" and "Let's Do It" buttons until video is complete

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#335]
In Yammer CCGA Pioneer feedback, educators are seeing that some students just want to "get it done and over with" - so they skip the videos, follow the blue tutorial prompts, and have a working game/app - but don't understand the concepts they were supposed to be following.

One way to (hopefully) prevent a student from blowing through the tutorial and actually taking in what they need to learn is to hide the "let's get started" and "let's do it" buttons through some macro or other toggleable means for tutorial writers.  

This would also require hiding the video controls so they cannot skip over the content via that means either.

**Comment by pelikhan** [comment]
Also, entering faster in semi mode: https://github.com/Microsoft/TouchDevelop/commit/7a047b14f1f75f4ade585dfbc9ccf06cccf7f718
