### ISSUE TITLE
Word Truncation: TouchDevelop Documentatio <<  Docs

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#336]
Steps: 
IE or Microsoft Edge
https://www.touchdevelop.com/app/#list:topics:topic:tutorials:overview
Select any document on the left e.g. Content
Result: TouchDevelop Documentatio <<< is truncated

**Comment by pelikhan** [comment]
Screenshot?

**Comment by RickGMSR** [comment]
[cid:image001.png@01D12130.CEE424E0]

**Comment by RickGMSR** [comment]
![truncation](https://cloud.githubusercontent.com/assets/15837908/11223337/4fd78092-8d24-11e5-949a-1294ee841b88.png)

**Comment by millerv** [comment]
In checking around, this appears to be fixed - the account may have been renamed.

**Comment by RickGMSR** [comment]
Passed Regression: Touch Develop Docs
