### ISSUE TITLE
Touch Develop local doesn't work

### ISSUE THREAD

**Issue by grumpybee100** [Microsoft/TouchDevelop#340]
Although I have signed in a lot of times when prompted to, TD local still says that my access token has expired. Here's the screenshot:
![2015-11-18](https://cloud.githubusercontent.com/assets/14962312/11234659/25679770-8e05-11e5-889c-641b18842b07.png)

**Comment by grumpybee100** [comment]
It's in Beta 82122 sorry for the mix up in uservoice.

**Comment by millerv** [comment]
User Voice Links:
https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10773402-unable-to-install-touchdevelop-local
https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10721604-fix-touch-develop-local

**Comment by mmoskal** [comment]
@grumpybee100 In a couple minutes touchdevelop-0.41.0 should be available. Please install, run in new folder and see if it helps.

**Comment by grumpybee100** [comment]
Thanks!

**Comment by grumpybee100** [comment]
It works fine now, thanks so much!!😀😀
