### ISSUE TITLE
Website Issue: Bad Links

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#343]
Bad Links: Separated by Web Page. Each link below the web page represents each broken link

```
https://www.touchdevelop.com/
```
- [x]  a href=/help/cloudservices
- [ ]  a href=/scripts
  
  https://www.touchdevelop.com/home
- [ ]  a href=/help/cloudservices
- [ ]  a href=/scripts
  
  https://www.touchdevelop.com/app/
- [ ]  link href=manifest.json
  
  https://www.touchdevelop.com/app/?c
- [ ]  link href=manifest.json
  
  https://www.touchdevelop.com/app/beta
- [ ]  link href=manifest.json
  
  https://www.touchdevelop.com/docs/action-types
- [ ]  a href=/docs/action
  a href=/docs/textaction
  
  https://www.touchdevelop.com/docs/api
- [ ]  a href=/docs/action
- [ ]  a href=/docs/action1
- [ ]  a href=/docs/app
- [ ]  a href=/docs/appenv
- [ ]  a href=/docs/applogger
- [ ]  a href=/docs/appointment
- [ ]  a href=/docs/atomicaction
- [ ]  a href=/docs/atomicaction1
- [ ]  a href=/docs/bazaar
- [ ]  a href=/docs/bits
- [ ]  a href=/docs/bluetoothdevice
- [ ]  a href=/docs/booleanaction
- [ ]  a href=/docs/buffer
- [ ]  a href=/docs/cloudpicture
- [ ]  a href=/docs/cloudstorage
- [ ]  a href=/docs/collection
- [ ]  a href=/docs/collectionmessageaction
- [ ]  a href=/docs/collections
- [ ]  a href=/docs/color
- [ ]  a href=/docs/colors
- [ ]  a href=/docs/comparison
- [ ]  a href=/docs/contact
- [ ]  a href=/docs/contract
- [ ]  a href=/docs/converter
- [ ]  a href=/docs/create
- [ ]  a href=/docs/datetime
- [ ]  a href=/docs/docs
- [ ]  a href=/docs/document
- [ ]  a href=/docs/dom
- [ ]  a href=/docs/editor
- [ ]  a href=/docs/eventbinding
- [ ]  a href=/docs/formbuilder
- [ ]  a href=/docs/jsonaction
- [ ]  a href=/docs/jsonbuilder
- [ ]  a href=/docs/jsonobject
- [ ]  a href=/docs/languages
- [ ]  a href=/docs/link
- [ ]  a href=/docs/locations
- [ ]  a href=/docs/map
- [ ]  a href=/docs/mappushpin
- [ ]  a href=/docs/maps
- [ ]  a href=/docs/math
- [ ]  a href=/docs/matrix
- [ ]  a href=/docs/media
- [ ]  a href=/docs/message
- [ ]  a href=/docs/motion
- [ ]  a href=/docs/numberaction
- [ ]  a href=/docs/numberconverter
- [ ]  a href=/docs/numbermap
- [ ]  a href=/docs/oauthresponse
- [ ]  a href=/docs/obstacle
- [ ]  a href=/docs/page
- [ ]  a href=/docs/pagebutton
- [ ]  a href=/docs/phone
- [ ]  a href=/docs/picture
- [ ]  a href=/docs/picturealbum
- [ ]  a href=/docs/picturealbums
- [ ]  a href=/docs/pictures
- [ ]  a href=/docs/place
- [ ]  a href=/docs/player
- [ ]  a href=/docs/playlist
- [ ]  a href=/docs/playlists
- [ ]  a href=/docs/positionaction
- [ ]  a href=/docs/predicate
- [ ]  a href=/docs/radio
- [ ]  a href=/docs/serverrequest
- [ ]  a href=/docs/serverresponse
- [ ]  a href=/docs/social
- [ ]  a href=/docs/song
- [ ]  a href=/docs/songalbum
- [ ]  a href=/docs/songalbums
- [ ]  a href=/docs/songs
- [ ]  a href=/docs/sound
- [ ]  a href=/docs/spring
- [ ]  a href=/docs/sprite
- [ ]  a href=/docs/spriteaction
- [ ]  a href=/docs/spriteset
- [ ]  a href=/docs/spritesetaction
- [ ]  a href=/docs/stringconverter
- [ ]  a href=/docs/stringmap
- [ ]  a href=/docs/tags
- [ ]  a href=/docs/task
- [ ]  a href=/docs/textaction
- [ ]  a href=/docs/tile
- [ ]  a href=/docs/time
- [ ]  a href=/docs/timer
- [ ]  a href=/docs/tutorial
- [ ]  a href=/docs/unknown
- [ ]  a href=/docs/user
- [ ]  a href=/docs/vector3
- [ ]  a href=/docs/vectoraction
- [ ]  a href=/docs/wall
- [ ]  a href=/docs/web
- [ ]  a href=/docs/webeventsource
- [ ]  a href=/docs/webrequest
- [ ]  a href=/docs/webresponse
- [ ]  a href=/docs/webresponseaction
- [ ]  a href=/docs/websocket
- [ ]  a href=/docs/websocketmessage
- [ ]  a href=/docs/xmlobject
  
  https://www.touchdevelop.com/docs/app-day-workshops
- [ ]  a href=https://www.touchdevelop.com/docs/soundboard-tutorial
  
  https://www.touchdevelop.com/docs/app-javascript-async
- [ ]  a href=/docs/buffer
- [ ]  a href=/docs/jsonbuilder
- [ ]  a href=/docs/jsonobject
  
  https://www.touchdevelop.com/docs/art
- [ ]  a href=/docs/sound
- [ ]  a href=https://www.touchdevelop.com/docs/color
- [ ]  a href=https://www.touchdevelop.com/docs/picture
- [ ]  a href=https://www.touchdevelop.com/docs/sound
  
  https://www.touchdevelop.com/docs/async-actions
- [ ]  a href=/docs/task
- [ ]  a href=/docs/taskawait
- [ ]  a href=/docs/timesleep
- [ ]  a href=/docs/webdownload
  
  https://www.touchdevelop.com/docs/bazaar-ast-of
- [ ]  a href=/docs/jsonobject
- [ ]  a href=https://www.touchdevelop.com/help/cloudservices
  
  https://www.touchdevelop.com/docs/book
- [ ]  a href=https://www.touchdevelop.com/doc/book/book.pdf
- [ ]  a href=https://www.touchdevelop.com/doc/book/book1.epub
- [ ]  a href=https://www.touchdevelop.com/doc/book/book2.mobi
  
  https://www.touchdevelop.com/docs/box
- [ ]  a href=https://www.touchdevelop.com/docs/pages-and-boxes
- [ ]  a href=https://www.touchdevelop.com/docs/page
  
  https://www.touchdevelop.com/docs/boxed
- [ ]  a href=https://www.touchdevelop.com/docs/pages-and-boxes
  
  https://www.touchdevelop.com/docs/camera
- [ ]  a href=/docs/sensescamera
- [ ]  a href=/docs/sensesfrontcamera
- [ ]  a href=/docs/sensestakecamerapicture
  
  https://www.touchdevelop.com/docs/cloud-libraries
- [ ]  a href=https://www.touchdevelop.com/docs/jsonobject
  
  https://www.touchdevelop.com/docs/code
- [ ]  a href=https://www.touchdevelop.com/inline_actions
  
  https://www.touchdevelop.com/docs/commands
- [ ]  a href=https://www.touchdevelop.com/docs/math
- [ ]  a href=https://www.touchdevelop.com/docs/mathrandom
  
  https://www.touchdevelop.com/docs/cordova-library-guide
- [ ]  a href=/docs/appimport
- [ ]  a href=/docs/applogger
- [ ]  a href=/docs/jsonobject
  
  https://www.touchdevelop.com/docs/courses
- [ ]  a href=https://www.touchdevelop.com/doc/curriculum/touchdevelopcurriculum.pdf
  
  https://www.touchdevelop.com/docs/creating-interactive-tutorials
  a href=/docs/appimport
- [ ]  a href=/docs/colors
- [ ]  a href=/docs/colorsblue
- [ ]  a href=/docs/colorsrandom
- [ ]  a href=/docs/colorsred
- [ ]  a href=/docs/mathrandomrange
- [ ]  a href=/docs/tutorialstepcompleted
- [ ]  a href=https://www.touchdevelop.com/docs/scriptplugins
  
  https://www.touchdevelop.com/docs/dev-bootcamp
- [ ]  a href=/docs/pages
- [ ]  a href=https://www.touchdevelop.com//app/#list:showcase-scripts:script:oguva:code
- [ ]  a href=https://www.touchdevelop.com//app/#list:showcase-scripts:script:wbxsa:overview
- [ ]  a href=https://www.touchdevelop.com/docs/pages
- [ ]  a href=https://www.touchdevelop.com/docs/soundboard-tutorial
  
  https://www.touchdevelop.com/docs/events
- [ ]  a href=/docs/boardevolve
- [ ]  a href=/docs/boardupdateonwall
- [ ]  a href=/docs/sensesonphonefacedown
- [ ]  a href=/docs/sensesonphonefaceup
- [ ]  a href=/docs/sensesonphonelandscapeleft
- [ ]  a href=/docs/sensesonphonelandscaperight
- [ ]  a href=/docs/sensesonphoneportrait
- [ ]  a href=/docs/sensesonshake
- [ ]  a href=/docs/timeoneveryframe
- [ ]  a href=https://www.touchdevelop.com/docs/eventbinding
- [ ]  a href=https://www.touchdevelop.com/docs/sprite
- [ ]  a href=https://www.touchdevelop.com/docs/spriteset
  
  https://www.touchdevelop.com/docs/export-to-azure
- [ ]  a href=/docs/appimport
- [ ]  a href=/docs/appserversetting
  
  https://www.touchdevelop.com/docs/game-board
- [ ]  a href=/docs/boardat
- [ ]  a href=/docs/boardclearbackgroundcamera
- [ ]  a href=/docs/boardclearbackgroundpicture
- [ ]  a href=/docs/boardcount
- [ ]  a href=/docs/boardcreateanchor
- [ ]  a href=/docs/boardcreateellipse
- [ ]  a href=/docs/boardcreateobstacle
- [ ]  a href=/docs/boardcreatepicture
- [ ]  a href=/docs/boardcreaterectangle
- [ ]  a href=/docs/boardcreatespring
- [ ]  a href=/docs/boardcreatespriteset
- [ ]  a href=/docs/boardcreatetext
- [ ]  a href=/docs/boardevolve
- [ ]  a href=/docs/boardheight
- [ ]  a href=/docs/boardislandscape
- [ ]  a href=/docs/boardsetbackground
- [ ]  a href=/docs/boardsetbackgroundcamera
- [ ]  a href=/docs/boardsetbackgroundpicture
- [ ]  a href=/docs/boardsetfriction
- [ ]  a href=/docs/boardsetgravity
- [ ]  a href=/docs/boardwidth
- [ ]  a href=/docs/mediacreatelandscapeboard
- [ ]  a href=/docs/mediacreateportraitboard
- [ ]  a href=/docs/picture
- [ ]  a href=/docs/sprite
- [ ]  a href=/docs/spritecolor
- [ ]  a href=/docs/spriteheight
- [ ]  a href=/docs/spritehide
- [ ]  a href=/docs/spriteisvisible
- [ ]  a href=/docs/spriteopacity
- [ ]  a href=/docs/spritepicture
- [ ]  a href=/docs/spritesetclip
- [ ]  a href=/docs/spritesetcolor
- [ ]  a href=/docs/spritesetheight
- [ ]  a href=/docs/spritesetopacity
- [ ]  a href=/docs/spritesetpicture
- [ ]  a href=/docs/spritesettext
- [ ]  a href=/docs/spritesetwidth
- [ ]  a href=/docs/spritesetzindex
- [ ]  a href=/docs/spriteshow
- [ ]  a href=/docs/spritetext
- [ ]  a href=/docs/spritewidth
- [ ]  a href=/docs/spritezindex
- [ ]  a href=https://www.touchdevelop.com/docs/boardtouchcurrent
- [ ]  a href=https://www.touchdevelop.com/docs/boardtouched
- [ ]  a href=https://www.touchdevelop.com/docs/boardtouchend
- [ ]  a href=https://www.touchdevelop.com/docs/boardtouchstart
- [ ]  a href=https://www.touchdevelop.com/docs/boardtouchvelocity
- [ ]  a href=https://www.touchdevelop.com/docs/picture
- [ ]  a href=https://www.touchdevelop.com/docs/sprite
- [ ]  a href=https://www.touchdevelop.com/docs/spriteset
  
  https://www.touchdevelop.com/docs/gameloop
- [ ]  a href=/docs/boardupdateonwall
  
  https://www.touchdevelop.com/docs/gamepad
- [ ]  a href=/docs/sensesfirstgamepad
  
  https://www.touchdevelop.com/docs/hello-world
- [ ]  a href=https://www.touchdevelop.com/docs/pages
- [ ]  a href=https://www.touchdevelop.com/docs/wall
  
  https://www.touchdevelop.com/docs/hosted-apps
- [ ]  a href=/docs/appenvhashost
- [ ]  a href=/docs/apphostexec
  
  https://www.touchdevelop.com/docs/hour-of-code-educator-notes
- [ ]  a href=https://www.touchdevelop.com/doc/touchdevelophourofcodeposter.pdf
  
  https://www.touchdevelop.com/docs/how-to-search
- [ ]  a href=/docs/action
- [ ]  a href=/docs/bluetoothdevice
- [ ]  a href=/docs/mathrandom
  
  https://www.touchdevelop.com/docs/keyboard
- [ ]  a href=/docs/sensesiskeypressed
- [ ]  a href=/docs/sensesonkeypressed
  
  https://www.touchdevelop.com/docs/label-printer
- [ ]  a href=https://www.touchdevelop.com/doc/TouchDevelopLabelPrinter.zip
- [ ]  a href=https://www.touchdevelop.com/help/cloudservices
  
  https://www.touchdevelop.com/docs/language
- [ ]  a href=https://www.touchdevelop.com/docs/inline-actions
- [ ]  a href=https://www.touchdevelop.com/docs/pages
- [ ]  a href=https://www.touchdevelop.com/docs/wall
  
  https://www.touchdevelop.com/docs/leaderboards
- [ ]  a href=/docs/bazaarleaderboardscore
- [ ]  a href=/docs/bazaarpostleaderboardscore
  
  https://www.touchdevelop.com/docs/location
- [ ]  a href=/docs/languages
  
  https://www.touchdevelop.com/docs/markdown
- [ ]  a href=/docs/appimport
- [ ]  a href=/docs/bazaarcurrentuser
- [ ]  a href=/docs/bazaarleaderboardscore
- [ ]  a href=/docs/bazaarpostleaderboardscore
- [ ]  a href=/docs/bazaarpostleaderboardtowall
- [ ]  a href=/docs/bazaaruserof
- [ ]  a href=/docs/userid
- [ ]  a href=/docs/webcsv
  
  https://www.touchdevelop.com/docs/microphone
- [ ]  a href=/docs/sensesrecordmicrophone
- [ ]  
- [ ]  https://www.touchdevelop.com/docs/number
- [ ]  a href=/docs/mathfloor
- [ ]  a href=/docs/mathisnan
- [ ]  a href=/docs/mathround
  
  https://www.touchdevelop.com/docs/oauth-v2
- [ ]  a href=/docs/userid
- [ ]  a href=/docs/weboauthv2
- [ ]  a href=https://www.touchdevelop.com/<span class='md-error'>unknown macro &#X27;var&#X27; </span>/oauth
- [ ]  a href=https://www.touchdevelop.com/docs/jsonobject
- [ ]  a href=https://www.touchdevelop.com/docs/xmlobject
  
  https://www.touchdevelop.com/docs/office-mix-docs
- [ ]  a href=/docs/action
  
  https://www.touchdevelop.com/docs/parsing-data
- [ ]  a href=/docs/jsonobject
- [ ]  a href=/docs/webcsv
- [ ]  a href=/docs/webdownloadjson
- [ ]  a href=/docs/webjson
- [ ]  a href=/docs/webxml
- [ ]  a href=https://www.touchdevelop.com/docs/jsonobject
- [ ]  a href=https://www.touchdevelop.com/docs/message
- [ ]  a href=https://www.touchdevelop.com/docs/xmlobject
  
  https://www.touchdevelop.com/docs/persistent-data
- [ ]  a href=/docs/cloudpicture
- [ ]  a href=/docs/collection
- [ ]  a href=/docs/color
- [ ]  a href=/docs/datetime
- [ ]  a href=/docs/jsonobject
- [ ]  a href=/docs/link
- [ ]  a href=/docs/numbermap
- [ ]  a href=/docs/oauthresponse
- [ ]  a href=/docs/user
  
  https://www.touchdevelop.com/docs/plugins
- [ ]  a href=/docs/appcreatelogger
- [ ]  a href=/docs/applog
- [ ]  a href=/docs/editor
- [ ]  a href=/docs/editorannotateast
- [ ]  a href=/docs/editorprogress
- [ ]  a href=/docs/jsonobjecttojsonbuilder
- [ ]  a href=/docs/wallprompt
  
  https://www.touchdevelop.com/docs/records
- [ ]  a href=/docs/phone
- [ ]  a href=https://www.touchdevelop.com/docs/datetime
  
  https://www.touchdevelop.com/docs/scratch-reference
- [ ]  a href=/docs/stringat
- [ ]  a href=/docs/stringcount
- [ ]  a href=https://www.touchdevelop.com/docs/action
  
  https://www.touchdevelop.com/docs/senses
- [ ]  a href=https://www.touchdevelop.com/docs/sprite
- [ ]  a href=https://www.touchdevelop.com/docs/spriteset
  
  https://www.touchdevelop.com/docs/sensors-and-user-input
- [ ]  a href=https://www.touchdevelop.com/docs/pages-and-boxes
- [ ]  a href=https://www.touchdevelop.com/docs/sprite
- [ ]  a href=https://www.touchdevelop.com/docs/spriteset
  
  https://www.touchdevelop.com/docs/sprite-animation
- [ ]  a href=/docs/boardevolve
- [ ]  a href=/docs/spritecreateanimation
  
  https://www.touchdevelop.com/docs/sprite-sheet
- [ ]  a href=/docs/boardcreatespritesheet
- [ ]  a href=https://www.touchdevelop.com/docs/picture
  
  https://www.touchdevelop.com/docs/subscriptions
- [ ]  a href=https://www.touchdevelop.com/tags
- [ ]  a href=https://www.touchdevelop.com/user/settings
- [ ]  List of all users
- [ ]  Your own Subscriptions
- [ ]  Your latest subscriptions
- [ ]  Account Settings
  
  https://www.touchdevelop.com/docs/teach
- [ ]  a href=https://www.touchdevelop.com/teachwindowsphone
  
  https://www.touchdevelop.com/docs/testing
- [ ]  a href=/docs/contract
- [ ]  a href=/docs/contractassert
- [ ]  a href=/docs/contractrequires
- [ ]  a href=https://www.touchdevelop.com/docs/contract
  
  https://www.touchdevelop.com/docs/textbox
- [ ]  a href=https://www.touchdevelop.com/docs/pages-and-boxes
  
  https://www.touchdevelop.com/docs/user-input
- [ ]  a href=/docs/wall
- [ ]  a href=/docs/wallpickstring
- [ ]  a href=https://www.touchdevelop.com/docs/datetime
- [ ]  a href=https://www.touchdevelop.com/docs/page
- [ ]  a href=https://www.touchdevelop.com/docs/stringcollection
- [ ]  a href=https://www.touchdevelop.com/docs/stringcollectionat
  
  https://www.touchdevelop.com/docs/user-score
- [ ]  a href=https://www.touchdevelop.com/features
  
  https://www.touchdevelop.com/docs/web-requests
- [ ]  a href=/docs/webcreaterequest
- [ ]  a href=/docs/webxml
- [ ]  a href=https://www.touchdevelop.com/docs/formbuilder
- [ ]  a href=https://www.touchdevelop.com/docs/jsonbuilder
- [ ]  a href=https://www.touchdevelop.com/docs/picture
- [ ]  a href=https://www.touchdevelop.com/docs/web
- [ ]  a href=https://www.touchdevelop.com/docs/webrequest
- [ ]  a href=https://www.touchdevelop.com/docs/webresponse
  
  https://www.touchdevelop.com/docs/welcome-to-the-community-blog
- [ ]  a href=https://www.touchdevelop.com/blog/rss
  
  https://www.touchdevelop.com/docs/what-s-new
- [ ]  a href=/docs/appcreatelogger
- [ ]  a href=/docs/appeditor
- [ ]  a href=/docs/appimport
- [ ]  a href=/docs/applog
- [ ]  a href=/docs/apprestart
- [ ]  a href=/docs/boardcreateobstacle
- [ ]  a href=/docs/boxaddbackgroundpicture
- [ ]  a href=/docs/bufferconcat
- [ ]  a href=/docs/bufferreadnumber
- [ ]  a href=/docs/bufferwritenumber
- [ ]  a href=/docs/cloudpicture
- [ ]  a href=/docs/collectionmapto
- [ ]  a href=/docs/collectionorderedby
- [ ]  a href=/docs/collectionorderedbystring
- [ ]  a href=/docs/collectionslice
- [ ]  a href=/docs/collectionsorted
- [ ]  a href=/docs/collectiontake
- [ ]  a href=/docs/datetimemillisecondssinceepoch
- [ ]  a href=/docs/mathdiv
- [ ]  a href=/docs/playeronactivesongchanged
- [ ]  a href=/docs/playeronplayerstatechanged
- [ ]  a href=/docs/sensesonphonefacedown
- [ ]  a href=/docs/sensesonphonefaceup
- [ ]  a href=/docs/sensesonphonelandscapeleft
- [ ]  a href=/docs/sensesonphonelandscaperight
- [ ]  a href=/docs/sensesonphoneportrait
- [ ]  a href=/docs/sensesonshake
- [ ]  a href=/docs/sensesrecordmicrophone
- [ ]  a href=/docs/spritebottom
- [ ]  a href=/docs/spritefittext
- [ ]  a href=/docs/spriteleft
- [ ]  a href=/docs/spriteright
- [ ]  a href=/docs/spritetop
- [ ]  a href=/docs/task
- [ ]  a href=/docs/taskawaitatmost
- [ ]  a href=/docs/taskcompleted
- [ ]  a href=/docs/taskvalue
- [ ]  a href=/docs/timeoneveryframe
- [ ]  a href=/docs/timerunafter
- [ ]  a href=/docs/timerunevery
- [ ]  a href=/docs/webdecodeuri
- [ ]  a href=/docs/webdecodeuricomponent
- [ ]  a href=/docs/webencodeuri
- [ ]  a href=/docs/webencodeuricomponent
- [ ]  a href=https://www.touchdevelop.com/docs/obstacle
- [ ]  a href=https://www.touchdevelop.com/docs/page
  
  https://www.touchdevelop.com/docs/what-s-new-2013
- [ ]  a href=/docs/bits
- [ ]  a href=/docs/buffer
- [ ]  a href=/docs/bufferclone
- [ ]  a href=/docs/buffercopyfrom
- [ ]  a href=/docs/bufferfill
- [ ]  a href=/docs/bufferfillrandom
- [ ]  a href=/docs/buffersubbuffer
- [ ]  a href=/docs/colortohtml
- [ ]  a href=/docs/jsonbuilder
- [ ]  a href=/docs/jsonobjectserialize
- [ ]  a href=/docs/jsonobjecttojsonbuilder
- [ ]  a href=/docs/picture
- [ ]  a href=/docs/picturetodatauri
- [ ]  a href=/docs/wallheight
- [ ]  a href=/docs/wallpoppagewithtransition
- [ ]  a href=/docs/wallwidth
- [ ]  a href=https://www.touchdevelop.com/docs/pages
- [ ]  a href=https://www.touchdevelop.com/inline_actions
- [ ]  a href=https://www.touchdevelop.com/OAuth_V2

**Comment by mmoskal** [comment]
@RickGMSR could you run the link checker again? I think most of these should be resolved now.

**Comment by millerv** [comment]
User voice posts: 
https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10921683-please-update-the-links-on-the-documentation-pages
https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10913358-the-documentation-pages-are-coming-up-as-not-found

**Comment by pelikhan** [comment]
Could you open individual issues for links raised by users? This issue contains 300 missing links and it is not prioritized.
