### ISSUE TITLE
Turtle maze: need "on collision" and "on goal" actions

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#35]
In older versions of the turtle library, when creating a maze it was possible to set the behavior on collisions with obstacles and on reaching the goal. Those actions/behaviors don't seem to work in recent version of the library. An example is here: http://tdev.ly/gkvkg

In the context of a maze, having a **turtle->on collision** action and a **turtle->on goal** action (or **on goal reached** or **on goal attained** or something like that) is necessary to make mazes good teaching tools.

**Comment by pelikhan** [comment]
You must call ``maze->lock`` after your setup code so that the checking starts running. When all goals are reached, tutorial->step completed gets called automatically.

**Comment by brian-swan** [comment]
Thanks. There still seems to be a problem with this tutorial: http://tdev.ly/ilah. Somehow, the initial position of the turtle overlaps with an obstacle, despite code that explicitly sets the position in a "safe" location.

**Comment by pelikhan** [comment]
Watch out for corners, obstacle detection is done on the bounding box. Turning on the debug mode on the board might help show this behavior. Agreed, it's not great.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Feb 23, 2015 at 9:00 PM -0800, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. There still seems to be a problem with this tutorial: http://tdev.ly/ilah. Somehow, the initial position of the turtle overlaps with an obstacle, despite code that explicitly sets the position in a "safe" location.

-

**Comment by brian-swan** [comment]
This particular case isn’t because of corners. Somehow, the initial placement of the turtle at a “safe” position is being ignored when the script is run.
