### ISSUE TITLE
TD Local - Error - Export Not Allowed

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#351]
When attempting to export a app using Cordova, the following error is shown "Export not allowed We're sorry, one or more authors from the base script have disallowed the export of this script.

In the 3 instances I tried, I was the base authors and only author of all instances in-between the original base and the current version.  No libraries were used.

**Comment by rubycoder** [comment]
I'm getting exactly the same error message in a case where I'm the base author and the author of all instances, and I'm using some standard libraries: game, game animations, gamepad

**Comment by ianapps** [comment]
Tested this with a newly created, very simple test script. Still the same issue in that an unknown, impossible base author had magically denied me publishing it even though I had just created the script, there was only one instance of this script in the history.

**Comment by pelikhan** [comment]
This API has not been reimplemented yet. We will be looking at this next week.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Nov 28, 2015 at 5:51 AM -0800, "ianapps" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested this with a newly created, very simple test script. Still the same issue in that an unknown, impossible base author had magically denied me publishing it even though I had just created the script, there was only one instance of this script in the history.

-

**Comment by pelikhan** [comment]
SHould be fixed with https://github.com/Microsoft/TouchDevelop/commit/5534f836ecbc6992dec042462dcf68c7ac65115b

**Comment by millerv** [comment]
Rick - could you verify for me?

**Comment by ianapps** [comment]
You can now start the export to cordova process.  However, there are many errors and it eventually stops working when trying to add plugins.

**Comment by pelikhan** [comment]
Try again, should be fixed.
