### ISSUE TITLE
Email Verification is not being sent

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#352]
Win 10, Microsoft Edge
https://www.touchdevelop.com/app/#list:installed-scripts:user:ajsn:overview
Enter Appropriate Email and Save
Wait to receive email (Waited over 4 hours)
Result: No email verification received. Checked Junk mail and nothing.
Expected: Email verification should be send upon Save when first registering or when changing email

**Comment by RickGMSR** [comment]
Same issue reported in Forum. Blocking people from creating groups until email verification has taken place

**Comment by grumpybee100** [comment]
Hi, have you tried to check for the mail in your Junk or Spam folder? It might be there, it's just that outlook or google mail doesn't recognize the sender of the email. Try finding the mail there. The sender's name would be "noreply@microbit.uk". See if this helps out

**Comment by grumpybee100** [comment]
Oh sry looks like you've checked them. I don't know what's the issue now

**Comment by mmoskal** [comment]
This should be fixed now - no email verification required for groups. I'll try to fix the email verification itself later.

**Comment by grumpybee100** [comment]
Thanks!😄😄😄

**Comment by RickGMSR** [comment]
Verified: Will close bug once email fix is in
