### ISSUE TITLE
Several Phone Models: Touch Develop no longer compatible for development

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#353]
Prolific users/creators on Touch Develop have found that they are unable to continue development on Touch Develop with the following devices:

*Lumia 920
*Lumia 640

Please re-enable Touch Develop development access via these devices - thanks!

**Comment by millerv** [comment]
User Voice link:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10808625-fix-the-compatibility-with-lumia-920-please

**Comment by RickGMSR** [comment]
It seems that this issue is affecting all Windows Phone.

**Comment by RickGMSR** [comment]
I have tracked more details about the issue. If you have Windows 8.0/8.1 Phone edition, IE is not able to load TouchDevelop.com/app
I tried the same test on my Windows 10 Phone (Edge) and the website loaded correctly.

**Comment by tballmsft** [comment]
Same here - TD doesn't get past load screen anymore on WP 8.1.
