### ISSUE TITLE
Missing Controls while running through Tutorial

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#354]
Windows 10, Edge Browser
URL: http://aka.ms/CollageTutorial
Proceed to the part where you search for art (Robot)
After you pick the art, the tutorial states to click Run but Run is not visible
![snip-missing-run](https://cloud.githubusercontent.com/assets/15837908/11384461/e1ea3ccc-92c4-11e5-9088-1d865eb9e493.png)
If you click on the empty space where Run should be, then the controls are displayed

Expected: The Run button should be visible

Note: I suspect that this behavior can be duplicated by just searching when the "Search control is on the top left side of the screen"

**Comment by RickGMSR** [comment]
![click-empty-space](https://cloud.githubusercontent.com/assets/15837908/11384583/ce53c2ea-92c5-11e5-8910-75a681167dbd.png)
Adding picture that shows after click on empty space, then controls Run, Undo and Split finally display

**Comment by millerv** [comment]
Tracking this via:  https://github.com/Microsoft/TouchDevelop/issues/290

**Comment by millerv** [comment]
This has since been fixed via other work.

**Comment by RickGMSR** [comment]
Passed Regression Test
