### ISSUE TITLE
Build Error in Cordova : Cannot POST

### ISSUE THREAD

**Issue by grumpybee100** [Microsoft/TouchDevelop#355]
This line of code appeared in cmd when I tried building my app in cordova:

npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.

Any ideas?

**Comment by grumpybee100** [comment]
Sorry, there's a new issue after that. I realized that issue was caused when I checked the android option in the build dialog. Here are the screenshots of what happened when I just tried to build it for windows:

![2015-11-25 1](https://cloud.githubusercontent.com/assets/14962312/11394059/009e5aa2-939e-11e5-9820-8134cce4a1fd.png)
![2015-11-25 2](https://cloud.githubusercontent.com/assets/14962312/11394060/009f4dea-939e-11e5-8e25-f51d58bc96e3.png)

**Comment by grumpybee100** [comment]
This happened a lot of times already, and I just tried it again a few minutes ago.

**Comment by pelikhan** [comment]
Try again.
