### ISSUE TITLE
Users cannot export to HTML5

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#358]
Details sparse, but a User Voice post mentions that they are unable to export their project to HTML 5:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10891512-exporting-html5-doesn-t-work

**Comment by millerv** [comment]
Could you verify this for me?

**Comment by RickGMSR** [comment]
Passed Testing: 12/4/15
