### ISSUE TITLE
Microsoft Edge: Close Caption on tutorial videos do not show

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#362]
Windows 10, Edge Browser
http://aka.ms/flatverse
Select English CC
Play the Tutorial
Result: CC fail to show

**Comment by millerv** [comment]
TFS issue 43127 - all tutorials with embedded video show this issue.

**Comment by millerv** [comment]
I've been in email discussions with some Microsoft Edge team members, they were able to reproduce the "no captions" in Edge issues we've been seeing.

Per Jerry Smith's last email:
"I’ve confirmed that your captions work on Edge/14.  It’s in a Windows release that ships mid-year."

**Comment by RickGMSR** [comment]
Closing - Edge Issue
