### ISSUE TITLE
CCGA: Documentation: Need pages-and-boxes documentation

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#363]
We've gotten multiple requests to restore this page:  
https://www.touchdevelop.com/docs/pages-and-boxes

Users and educators alike are looking for this information when they work on creating apps on Touch Develop.

**Comment by millerv** [comment]
Also reported in #325 - closing that and splitting the reported issues into individual high priority requests.

**Comment by PatPhillips1400** [comment]
This topic is included in unit 10, so it might be important to students also.

**Comment by millerv** [comment]
This is working now, closing bug.
