### ISSUE TITLE
cordova: Media support in iOS broken

### ISSUE THREAD

**Issue by samuelsavio** [Microsoft/TouchDevelop#37]
![problem](https://cloud.githubusercontent.com/assets/10967869/6195496/fb93544a-b3ce-11e4-8f62-0e7165dce5da.jpg)
![touchdeve](https://cloud.githubusercontent.com/assets/10967869/6195502/04ae41e8-b3cf-11e4-83cc-568e56ed0282.jpg)
after run cordova export iOS

**Comment by pelikhan** [comment]
The images show as broken links?

**Comment by samuelsavio** [comment]
ok now images is visible

**Comment by samuelsavio** [comment]
report xcode
![errorxcode](https://cloud.githubusercontent.com/assets/10967869/6203364/5be02fd0-b51e-11e4-92b8-964e053a7d36.jpg)
