### ISSUE TITLE
Export to Azure "Payload too large" error

### ISSUE THREAD

**Issue by jdgg1993** [Microsoft/TouchDevelop#371]
Using my DreamSpark account I've created a web app, downloaded the publish settings, then use that to export my app from touch develop. However, no matter what I do I always get a "Payload too large" error, even on blank apps. I've tried making a web app with Node.js but had no luck.

**Comment by pelikhan** [comment]
Could you please publish the script id that creates the issue?

**Comment by jdgg1993** [comment]
First I tried publishing a completed project to azure (ID: /bdgfxjnntv) which was when I first encountered the "Payload too large" error so I created an empty project and tried publishing that (ID: /jabqysmmrb) but still no luck.

**Comment by ticup** [comment]
Having same issue here with a freshly created azure account, free trail and a blank app.
It also gives the following during creation of the new app: 
<Code>BadRequest</Code><Message>The location constraint is not valid</Message>

**Comment by ticup** [comment]
These are the errors: https://goo.gl/photos/mswXCiWKTiY9YiHH6
Location error is generated upon creation of azure app, the HTTP 413 error is received from the azure app when trying to export to it.

It must be a new configuration setting from the azure apps that have their request body limit lowered?

**Comment by randguth** [comment]
I have the same problem. In the past (last September) switching browsers to Chrome; but now it is pervasive using every browser and OS (Mac, Win 10, Chrome, Edge, IE, Safari)
