### ISSUE TITLE
CCGA/Yammer: Students unable to use their uploaded .wav sound files

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#377]
Reported on Yammer:
https://www.yammer.com/microsoftteachers/#/Threads/show?threadId=624283878

As reported on Yammer, students who are trying to upload and use their uploaded .wav sound files are seeing "invalid value" errors.

Sample script:  https://www.touchdevelop.com/dmadeortqv

**Comment by RickGMSR** [comment]
I have confirmed this bug. New uploaded sounds cause error when used.
The sound shows in the available art but cause error when you run the program

**Comment by mmoskal** [comment]
This should be fixed now, but they have to upload the files again as mp3. WAV is no longer supported. It would be good if people deleted any wav stuff they have uploaded recently.

**Comment by mmoskal** [comment]
Please test on /app/latest and close.

**Comment by RickGMSR** [comment]
We need to modify the upload sound page. Currently it says: Choose a WAV sound.

**Comment by RickGMSR** [comment]
Passed Regression Testing: Page now says MP3
