### ISSUE TITLE
Introduce delay between tutorial steps

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#38]
Students following a tutorial need to be able to contemplate the code they have written. Right now, students can do this *only* if they are prompted to run the code after a tutorial step (they can examine the code before tapping "run"). However, it is not always desirable to have students run code after a tutorial step. In this case, instructions for the next step are immediately shown without giving a student opportunity to examine what he/she just wrote.

Some options that would be helpful (least-good to best):
- a built-in delay of a few seconds between all tutorial steps
- a macro that allowed a configurable delay between steps
- a macro that provided a way to pop a "continue to next step" button between steps

**Comment by pelikhan** [comment]
duplicated of #10
