### ISSUE TITLE
Mispelling: build\editor.js

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#383]
1. TDev.Util.log("about to resetstate");
2. TDev.ModalDialog.info(TDev.lf("sorry, no can do"), TDev.lf("'else' of the preceeding 'if' must be empty"));
3. logs.push(TDev.RT.App.createInfoMessage('--- error while retreiving web site logs ---'));
4. TDev.Util.check(false, TDev.lf("failed to retreive scripts"));
5.  TDev.HTML.showProgressNotification(TDev.lf("requesting new invitiation code..."));
6.  TDev.HTML.showProgressNotification(TDev.lf("clearing invitiation code..."));
7. marvelous
8. TDev.Util.log('failed to retreive progress info');
9. 229 /* sideAddResource */, description: TDev.lf("Embeded
10. _this.imgInfo.setChildren([TDev.lf("Ooops, there was an error
11. statusMsg("page loaded, initalizing");

**Comment by millerv** [comment]
Looks like "marvelous" is actually ok, the rest have been updated in the .ts files that get compiled into .js files.

**Comment by RickGMSR** [comment]
Checked Diff - All good
