### ISSUE TITLE
Page Missing Videos: https://www.touchdevelop.com/docs/debugging

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#386]
Tried on both Edge and IE
Go to Page: https://www.touchdevelop.com/docs/debugging
Scroll to: show me the videos!
•a quick step-by-step tutorial
Result: Videos are just pictures instead of actual videos
Looks like the hooks need fixing.

**Comment by millerv** [comment]
Michal got a fix in on the backend for this:  https://github.com/Microsoft/TouchDevelop-backend/commit/50805406223e198030b85858abde2b682a7062ac  Should be live on that page now.

**Comment by RickGMSR** [comment]
Passed Regression Test
