### ISSUE TITLE
Tutorials: Users cannot publish tutorials

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#387]
User Voice:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/11043630-i-noticed-the-publishing-of-tutorial-has-been-bloc

Users are currently trying to publish their own tutorials using the tutorial plugin, but cannot - has the method changed or is this a new issue?

**Comment by millerv** [comment]
Rick - mind trying to reproduce this?  Any details you can fill in for this user scenario would be helpful.

**Comment by esiauwid** [comment]
Here is the detail recording:
https://mix.office.com/watch/1smr3nqycsakx

Put attention around 1:24 - network issue. However, the syncing is always working, which is very strange.

**Comment by RickGMSR** [comment]
I have executed the same scenario locally and it worked fine. Must be related to a network issue. Recommend to try another system, try wired connection or run TD locally.

**Comment by millerv** [comment]
Michal - taking a look at the Office Mix recording, his script publishes eventually, but it's showing that network error message.  Know what's possibly going on?

**Comment by esiauwid** [comment]
Hi Rick,

The interesting part is that the syncing worked. So we need to know what's the step after syncing.

I tried this on a super fast university network where touchdevelop loads instantly. The problem still exists.

The other functions worked so something very specific to this. I have downloaded the codes, I am not sure where to look, unless somebody can point me to the right direction.

Is there any debugging info that I can supply?

If we want to make touchdevelop available outside US, we need to address this issue.

Cheers,

Eddy



Sent from my Windows Phone
________________________________

**Comment by esiauwid** [comment]
Hi,

I had to break it as it was doing infinite loop.

I have used this for the last 9 months. This used to publish immediately.

Cheers,

Eddy


Sent from my Windows Phone
________________________________

**Comment by pelikhan** [comment]
The connectivity issue might be something. You would need to pop up the JavaScript window and see the console to see what happens.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Fri, Dec 11, 2015 at 5:33 PM -0800, "esiauwid" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Rick,

The interesting part is that the syncing worked. So we need to know what's the step after syncing.

I tried this on a super fast university network where touchdevelop loads instantly. The problem still exists.

The other functions worked so something very specific to this. I have downloaded the codes, I am not sure where to look, unless somebody can point me to the right direction.

Is there any debugging info that I can supply?

If we want to make touchdevelop available outside US, we need to address this issue.

Cheers,

Eddy



Sent from my Windows Phone
________________________________
