### ISSUE TITLE
Upload Sound Page: Need to modify requirements P1

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#389]
Currently, if you go to upload a file you are prompted to choose a WAV file. 
Only MP3 are supported so the page is invalid.
We should fix this soon as wav files don't work and cause script to crash

Steps:
New Script
+ Add new 
Sound Resource
Click Upload Button
---Choose WAV

**Comment by RickGMSR** [comment]
Also, don't forget to modify Choose File to upload (Filter to include only MP3 Files)
Currently WAV, Pictures, All (*.*) and HTML

**Comment by millerv** [comment]
See this commit for details:  https://github.com/Microsoft/TouchDevelop/commit/3f95b465cb0f55bed34d6fee8bcda1d589325e9f

**Comment by millerv** [comment]
This appears to be fixed in current versions of Touch Develop.  I've also updated the corresponding text in Docs:  https://www.touchdevelop.com/docs/art

**Comment by RickGMSR** [comment]
Passed Regression
