### ISSUE TITLE
Tutorials: images found on search for sound

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#39]
When a user needs to supply a sound resource in a tutorial, images come up in the search (see screen shot). If a user selects an image, he/she will get an error when trying to ->play it.
Example in this tutorial: http://tdev.ly/ozsfa
![sound-image](https://cloud.githubusercontent.com/assets/918682/6197451/48ab4cc2-b39a-11e4-8bc1-d2ef9b253e0f.PNG)

**Comment by pelikhan** [comment]
the workaround is to name your variable "sound ...". there is a filter that trigger in that case and only returns sounds. Will that work?
