### ISSUE TITLE
stmtParticipants should not be created when collaboration is not turned on.

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#40]
I noticedd a bunch of empty nodes to display the participants heads. Do we need to create those when collab is not enabled?

**Comment by msprotz** [comment]
Yes. Is that a problem?

**Comment by pelikhan** [comment]
In most cases, users are not using collab so I don't see why we need those nodes. Not a big deal.

Sent from my iPhone

On Feb 13, 2015, at 5:19 PM, Jonathan Protzenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. Is that a problem?

-

**Comment by msprotz** [comment]
I need to check whether, by the time `editor/render.ts` executes, we already know if there's a collaboration or not. The editor initialization sequence is tricky, and asynchronous.
