### ISSUE TITLE
localized Flatverse tutorial: strings not found

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#400]
Hi,
we could not translate the strings in the xls attached (8 strings that we shoud translate in 9 languages).
[49954-Flatverse_TD_Failed_import.xlsx](https://github.com/Microsoft/TouchDevelop/files/61039/49954-Flatverse_TD_Failed_import.xlsx)
![add score](https://cloud.githubusercontent.com/assets/15230722/11778188/d44bec10-a24a-11e5-822e-b2f2c8338a8b.png)
![bounce on sides](https://cloud.githubusercontent.com/assets/15230722/11778191/d83c1b6a-a24a-11e5-92d7-a2f102ff0236.png)
![data](https://cloud.githubusercontent.com/assets/15230722/11778196/dced08b8-a24a-11e5-9cfb-d60081ddc1aa.png)
![game](https://cloud.githubusercontent.com/assets/15230722/11778198/de4b3446-a24a-11e5-91c6-5f7e8baee19c.png)
![landing_page](https://cloud.githubusercontent.com/assets/15230722/11778203/e502fe72-a24a-11e5-8f6c-419a4a9ed260.png)
![random range](https://cloud.githubusercontent.com/assets/15230722/11778205/e61bb0d8-a24a-11e5-864e-a9a9b3db59d5.png)
![remove life](https://cloud.githubusercontent.com/assets/15230722/11778210/e974bc0c-a24a-11e5-928f-b2253b5f7fa7.png)
![set life](https://cloud.githubusercontent.com/assets/15230722/11778212/edcabb12-a24a-11e5-8956-196f6cb6536c.png)
![type_changing sprite](https://cloud.githubusercontent.com/assets/15230722/11778216/f1cd8fbe-a24a-11e5-9cf7-38fdde94324f.png)

**Comment by millerv** [comment]
Peli - It looks like I can fix everything *except* anything that deals with the Game API documentation.  I have no means of hooking in localizable versions of the strings that I can see.  So when it comes to a line like "sets the current life points" - I cannot fix it at this moment.

**Comment by ilabar** [comment]
Hi Valerie, Peli,
here the same set of strings (fix nice to have, not mandatory) for other 10 languages we have released.

Thanks,
Ilaria


[49954-Flatverse_TD_Failed_import.xlsx](https://github.com/Microsoft/TouchDevelop/files/66735/49954-Flatverse_TD_Failed_import.xlsx)
![add score](https://cloud.githubusercontent.com/assets/15230722/11899656/99cc6d70-a598-11e5-9544-84baf6809798.png)
![bounce on sides](https://cloud.githubusercontent.com/assets/15230722/11899657/99cce28c-a598-11e5-9735-79628d9e3439.png)
![data](https://cloud.githubusercontent.com/assets/15230722/11899655/99cc3efe-a598-11e5-9184-41ee839bd9af.png)
![game](https://cloud.githubusercontent.com/assets/15230722/11899658/99ccef5c-a598-11e5-9061-254ae2e05dcc.png)
![landing_page](https://cloud.githubusercontent.com/assets/15230722/11899659/99cd3016-a598-11e5-8f78-965f157855d7.png)
![random range](https://cloud.githubusercontent.com/assets/15230722/11899660/99ce5496-a598-11e5-92ca-034c5fa5164e.png)
![remove life](https://cloud.githubusercontent.com/assets/15230722/11899663/99e2fad6-a598-11e5-8bda-5110e4e11d9a.png)
![set life](https://cloud.githubusercontent.com/assets/15230722/11899662/99e1cbde-a598-11e5-8ede-d70c9fe0befa.png)
![type_changing sprite](https://cloud.githubusercontent.com/assets/15230722/11899661/99df5002-a598-11e5-896a-2cfac04f54a4.png)

**Comment by ilabar** [comment]
Hi Peli, Valerie,
some strings nice to have imported in the new 10 languages.
![add score](https://cloud.githubusercontent.com/assets/15230722/11899691/c0dda60e-a598-11e5-9e58-e45260d82c07.png)
![bounce on sides](https://cloud.githubusercontent.com/assets/15230722/11899689/c0dca1be-a598-11e5-82d3-8b10a235bbec.png)
![data](https://cloud.githubusercontent.com/assets/15230722/11899692/c0de6c06-a598-11e5-83ad-90d6b5247640.png)
![game](https://cloud.githubusercontent.com/assets/15230722/11899690/c0dca0b0-a598-11e5-815d-d04a1713a8e4.png)
![landing_page](https://cloud.githubusercontent.com/assets/15230722/11899693/c0e0b330-a598-11e5-9607-642aa7138867.png)
![random range](https://cloud.githubusercontent.com/assets/15230722/11899694/c0e5cdfc-a598-11e5-836c-c2695c6af581.png)
![remove life](https://cloud.githubusercontent.com/assets/15230722/11899695/c0eef4fe-a598-11e5-9ae8-555ee7e52a0c.png)
![set life](https://cloud.githubusercontent.com/assets/15230722/11899696/c0f1dfac-a598-11e5-9cce-b1373a395b9b.png)
![type_changing sprite](https://cloud.githubusercontent.com/assets/15230722/11899697/c0f2af9a-a598-11e5-8568-35b8a5d433dc.png)
[49954-Flatverse_TD_Failed_import.xlsx](https://github.com/Microsoft/TouchDevelop/files/66737/49954-Flatverse_TD_Failed_import.xlsx)

**Comment by millerv** [comment]
Looks like Game library strings are available for localization now, assigning to myself for tracking.
