### ISSUE TITLE
FAQ - Docs needs updating: https://www.touchdevelop.com/docs/faq

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#403]
Should be removed
1. For the Windows Phone, you can download the TouchDevelop app from the Windows Phone Store.
2. what about the Touch Develop Windows Phone app
The Touch Develop Windows Phone app was the first to launch in April 2011. The Touch Develop Web App Preview was launched in October 2012. Certain sensors and data providers that can be used in the Touch Develop Windows Phone app and generated Windows 8 apps are not accessible on the web due to browser restrictions.

Modify to add User Voice
how do I report bugs or contact the Touch Develop team?

One of the best ways to report issues is to go to our GitHub page and log your bug or feature request with screenshots or a link to the particular script experiencing issues. The more information and context you can provide, the better the chances of us pinpointing the issue and fixing it!

**Comment by millerv** [comment]
Updated per recommendations in bug.

**Comment by RickGMSR** [comment]
Passed Regression Test
