### ISSUE TITLE
Tables in exported Cordova scripts do not store data locally.

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#407]
Tables do not store data locally.  They are cleared each time the app is run. This used to work but doesn't now since the backend  migration began in November.

**Comment by millerv** [comment]
User Voice Link:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/11285589-fix-tables-in-exported-cordova-apps-they-only-st

This may also effect tutorials that use tables as part of the tutorial's lesson.

**Comment by ianapps** [comment]
When do you estimate this one will be fixed?

**Comment by ianapps** [comment]
When running the app within the touch develop environment it stores data in the cloud between sessions.  It's just when it is exported as a Cordova Script that is doesn't store data locally between runs.

**Comment by millerv** [comment]
@pelikhan - if you have a chance, could you take a look at this one?

**Comment by ianapps** [comment]
So if the app stores and can access the data while it is running, but can't between sessions it implies that whatever command allows the exported app to store data locally is either incorrect of missing - but where is it ....

**Comment by ianapps** [comment]
The exported 'index.html' is causing this issue:

DELETE:
var webAppImplicit = true;

CHANGE:
<script type="text/javascript">TDev.Browser.check(true, "Touch Develop", "https://www.touchdevelop.com/app/");
</script>
to
<script type="text/javascript">TDev.Browser.check(true);

**Comment by ianapps** [comment]
Amending my last comment, just DELETE: var webAppImplicit = true; in index.html to fix this issue

**Comment by ianapps** [comment]
See my last comment to resolve this issue.
