### ISSUE TITLE
Need to restore Docs search feature

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#413]
Educators who are trying to find specific information to help their students want to search the Docs with a search bar.  Before the backend change, the contents/docs pages used to have a search bar available in the same area as the green "subscribe now" button.

Requesting that we restore this feature for teachers and students.

![nosearchpresent](https://cloud.githubusercontent.com/assets/2482509/12184483/5453abde-b54a-11e5-8432-292c3b60b005.PNG)

**Comment by mmoskal** [comment]
Added back.

**Comment by millerv** [comment]
Looks like it's working - closing bug as fixed and notifying teachers who asked about it.
