### ISSUE TITLE
Issues Report with localized CCGA ARA

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#415]
[Bug_Report-ARA.xlsx](https://github.com/Microsoft/TouchDevelop/files/85593/Bug_Report-ARA.xlsx)
[ARA_images.zip](https://github.com/Microsoft/TouchDevelop/files/85594/ARA_images.zip)

**Comment by millerv** [comment]
Ok, updated and fixed the missing poster and missing caption issues, the other issues are tracked in bugs #284 and #285 - if the poster and caption look ok during your testing, you can close this bug.  Just add notes to #284 and #285 that this is showing in Arabic CCGA as well.

**Comment by millerv** [comment]
Closing as fixed per email discussion with loc team.
