### ISSUE TITLE
Issues Report with localized CCGA CHS

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#416]
[CHS_images.zip](https://github.com/Microsoft/TouchDevelop/files/85597/CHS_images.zip)
[Bug_Report-CHS.xlsx](https://github.com/Microsoft/TouchDevelop/files/85598/Bug_Report-CHS.xlsx)

**Comment by millerv** [comment]
Fixed, please retest.

**Comment by millerv** [comment]
Closing as fixed per email discussion with loc team.
