### ISSUE TITLE
Issues Report with localized CCGA DEU

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#417]
[Bug_Report-DEU.xlsx](https://github.com/Microsoft/TouchDevelop/files/85606/Bug_Report-DEU.xlsx)
[GER_images.zip](https://github.com/Microsoft/TouchDevelop/files/85607/GER_images.zip)

**Comment by millerv** [comment]
Fixed, please retest.

**Comment by millerv** [comment]
Closing as fixed per email discussion with loc team.
