### ISSUE TITLE
Issues Report with localized CCGA DUT

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#418]
[DUT_images.zip](https://github.com/Microsoft/TouchDevelop/files/85608/DUT_images.zip)
[Bug_Report-DUT.xlsx](https://github.com/Microsoft/TouchDevelop/files/85609/Bug_Report-DUT.xlsx)

**Comment by millerv** [comment]
Fixed, please retest.

**Comment by millerv** [comment]
Closing issue as fixed per email discussion with loc team.
