### ISSUE TITLE
Issues Report with localized CCGA FIN

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#419]
[Bug_Report-FIN.xlsx](https://github.com/Microsoft/TouchDevelop/files/85612/Bug_Report-FIN.xlsx)
[FIN_images.zip](https://github.com/Microsoft/TouchDevelop/files/85613/FIN_images.zip)

**Comment by millerv** [comment]
Fixed, please retest.

**Comment by millerv** [comment]
Closing issue as fixed per email discussion with loc team.
