### ISSUE TITLE
Issues Report with localized CCGA - VIE

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#435]
[VIE_images.zip](https://github.com/Microsoft/TouchDevelop/files/87219/VIE_images.zip)

**Comment by pelikhan** [comment]
What is this?

**Comment by millerv** [comment]
No worries - I've got this.

**Comment by millerv** [comment]
Fixed - please retest.

**Comment by millerv** [comment]
Closing issue as fixed per email discussion with loc team.
