### ISSUE TITLE
Missing Language Preference 

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/TouchDevelop#441]
"I really want to change my language preferences to English, but I can’t find the option in account settings."
https://touchdevelop.uservoice.com/admin/v3/suggestions/11658498/activity
touchdevelop.com/docs/account-settings

In this page, it seems like there should be a ‘preferred language’ button in my account settings, but there isn’t anything like that.

How can I change my language preferences? Thanks in advance.

**Comment by millerv** [comment]
Would it be possible to restore this functionality on the user's profile?  It's also useful for when the localization teams work on trying different languages overall.
