### ISSUE TITLE
manual push of 1 string localized into several languages

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#442]
[40333A_report_19_languages.xlsx](https://github.com/Microsoft/TouchDevelop/files/114174/40333A_report_19_languages.xlsx)
Hi,
we noticed that the corresponding tranlastion of one English string has not been properly reflected fo this set of languages:
Simplified Chinese, Finnish, Swedish, Italian, Hindi, Indonesia, Vietnamese, Thai,Turkish,Polish,Russian.

Could you please manually push these translations? they are included in the xls attached

Thanks
Ilaria

**Comment by millerv** [comment]
These are fixed and are present on the live site now.  The tutorial was also slightly altered so that "cheer message" only appears on the last step of the tutorial (with the "finished" button).

**Comment by millerv** [comment]
Going to close this one - seems like the fix is working out fine.
