### ISSUE TITLE
CCGA Dutch tutorials: missing captions

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#447]
Hi,
here the mapping of the missing captions across the different tutorials, with a descritpion of the repro step of the issue.

![image](https://cloud.githubusercontent.com/assets/15230722/13141234/17708a2a-d62e-11e5-9a6b-d5241768b1cd.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
Fixed the caption files and reuploaded to Azure storage - note the following:

Timestamps in this format cause captions to **not **display:  0:00:16.283 --> 0:00:18.051

Timestamps must be in this format: 00:16.283 --> 00:18.051
Or this format: 00:00:16.283 --> 00:00:18.051

**Comment by millerv** [comment]
No other issues reported, closing bug.
