### ISSUE TITLE
CCGA Dutch tutorials: missing posters

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#448]
Hi,
here a list of the missing posters across the tutorials plus the issue repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13141368/e0af93b8-d62e-11e5-8b06-924094dbdfe9.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
TDT16 - no missing posters, though it might seem like it since some videos are small and load quickly.  
TDT18 - also no missing posters, all appear correctly in-tutorial.

**Comment by millerv** [comment]
No other issues with this reported, closing bug.
