### ISSUE TITLE
It is really confusing for sounds to be under "art"

### ISSUE THREAD

**Issue by togakangaroo** [Microsoft/TouchDevelop#45]
I got really confused by this when going through the tutorial, and later when teaching students they were really confused by this also. The tutorial tells you to do `sound->play` but you're _supposed_ to click on `art`.

Tutorials should either say look under `art` or `sounds` should be a separate library (not sure the term here)

**Comment by mmoskal** [comment]
Peli - could you describe the issue in more detail?

**Comment by pelikhan** [comment]
I think the issue comes tutorials where you are supposed to look for a picture and you get a sound instead.
The second issue is probably the unicode characters for art which confuse beginners. In beginner mode, we should always keep them expanded.

**Comment by wuzappenin** [comment]
I agree. If I need to search for a sound, I always type "sound" at the end so I don't have to search through a bunch of pictures.
