### ISSUE TITLE
CCGA Arabic tutorials: missing posters

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#450]
Hi,
please find the details of the missing posters and repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13141776/fea20d68-d630-11e5-857a-9e61d427b4e9.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
There was one misnamed file for TDT6, but all the rest appeared fine.  Like with other "missing poster" bugs, it's possible for a video to load in quickly so that the poster doesn't show, which is fine.  The posters just help show a little of what's already inside the tutorial step's video.

**Comment by millerv** [comment]
Closing bug as fixed.
