### ISSUE TITLE
CCGA Arabic tutorials: issues with captions

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#451]
Hi,
please find the details of issues with captions and repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13141839/6aa82baa-d631-11e5-8841-62fe93a6327f.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
The situation with the truncated text is going to be difficult to fix - we should remove the symbols to be safe.
In the case of the caption order - we need to break those captions into smaller chunks and retime them to make this work out better.

**Comment by millerv** [comment]
Closing bug since updates to loc assets seemed to have nullified these issues.
