### ISSUE TITLE
CCGA Arabic tutorials: issue wrong poster background

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#452]
Hi,
please find issue details with wrong poster background and repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13141937/c993edfc-d631-11e5-9d50-cbf1f62919e5.png)

Thanks,
llaria

**Comment by millerv** [comment]
It is ok for the poster backgrounds to show black instead of white, so this will be a Won't Fix.

**Comment by millerv** [comment]
Closing as Won't Fix.
