### ISSUE TITLE
CCGA French tutorials: missing posters

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#454]
Hi,
here details for the issue of missing posters for French tutorials and the related repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13223861/f12018a6-d97d-11e5-97e1-007288b6dff6.png)

Thanks!
Ilaria

**Comment by millerv** [comment]
It looks like this is actually ok - the posters are present and show if the video takes a bit longer to load.  If the user doesn't see the poster, it's all right since it just shows what's already inside the video anyway.

**Comment by millerv** [comment]
Closing bug since updates to loc assets seemed to have nullified these issues.
