### ISSUE TITLE
CCGA French tutorials: issues with missing videos

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#455]
Hi,
here the details for the missing videos across the French tutorials and repro steps

![image](https://cloud.githubusercontent.com/assets/15230722/13224045/a7686e56-d97e-11e5-9ace-cbc4115c11a7.png)

Thanks
Ilaria

**Comment by millerv** [comment]
Closing bug since updates to loc assets seemed to have nullified these issues.
