### ISSUE TITLE
CCGA German tutorials: poster missing

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#456]
Hi,
we report only one issue with a poster missing, please find details:

![image](https://cloud.githubusercontent.com/assets/15230722/13258043/6268c118-da49-11e5-9ff0-a231dd80ab69.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
May need to recheck after the videos are fixed, but I think it's showing correctly, as far as I can tell.

**Comment by millerv** [comment]
Closing bug as fixed.
