### ISSUE TITLE
CCGA German tutorials: mixed language

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#458]
Hi,
it seems in TDT22 there is a string left in English, please refer to the screenshot.

![ger_globalbug_mix lang](https://cloud.githubusercontent.com/assets/15230722/13258542/74ca05cc-da4b-11e5-9f29-9a0662551c0c.png)

Thanks
Ilaria

**Comment by millerv** [comment]
Cannot reproduce.  This likely appeared due to the situation outlined in bug #459 - if they clicked on the incorrect TDT22, they would've seen the English version instead of the German version.

**Comment by millerv** [comment]
Closing bug.
