### ISSUE TITLE
CCGA German tutorials: missing lang code in landing page

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#459]
Hi,
language code is missing in the launching page of TDT22.
Please refer to the screnshot.

![ger_landing_page_missing lang code](https://cloud.githubusercontent.com/assets/15230722/13258611/bc3cb92c-da4b-11e5-84ed-974bb1b25fa6.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
Fixed. New URL:  https://www.touchdevelop.com/pluylcqpln

**Comment by millerv** [comment]
Closing bug as fixed.
