### ISSUE TITLE
Text input 'space' broken

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#467]
Since the text improvements commit, the 'space' has been causing erratic behaviour when entering it in text fields.

**Comment by pelikhan** [comment]
Got a repro

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Mar 22, 2016 at 2:59 PM -0700, "millerv" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #467<https://github.com/Microsoft/TouchDevelop/issues/467> to @pelikhan<https://github.com/pelikhan>.

-

**Comment by millerv** [comment]
@ianapps - can you provide a repro or video?  I will try to create one as well, but it'd be best to see what you're seeing.

**Comment by ianapps** [comment]
Appears resolved across all devices.
