### ISSUE TITLE
Turtle Shapes Tutorial 1: Does not detect first step completed

### ISSUE THREAD

**Issue by themooserooster** [Microsoft/TouchDevelop#47]
There seems to be no business logic that handles the completion of the first challenge (drawing a square). The tutorial expects a for loop drawing a square with sides of length 200. When this code is written and had run, the tutorial does not detect this success condition and move on the the next challenge.

**Comment by themooserooster** [comment]
![turtleshapes](https://cloud.githubusercontent.com/assets/1231168/6320437/f65aa9b2-baa2-11e4-979d-3d5c92aee0fb.png)

Image of completed drawing with code that generated it.

**Comment by pelikhan** [comment]
Hi Steve, I've fixed this recently. Could you try to update the turtle lib and run again?


Sent from Outlook<http://taps.io/outlookmobile>




On Sun, Feb 22, 2015 at 12:56 PM -0800, "Steve Price" <notifications@github.com<mailto:notifications@github.com>> wrote:


[turtleshapes]<https://cloud.githubusercontent.com/assets/1231168/6320437/f65aa9b2-baa2-11e4-979d-3d5c92aee0fb.png>

Image of completed drawing with code that generated it.

-
