### ISSUE TITLE
User Voice: Request to restore "box->set font family" feature

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#474]
On the Oct 2014 "What's New" page (https://www.touchdevelop.com/docs/what-s-new), there's mention of the ability to customize fonts in Touch Develop.

We've received a request on the User Voice site here for the ability to customize fonts:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/13344567-add-fonts 

Please consider restoring this feature, per user request.

**Comment by savaka2** [comment]
How about also adding fonts as a type of art resource, so you can upload your own fonts

Maybe use `box→set font(web safe fonts→serif)` or whatever font family you want for web safe fonts, and then `box→set font(✿my font)` for custom fonts
