### ISSUE TITLE
Debugging in VS Code

### ISSUE THREAD

**Issue by EvansThomas** [Microsoft/TouchDevelop#475]
Is there a way to setup debugging from VS Code through the VS Code Debugger for Chrome?

**Comment by millerv** [comment]
@mmoskal @pelikhan Would there be any way of going about this, or is the Touch Develop "expert skill level" debugger still the primary way to go?

**Comment by EvansThomas** [comment]
I don't mean debugging TD scripts. I meant debugging Touch Develop itself. I'd like to contribute code and thought debugging it would be a good way to understand how it works.

**Comment by pelikhan** [comment]
You can use your favorite browser debugger to understand what happens in TD.

Use the "jake local" command to run your local build...

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by EvansThomas** [comment]
I already do that. Debugging will be much easier if I could do it via VS Code using the VS Debugger for Chrome (https://github.com/Microsoft/vscode-chrome-debug). Debugging Typescript running on Chrome should be possible (https://blogs.msdn.microsoft.com/jtarquino/2016/01/24/debugging-typescript-in-visual-studio-code-and-chrome/) but I haven't been able to set it up for Touch Develop. Any pointers on it would be nice.

**Comment by pelikhan** [comment]
We haven't tried this, good luck :)

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________
