### ISSUE TITLE
CCGA: Issues with sign-in occurring (looping sign-in requests, leaderboard prompt, etc)

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#476]
Issues with sign-in are hampering learners during the CCGA workshops - will need to investigate for more precise details, but we're seeing some of the following:
- Signed-in accounts will be prompted to sign-in again after _just_ signing in
- After playing a game with a leaderboard while signed in (http://aka.ms/chasebasic), they are prompted to either "sign in" or "maybe later" - if they click on this sign in button, it doesn't proceed to sign in

I will try to investigate and add more details soon.

**Comment by brianbro** [comment]
Is there any update on this issue?  This is not a problem when I run from local using node.js (https://www.touchdevelop.com/docs/touchdevelop-local).  Not a browser issue as IE and Chrome seem to fail in the same way.

**Comment by millerv** [comment]
I know some of the key devs for this are out on long (and well-deserved) vacations, so this appears to be on hold until they return.

**Comment by brianbro** [comment]
@tballmsft Closed because "won't fix"?
