### ISSUE TITLE
Unclear if/how to attach Serial UART to hardware pins (non-USB, non-Bluetooth UART)

### ISSUE THREAD

**Issue by cefn** [Microsoft/TouchDevelop#479]
There is guidance at http://microbit-micropython.readthedocs.io/en/latest/uart.html indicating that the python library can access UART capabilities through the DAL which apply to hardware pins (note the tx and rx constructor arguments).

Am I right in thinking that the only UART exposed through Touchdevelop is the in-build UART-over-USB capability, and that accessing the Bluetooth UART service and use of a Hardware UART (through IO pins) is currently impossible?

If so, is there a chance that hardware or bluetooth UART will be exposed eventually through the serial library?

Cefn
http://shrimping.it

**Comment by pelikhan** [comment]
At this point, we are not planning any changes to the "built-in" libraries of the micro:bit. It leaves you with multiple options to implement your needs:

- write an extension library that contains the C++ glue to implement your custom behavior: https://github.com/Microsoft/microbit-touchdevelop/blob/master/EXTENSIONS.md
- file an issue at https://github.com/Microsoft/pxt-microbit where we would be able to handle this issue

**Comment by cefn** [comment]
Looks like pxt.io version already has support - using "serial redirect to". Thanks
