### ISSUE TITLE
Cloud State - Issue

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/TouchDevelop#484]
OS WIN10

Browser: Edge

![image](https://cloud.githubusercontent.com/assets/11206682/15945770/95988f64-2e59-11e6-8213-a84c03ad689c.png)
1. sign into touchdevelop

2 then open a new window

3 enter aka.ms/ccgacloud

4 prompt: cloud state requires sign in

5 click sign in

6 select preferred method of login

7 message: you are not signed in [sign in _ dismiss]  

8 goes back to step 4

here is the error 

![image](https://cloud.githubusercontent.com/assets/11206682/15945734/76077d22-2e59-11e6-9a40-9638cf72782f.png)

**Comment by mebrauns** [comment]
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

**Comment by pelikhan** [comment]
You need to add ?dbg=1 on the URL to receive a full log.
