### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by biosman** [Microsoft/TouchDevelop#488]
when I click Export Button I Get this message 
# Deployment not configured

   **Go to main script and try to deploy from there**
![export error](https://cloud.githubusercontent.com/assets/20271445/16547828/75f390a8-417a-11e6-94de-0e45960d59d9.png)

**Comment by EbrahimKaram** [comment]
The problem still exists for me 

What's the solution

**Comment by nm2501** [comment]
I have this problem too. How do you 'configure' the deployment?
