### ISSUE TITLE
Tutorials: no hints for adding parameters

### ISSUE THREAD

**Issue by elenadotedu** [Microsoft/TouchDevelop#49]
Tried to add an action with parameters today to the tutorial. Looks like there are no hints (with full hints turned on) when adding an action with parameters. Hints nicely guide users how to create an action, but stop when user is about to change parameter name. There should be a blue hint pointing to the parameter and then to rename on the keyboard, then it should guide them to type the name.

**Comment by pelikhan** [comment]
Could you try on https://www.touchdevelop.com/app/latest ?
Do you have a script id to repro the issue?

**Comment by togakangaroo** [comment]
This is also happening in the turtle snowflake tutorial. You have to look at the tutorial source to find out the parameters you must create

**Comment by elenadotedu** [comment]
Tried on  https://www.touchdevelop.com/app/latest, looks like the same thing. Also tried the snowflake tutorial. Just like togakangaroo said, it's happening there too. There is no hints to type in the parameter name.
