### ISSUE TITLE
Cordova export - no sound

### ISSUE THREAD

**Issue by miruwosi** [Microsoft/TouchDevelop#492]
I want to export a game (developed with TD 2 1/2 years ago) to cordova (android) 

Pictures and gameplay work fine, but i dont get sound working in the generated apk file. All art ressources seem to be exported correctly inside the art folder (sounds are exported twice as m4a  and wav(?)

The same behaviour happens with this test application
/btoqgfhu
There is no sound playing in the cordova export files (android and browser built). 

((Following the suggestions from #375 i tried to change the url path in cs.registerArtResource (.\u002fart\u002xxxxxxxxxxxxxxx") but without any success. When I replace the relative link to my local art files, with the original external url to the sound e.g. (https://az31353.vo.msecnd.net/pub/icvovfly) . the apk file plays sound in the emulator (but it fetches the sound from the web the moment it is needed).))

Any help would be highly appreciated.

**Comment by tballmsft** [comment]
No support for Cordova any more. Apologies.
