### ISSUE TITLE
Local Cache Selection

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#510]
Looking through the impending commits, it looks like the requirement to sign in will be removed - so we can better run TD locally.  Would it also be possible to clarify (or let the user define) where the local cache is stored.  This would ensure it is safe from clearing internet history, and allow the user to back it up.

With the above, TD would truly run locally and ensure the integrity of the app cache.

Its worth a beer if I ever meet you :-)

**Comment by pelikhan** [comment]
The local script are stored in IndexedDB typically, which may or may not be cleared when you clear your history. We would recommend saving the scripts as files and reload them when needed.
