### ISSUE TITLE
Image search fails after using "previous step" option

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#52]
In this tutorial, http://tdev.ly/kget, if I use "previous step" on the 3rd step (i.e. I go back to the 2nd step, in which I'm adding a sprite to the board), search does not return any results (see screenshot). However, if I delete the text ("robot") in the search bar and re-type it, search *does* return results.
![nosearch](https://cloud.githubusercontent.com/assets/918682/6341906/435c938c-bb85-11e4-8f60-a078caa4ee55.PNG)

**Comment by pelikhan** [comment]
Looks like we don't properly clear the search text box when setting the focus.
