### ISSUE TITLE
Need a way to fully customize tutorial ending

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#58]
Using a **final()** action to customize the end of a tutorial is good, but it doesn't allow for *full* control of a tutorial ending. For example, at the end of a tutorial currently, students are shown several other tutorials that might be interesting. In the context of a course or curriculum, this will be distracting for students. It would be preferable to have *full* control over what students are shown at the end of a tutorial. Perhaps adding a macro that could be used in **final()** to override the default behavior would do the trick.

**Comment by pelikhan** [comment]
You can control which tutorials get shown at the end of the tutorial:
* stnexttutorials takes a coma separate list of tutorial ids
````
{stnexttutorials:turtle shapes tutorial, turtle tree tutorial}
````
* stmoretutorials takes a topic id that will become the "more" button
````
{stmoretutorials:turtle tutorials}
````

**Comment by brian-swan** [comment]
**stnexttutorials** (as I've tried using it here: http://tdev.ly/wkuusskc) doesn't seem to let me specify ***no*** tutorials. Allowing that would be a good first step.

**Comment by pelikhan** [comment]
Right, I could support "none" and it would competent his this section.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Feb 26, 2015 at 2:15 PM -0800, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


stnexttutorials (as I've tried using it here: http://tdev.ly/wkuusskc) doesn't seem to let me specify no tutorials. Allowing that would be a good first step.

-
