### ISSUE TITLE
Need a way to "reload" a game

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#60]
I need the ability to “reload” a game (or page or wall) multiple times. I know this can be done by using the “app” template, but I don’t want to have to explain pages, boxes, etc. (i.e. the “app” template comes with too much conceptual overhead – it gets in the way of teaching more fundamental concepts).
 
Here is a more concrete example: http://tdev.ly/ephymzes
- I want to use this (as a tutorial) to teach conditionals, but…
- To make it more fun for students, I want a way to “reload” the game at the end (i.e. ask another question, get another answer).
- I’m using the “game” template, because it allows me to easily create a board and position sprites (note that I hide the HUD – these aren’t necessary for this “game”).
- I’ve tried using a while loop (which hasn’t yet been taught by the time we reach this tutorial in the curriculum) like this:
 
var b := wall->ask Boolean
while(b)
    [game code here]
    b := wall->ask Boolean
end while
 
But, this doesn’t work. All “wall->ask …” statements are executed before all other code (there are things I fundamentally don’t understand about the wall and board objects and how code is executed in TD).
 
This is just one example. I’ve run into this requirement in other tutorials too. So…
 
1.      For my specific example, are they ways to do what I want?
2.      In general, what is the best approach to “reload” a game? (Do we need another template?)

**Comment by brian-swan** [comment]
Adding email exchange with Peli:

From: Brian Swan

If by “working” you mean that I’m prompted to play again immediately (I don’t actually get to see the important aspects of the game running…i.e. the answer to my question), then yes, it’s working. But this doesn’t help me achieve my goal. So, I’m back to my original questions…
-------------------
From: Peli de Halleux 

It works on the published script. What behavior are you seeing? File it on github.
-------------------
From: Brian Swan

I hadn’t tried that, but I just did and it doesn’t work (at least not as I’d expected). The docs say that it “restarts the app and pops a restart dialog”. I’m not getting a dialog or a restart. Instead, it appears to just stop the app: http://tdev.ly/kfcpaoof 
--------------------- 
From: Peli de Halleux 

Have you tried app->restart ?

**Comment by pelikhan** [comment]
I am not sure I understand what you are trying to do. By reloading, do you mean loading parts of another script in the current script?

**Comment by brian-swan** [comment]
No.
Let's use this as an example: http://tdev.ly/ephymzes. I need a way to *easily* let this game go on indefinitely (i.e. ask a question, see the answer, ask a question, see the answer, ...). This seems analogous to "reloading" a web page (hence my title for this bug). Having a simple "try again" button at the bottom of the page would work for this example. However, in other cases, I might want to keep track of a score.
Does that make it clearer?

**Comment by pelikhan** [comment]
I see: why not wrapping the whole thing in a while true loop?

Also, don't use the textbook. Instead clear the wall and post the question and answer again. Also instead of text, use images - makes the app more fun.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Feb 26, 2015 at 2:28 PM -0800, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


No.
Let's use this as an example: http://tdev.ly/ephymzes. I need a way to easily let this game go on indefinitely (i.e. ask a question, see the answer, ask a question, see the answer, ...). This seems analogous to "reloading" a web page (hence my title for this bug). Having a simple "try again" button at the bottom of the page would work for this example. However, in other cases, I might want to keep track of a score.
Does that make it clearer?

-

**Comment by brian-swan** [comment]
I was hoping to avoid using a **while** loop. At this point in the course, students will not have been exposed to the concept of a loop. I'm looking for a way to make games/apps fun *before* teaching certain concepts. Eventually, when I do teach loops, we could come back to this example and use a **while** loop. Until then, I'd like to have a "teaching feature" that let's me get around this.

**Comment by pelikhan** [comment]
Then use wall->prompt before call app restart

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Feb 26, 2015 at 2:56 PM -0800, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


I was hoping to avoid using a while loop. At this point in the course, students will not have been exposed to the concept of a loop. I'm looking for a way to make games/apps fun before teaching certain concepts. Eventually, when I do teach loops, we could come back to this example and use a while loop. Until then, I'd like to have a "teaching feature" that let's me get around this.

-

**Comment by brian-swan** [comment]
I've tried that and it doesn't produce the behavior I want. I can enter a question, but I never get to see the answer. Other suggestions?

**Comment by pelikhan** [comment]
First use ask string for the question then wall prompt with the answer then restart

Sent from my Windows Phone
________________________________

**Comment by brian-swan** [comment]
I've tried that in this version: http://tdev.ly/easqegrf. 
1. It doesn't seem to work as expected - I don't get the "restart".
2. I don't get to see the graphics, which makes it less fun.

**Comment by pelikhan** [comment]
You don't need a game board for this. Try http://tdev.ly/qwujusoj . 
I see that app->restart does not work in that case. Will investigate.

**Comment by brian-swan** [comment]
If I don't use a game board, I don't have a way to position and size sprites. I can implement the necessary *functionality* without a game board, but I can't create the affect I want without it.

**Comment by brian-swan** [comment]
Here's a version that should make clearer what I'm looking for: http://tdev.ly/steeajmf. I would be OK with telling students to call a custom function that I provide that allows them to play again (as shown in the example). However, note that that I'm calling **app->restart** in the custom function, but it just stops the app (doesn't appear to then start it). If **app->restart** were working correctly (and preferably with out a prompt), then this particular example would be OK.

**Comment by pelikhan** [comment]
In this example, you should attach a handler on board->on tap and restart there.

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, Feb 27, 2015 at 2:39 PM -0800, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a version that should make clearer what I'm looking for: http://tdev.ly/steeajmf. I would be OK with telling students to call a custom function that I provide that allows them to play again (as shown in the example). However, note that that I'm calling app->restart in the custom function, but it just stops the app (doesn't appear to then start it). If app->restart were working correctly (and preferably with out a prompt), then this particular example would be OK.

-

**Comment by brian-swan** [comment]
Sure...that's even better...but it still requires that **app->restart** works as expected. I'm assuming that since you closed this issue, you've fixed it. I'll wait for the changes to make it to app/latest, then I'll try using **app->restart** in **board->on tap**. Thanks.

**Comment by brian-swan** [comment]
This works now, but I have an additional request: Can I have an overload for **app->restart** that doesn't take any params and doesn't pop a dialogue to run again? (just automatically runs the app again)
