### ISSUE TITLE
Hint control not working in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#61]
I'm trying to use {sthints:semi} to reduce the hinting provided in this tutorial: http://tdev.ly/eokya. However, I don't see a difference between {sthints:full} and {sthints:semi}. Either this feature is not working or I'm doing something wrong.

**Comment by pelikhan** [comment]
Would you have the time to look into this one?

**Comment by brian-swan** [comment]
Changing this to a P1 bug since we need the ability to better control hints in our curriculum.

**Comment by brian-swan** [comment]
Bumping this one. We are nearing finalization of tutorials for our curriculum and need this functionality.

**Comment by pelikhan** [comment]
will take a look today

**Comment by pelikhan** [comment]
There seems to be some kind of interaction between stauto and this flag. Somehow, the information gets stored properly in the step but that step gets thrown away later on.

**Comment by brian-swan** [comment]
Is it something that can be resolved?

**Comment by tballmsft** [comment]
Drop dead date is June 26.

**Comment by brian-swan** [comment]
This is great...thanks! Question: If I specify {sthints:full} at the beginning of a tutorial, should the entire tutorial stay in “full” mode? Currently, it does not…wonder if this is a bug. I would expect things to work like this:
•	If sthints is not used at all, hinting starts as “full”, then moves to “semi” after some number of steps (with the “do it yourself” dialogue popping to explain what is happening).
•	If sthints:full is specified at the beginning, then the entire tutorial is in “full” hinting mode (or at least until the sthints macro is used again to specify a new hint level)
•	If sthints:semi is specified at the beginning, then the entire tutorial is in “semi” hinting mode (or at least until the sthints macro is used again to specify a new hint level)

**Comment by mmoskal** [comment]
Looks like a bug. Let me look into this.

**Comment by brian-swan** [comment]
I was using {sthints} in main. If I use it in the 1st real step of the tutorial to set the hint level, then it seems to work as I expected (and as I described above).
