### ISSUE TITLE
"we think it's not quite right" is sometimes misleading in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#62]
In a tutorial, the "we think it's not quite right" prompt can sometime be misleading. For example, when I'm prompted to type in a function for which the default parameter is not desired, I'm then immediately prompted to change the parameter with "we think it's not quite right". This is confusing as I followed the previous prompt correctly. In this context, a better prompt might be "let's change this" (or something like that). 
I imagine this may be a tricky bug to fix as it depends on context. Sometimes code isn't "quite right" due to a user mistake.

**Comment by pelikhan** [comment]
We cannot differentiate both cases. We can rephrase in all cases to "let's change this" to provide more positive reinforcement. thoughts?

**Comment by brian-swan** [comment]
If this is an easy change to make, let's try "let's change this". We may find that it works OK for all contexts. If it doesn't, we change it to something better (assuming the change is an easy one).
