### ISSUE TITLE
Tutorial stalls after validator step

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#68]
This tutorial uses the {stvalidator} macro at step 5: http://tdev.ly/cycvsbbk. Upon successful completion of the step, the tutorial does not prompt the user to go on to the next step.

**Comment by brian-swan** [comment]
I figured out why this is happening: I had the wrong turtle library. The library that is automatically added when you create a script from the turtle app template doesn't have the validator and maze fixes that are in the updated version. (I think this should be the default turtle library.)

**Comment by pelikhan** [comment]
Please file a separate issue for this. We should always update the default templates to the latest version of libraries.

**Comment by brian-swan** [comment]
Will do.
