### ISSUE TITLE
Script templates should have latest libraries

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#69]
When creating a script from one of the script templates (e.g. game, turtle, etc.), the libraries that are included with the script should be the latest versions of those libraries. Currently, the turtle library that is included with the turtle script template is not the latest version. The latest version has useful fixes and updates.

**Comment by v-vamell** [comment]
This is currently marked as Won't Fix - will be shipped and updated during the core library major update.
