### ISSUE TITLE
Tutorial can't "find" action with 2 output params

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#7]
I'm using {stauto} to include an action as part of a tutorial. The action returns two output params. When you follow the tutorial, the tutorial engine can't "find" the action: http://tdev.ly/qjdjixqu. This does not happen if the function has one or none output params.

**Comment by brian-swan** [comment]
I'm still seeing this issue at step 8 in this tutorial: http://tdev.ly/kglwc. (I'm on /app/latest.)

**Comment by mmoskal** [comment]
I suggest avoiding multiple return values in actions.

The feature does not transfer to mainstream languages. We may consider deprecating it, along with adding a "return" statement. It already is not first class (the `Task of` data type doesn't work with it, and you cannot call multiple-return actions inside expressions). The only reason for keeping it right now seems to be "extract to action" refactoring.

**Comment by brian-swan** [comment]
Very good point. I can easily split this up in to two functions that each return a single parameter. Thanks.

**Comment by pelikhan** [comment]
It's actually nicely supported in python which implicitely unrolls any object field into separate variable. This is particularly relevant in the Minecraft Pi scenario:

    x, y, z := minecraft pi->player->position

**Comment by mmoskal** [comment]
I recall we decided a custom object with x,y,z was the way to go.

**Comment by pelikhan** [comment]
Yes we did. Closed.
