### ISSUE TITLE
"Preview" for tutorials creation doesn't appear to work the same way as in the tutorial on tutorials

### ISSUE THREAD

**Issue by SocalSam** [Microsoft/TouchDevelop#70]
The Preview button doesn't appear to work as expected, that is: Tutorial functions as designed.  Specifically the tutorial /yewwa.

Also the tutorial on tutorial discusses a follow button, but there is no follow button.

**Comment by pelikhan** [comment]
The follow button can be found on the script list view. You have to leave the editor and you will find under the big edit, publish, ... buttons.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Mar 2, 2015 at 2:37 PM -0800, "SocalSam" <notifications@github.com<mailto:notifications@github.com>> wrote:


The Preview button doesn't appear to work as expected, that is: Tutorial functions as designed. Specifically the tutorial /yewwa.

Also the tutorial on tutorial discusses a follow button, but there is no follow button.

-
