### ISSUE TITLE
Create group button under social does not appear if the environment is set to coder or beginner

### ISSUE THREAD

**Issue by SocalSam** [Microsoft/TouchDevelop#71]
The social group/create group does not appear if you are set to coder or beginner.  This should be modified to have the "create group" show up if I have coder set.

**Comment by pelikhan** [comment]
It does appear in coder skill under the social hub.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Mar 2, 2015 at 2:51 PM -0800, "SocalSam" <notifications@github.com<mailto:notifications@github.com>> wrote:


The social group/create group does not appear if you are set to coder or beginner. This should be modified to have the "create group" show up if I have coder set.

-

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/6477354/c10887de-c1d7-11e4-946a-819c0b981c0e.png)
