### ISSUE TITLE
editor buttons messed up after editing text in the calculator

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/TouchDevelop#72]
They overlap each other.

**Comment by pelikhan** [comment]
This is related to my change that added a check mark button to the inline string editing.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, Mar 2, 2015 at 3:26 PM -0800, "Micha³ Moskal" <notifications@github.com<mailto:notifications@github.com>> wrote:


They overlap each other.

-

**Comment by pelikhan** [comment]
Also when adding comment on field
![image](https://cloud.githubusercontent.com/assets/4175913/6478471/9fd30ef2-c1e8-11e4-81d9-b2642e68a61f.png)
