### ISSUE TITLE
Preserve authoring mode when sharing script

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#73]
This script was authored in "split" mode: http://tdev.ly/aaerk. It is designed to be edited and run in "split: mode by students. However, when you follow this link and click on "edit in TouchDevelop", then click "edit", it does not open in "split" mode. Many students will be confused unless they go the extra step of going into "split" mode. It would be great if authoring a tutorial in split mode meant that when others edited it, it opened in the same mode by default.

**Comment by pelikhan** [comment]
We currently do not store any "view" information in the script code itself since changing the view would then be considered as a change in the code and an update.
In beginner mode, all scripts are opened in split mode, maybe this should be extended to coder mode.

**Comment by brian-swan** [comment]
I wouldn’t want all scripts in coder mode to be opened in split screen. I have lots of tutorials at that level that I want in classic mode by default. What would be a nice addition is to be able to set a flag on a script that made it open in split screen when someone else opened it for editing. Of course, that person could change it back to classic mode, but the default would be split screen.

**Comment by pelikhan** [comment]
>  I have lots of tutorials at that level that I want in classic mode by default. 
Tutorials should not be tied to a level. You should use the ``{flag:nosplit}`` macro to ensure that a tutorial is not opened in split screen.

**Comment by mmoskal** [comment]
We could save the “split” mode information in the script text, but only at the moment of publishing, and use it as a hint when opening the script.

**Comment by brian-swan** [comment]
Sorry...my comment about tutorials before doesn't apply here. I'm only concerned about non-tutorials here. If I understand Michal's suggestion correctly, you would save the "split" mode information when I publish a script. Then, when I share it and someone opens it, it would open in "split" mode. 
That would be perfect.

**Comment by pelikhan** [comment]
We would still want to make the split mode default in "coder" mode. Do you know the list of tutorials that require non-split? Could you annotate them with ``{flag:nosplit}``?

**Comment by brian-swan** [comment]
I could, but I have more tutorials that I want in non-split mode than I do in split mode. It would be easier for me to have the default mode be non-split, then annotate with {flag:split} when I wanted split mode. That said, I can work with whatever you decide.

**Comment by pelikhan** [comment]
If you could update your tutorial, we think that a split mode by default is a better experience for beginners.
