### ISSUE TITLE
Problems with adding custom actions in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#74]
This tutorial requires that you add two custom actions: http://tdev.ly/eeaiezep
- Problem 1: The tutorial consistently crashes after prompting you to create the first custom action (**do stuff()** ). The tutorial recovers (I get a "the script reloaded" message), but the crash is confusing. You are given the same set of instructions twice.
- Problem 2: When adding the second custom action (**do stuff2()** ), I'm prompted to edit the first custom action (change its name and its code). I never actually create a second custom action. Of course, this causes the tutorial to fail: When I get back to main, where **do stuff** was called, we have a problem because no such action exists.

**Comment by mmoskal** [comment]
I've fixed this particular one earlier today, but there were weird problems with variable definitions. These are fixed in 1eedfd9e56c36f5fe8cbc36fe99f34a7162e62e2
