### ISSUE TITLE
Change size, timing, placement of "click here to continue tutorial" message

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#8]
The timing, size, and placement of the “click here to continue tutorial” message (shows when you are running the code of a tutorial) are awkward.
* Can the timing be customizable? Sometimes it shows up too soon or too late depending on the nature of the tutorial step. In either case it leads to confusion.
* Can the size be changed (or be customizable)? It often covers up important elements of the running script.

**Comment by pelikhan** [comment]
The prompt is now smaller. Please reo-open as needed.
