### ISSUE TITLE
Support animated .gif's in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#81]
In the same way that images and videos can be embedded as instructional steps in a video, it would be useful to be able to embed animated .gif files.

**Comment by brian-swan** [comment]
Could I get an update on the status of this feature? (Is it likely to be added? If yes, when?) We need to make some decisions now based on its availability.

**Comment by pelikhan** [comment]
It is not clear whether we will support this feature for art resources but we could support external links in docs.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Mar 26, 2015 at 7:23 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could I get an update on the status of this feature? (Is it likely to be added? If yes, when?) We need to make some decisions now based on its availability.

-

**Comment by brian-swan** [comment]
Just want to clarify: Are you saying that its not clear whether you will support .gif's in used in tutorials?

**Comment by pelikhan** [comment]
Not as art variable.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Mar 26, 2015 at 10:01 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just want to clarify: Are you saying that its not clear whether you will support .gif's in used in tutorials?

-

**Comment by brian-swan** [comment]
Sorry. I didn't mean as art variable. I meant as an instruction step in a tutorial. i.e. Instead of an embedded video, will you support an embedded .gif file?

**Comment by pelikhan** [comment]
Yes we can support that.

Sent from my Windows Phone
________________________________

**Comment by brian-swan** [comment]
Thanks! I'll plan on it.

**Comment by pelikhan** [comment]
In 23c00f70a79138b92efc50b8638ed3d27cf96362 , the {pic macro supports external images hosted on https://

    {pic:https://.....}
