### ISSUE TITLE
Remove or make optional the publish screen on tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#82]
Most of the time, students won't want to publish a script that they have created as part of a tutorial (at least this is true in the curriculum I am building). Students may want to "keep editing" at the end of a tutorial (and that experience is much cleaner now), but they will only want to publish after they have made some customizations of their own.

To make the end-of-tutorial experience even better, it would be nice to either remove the "publish" screen or have control over whether it is shown.

**Comment by pelikhan** [comment]
We can probably add a macro that disables it. It is already disabled if the user is not signed in.

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Mar 11, 2015 at 9:23 AM -0700, "Brian Swan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Most of the time, students won't want to publish a script that they have created as part of a tutorial (at least this is true in the curriculum I am building). Students may want to "keep editing" at the end of a tutorial (and that experience is much cleaner now), but they will only want to publish after they have made some customizations of their own.

To make the end-of-tutorial experience even better, it would be nice to either remove the "publish" screen or have control over whether it is shown.

-

**Comment by pelikhan** [comment]
fixed by 7aa9a0bda7d56c49e7950f70902c92e6aa6cc490
