### ISSUE TITLE
Running script is cluttered

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#85]
When I run a script, there is a lot of text at the bottom of the window: "touchdevelop", "privacy and cookies", "legal', copyright symbol, etc. All of these things link to the same popup. Consolidating these into one would reduce the clutter on the page.

**Comment by SocalSam** [comment]
Hi Brian, sadly the over abundance of caution requires that these items be shown separately on the page.  If you note that Github has even more links at the bottom of the page.
