### ISSUE TITLE
Ability to run in "slow mo"

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#93]
## The feature that Peli describes in the email exchange below would probably suit my needs here.

From: Peli de Halleux 
Sent: Wednesday, March 18, 2015 12:30 PM
To: Brian Swan; Michal Moskal; Jonathan Protzenko
Subject: RE: Running in "slow mo"? 

No it does not exist. We do have a debugger though which works in the split screen experience. One could imagine to have a special “stcmd:run” command that would turn on this mode.

From: Brian Swan 
Sent: Wednesday, March 18, 2015 12:29 PM
To: Peli de Halleux; Michal Moskal; Jonathan Protzenko
Subject: RE: Running in "slow mo"? 

Does this “auto-stepper” exist now? Is using it supported in tutorials?

From: Peli de Halleux 
Sent: Wednesday, March 18, 2015 12:21 PM
To: Brian Swan; Michal Moskal; Jonathan Protzenko
Subject: RE: Running in "slow mo"? 

This is related to supported an “auto-stepper” mode in the debugger. The idea would be to have the debugger step automatically and highlight each line of code execution. Effectively, looks related to your slow-momode.

From: Brian Swan 
Sent: Wednesday, March 18, 2015 12:18 PM
To: Peli de Halleux; Michal Moskal; Jonathan Protzenko
Subject: Running in "slow mo"? 

Is there a way to slow down script execution temporarily? For example, I might want students to create a loop in which something is posted to the wall. If I want students to see each of those things posted one-by-one, I’d need some way to slow down script execution.

Is there a way to do this?

Thanks.

-Brian

**Comment by v-vamell** [comment]
Currently on hold - will be taken up later
