### ISSUE TITLE
Allow renaming of loop variable in for each loops

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#94]
In a **for each** loop, I currently can't rename the loop variable, so I end up with code like this:

  <code>for each s in numbers</code> (where **s** is a collection of numbers)

It would be nice to be able to rename **s** to something like **number**, so my code looks like this:

   <code>for each number in numbers</code>

**Comment by pelikhan** [comment]
You can rename the variable from the body of the loop.

**Comment by pelikhan** [comment]
Duplicated of #88

**Comment by brian-swan** [comment]
I see that #88 and #94 are both closed. Does this mean that this issue won't be addressed? (I don't think that renaming the variable within the body of the loop is satisfactory.)

**Comment by pelikhan** [comment]
#88 is still opened.

**Comment by brian-swan** [comment]
Ah...you're right. Sorry.
